### ISSUE TITLE
Idk, but it spams the console

### ISSUE THREAD

**Issue by Ste1n1** [NEZNAMY/TAB#1035]
### Server version

Paper 1.19.2

### TAB version

v.3.3.0

### Stack trace

[13:23:20 WARN]: org.bukkit.command.CommandException: Unhandled exception executing command 'tab' in plugin TAB v3.3.0
[13:23:20 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
[13:23:20 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[13:23:20 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916)
[13:23:20 WARN]:        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:980)
[13:23:20 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.Skript.dispatchCommand(Skript.java:1463)
[13:23:20 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.effects.EffCommand.execute(EffCommand.java:82)
[13:23:20 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[13:23:20 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:23:20 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[13:23:20 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[13:23:20 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[13:23:20 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[13:23:20 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[13:23:20 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:23:20 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:23:20 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[13:23:20 WARN]:        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:372)
[13:23:20 WARN]:        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$0(PlayerList.java:309)
[13:23:20 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:23:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:23:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:23:20 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[13:23:20 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[13:23:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:23:20 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[13:23:20 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[13:23:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:23:20 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1289)
[13:23:20 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1177)
[13:23:20 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[13:23:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:23:20 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.Property.getFormat(me.neznamy.tab.api.TabPlayer)" because the return value of "me.neznamy.tab.api.TabPlayer.getProperty(String)" is null
[13:23:20 WARN]:        at TAB v3.3.0.jar//me.neznamy.tab.shared.features.nametags.NameTag.updateTeamData(NameTag.java:264)
[13:23:20 WARN]:        at TAB v3.3.0.jar//me.neznamy.tab.shared.features.nametags.NameTag.toggleNameTagVisibilityView(NameTag.java:386)
[13:23:20 WARN]:        at TAB v3.3.0.jar//me.neznamy.tab.shared.features.nametags.unlimited.NameTagX.toggleNameTagVisibilityView(NameTagX.java:339)
[13:23:20 WARN]:        at TAB v3.3.0.jar//me.neznamy.tab.shared.command.NameTagCommand.toggle(NameTagCommand.java:67)
[13:23:20 WARN]:        at TAB v3.3.0.jar//me.neznamy.tab.shared.command.NameTagCommand.execute(NameTagCommand.java:36)
[13:23:20 WARN]:        at TAB v3.3.0.jar//me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:55)
[13:23:20 WARN]:        at TAB v3.3.0.jar//me.neznamy.tab.platforms.bukkit.BukkitTAB$TABCommand.onCommand(BukkitTAB.java:127)
[13:23:20 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[13:23:20 WARN]:        ... 30 more

### Additional info

It works, the plugin is really great, but this error is too bad ig

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
outdated

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/d126de42-95ff-4f3a-b3ff-2b8082c98883)
![image](https://github.com/NEZNAMY/TAB/assets/6338394/e1802d37-b18b-4369-8380-aa1b7a089ae2)
Where is that latest?
