### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ste1n1** [NEZNAMY/TAB#1038]
### Server version

Paper 1.19.2

### TAB version

4.0.3

### Stack trace

[16:44:48 WARN]: org.bukkit.command.CommandException: Unhandled exception executing command 'tab' in plugin TAB v4.0.3
[16:44:48 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
[16:44:48 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[16:44:48 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916)
[16:44:48 WARN]:        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:980)
[16:44:48 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.Skript.dispatchCommand(Skript.java:1463)
[16:44:48 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.effects.EffCommand.execute(EffCommand.java:82)
[16:44:48 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[16:44:48 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[16:44:48 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[16:44:48 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[16:44:48 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[16:44:48 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[16:44:48 WARN]:        at Skript-2.6.4.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[16:44:48 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:44:48 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:44:48 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[16:44:48 WARN]:        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:372)
[16:44:48 WARN]:        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$0(PlayerList.java:309)
[16:44:48 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:44:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[16:44:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[16:44:48 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[16:44:48 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[16:44:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[16:44:48 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[16:44:48 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[16:44:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[16:44:48 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1289)
[16:44:48 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1177)
[16:44:48 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[16:44:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:44:48 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.shared.Property.getFormat(me.neznamy.tab.shared.platform.TabPlayer)" because the return value of "me.neznamy.tab.shared.platform.TabPlayer.getProperty(String)" is null
[16:44:48 WARN]:        at TAB v4.0.3.jar//me.neznamy.tab.shared.features.nametags.NameTag.updateTeamData(NameTag.java:233)
[16:44:48 WARN]:        at TAB v4.0.3.jar//me.neznamy.tab.shared.features.nametags.NameTag.toggleNameTagVisibilityView(NameTag.java:334)
[16:44:48 WARN]:        at TAB v4.0.3.jar//me.neznamy.tab.shared.features.nametags.unlimited.NameTagX.toggleNameTagVisibilityView(NameTagX.java:285)
[16:44:48 WARN]:        at TAB v4.0.3.jar//me.neznamy.tab.shared.command.NameTagCommand.toggle(NameTagCommand.java:69)
[16:44:48 WARN]:        at TAB v4.0.3.jar//me.neznamy.tab.shared.command.NameTagCommand.execute(NameTagCommand.java:38)
[16:44:48 WARN]:        at TAB v4.0.3.jar//me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:56)
[16:44:48 WARN]:        at TAB v4.0.3.jar//me.neznamy.tab.platforms.bukkit.BukkitTabCommand.onCommand(BukkitTabCommand.java:34)
[16:44:48 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:44:48 WARN]:        ... 30 more

### Additional info

Keeps spamming the console

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
How can a command spam? Also check /tab cpu.

**Comment by Ste1n1** [comment]
[17:04:32 INFO]: [TAB] ║             [ TAB CPU Stats ]             
[17:04:32 INFO]: [TAB] ║ CPU stats from the last 10 seconds
[17:04:32 INFO]: [TAB] ║                                                    
[17:04:32 INFO]: [TAB] ║ Top 5 placeholders:
[17:04:32 INFO]: [TAB] ║ %luckperms_suffix% (500) - 0.047%
[17:04:32 INFO]: [TAB] ║ %animation:head% (50) - 0.024%
[17:04:32 INFO]: [TAB] ║ %gamemode% (100) - 0.011%
[17:04:32 INFO]: [TAB] ║ %time% (500) - 0.01%
[17:04:32 INFO]: [TAB] ║ %lands_land_name_here% (500) - 0.006%
[17:04:32 INFO]: [TAB] ║                                                    
[17:04:32 INFO]: [TAB] ║ Features:
[17:04:32 INFO]: [TAB] ║ Refreshing placeholders (0.129%):
[17:04:32 INFO]: [TAB] ║     Refreshing placeholders - 0.129%
[17:04:32 INFO]: [TAB] ║     Updating placeholders - 0%
[17:04:32 INFO]: [TAB] ║ Unlimited NameTags (0.127%):
[17:04:32 INFO]: [TAB] ║     Packet reading (out) - 0.082%
[17:04:32 INFO]: [TAB] ║     PacketPlayOutEntity - 0.031%
[17:04:32 INFO]: [TAB] ║     Refreshing NameTag visibility - 0.01%
[17:04:32 INFO]: [TAB] ║     Player Sneak - 0.003%
[17:04:32 INFO]: [TAB] ║ Header/Footer (0.048%):
[17:04:32 INFO]: [TAB] ║     Updating header/footer - 0.048%
[17:04:32 INFO]: [TAB] ║ NameTags (0.01%):
[17:04:32 INFO]: [TAB] ║     Refreshing vehicles - 0.006%
[17:04:32 INFO]: [TAB] ║     Processing player movement - 0.005%
[17:04:32 INFO]: [TAB] ║ BossBar (0.002%):
[17:04:32 INFO]: [TAB] ║     Updating text - 0.002%
[17:04:32 INFO]: [TAB] ║     Command Preprocess - 0%
[17:04:32 INFO]: [TAB] ║                                                    
[17:04:32 INFO]: [TAB] ║ Placeholders Total: 0.12%
[17:04:32 INFO]: [TAB] ║ Plugin internals: 0.196%
[17:04:32 INFO]: [TAB] ║ Total: 0.316%
[17:04:32 INFO]: [TAB] ║             [ TAB CPU Stats ]
