### ISSUE TITLE
Upgrade from v3.2.4 to v4.0.6 - Config no longer working

### ISSUE THREAD

**Issue by codeHusky** [NEZNAMY/TAB#1091]
### Server version

Paper 1.20.2 git-Paper-207

### TAB version

4.0.6

### Stack trace

```
[18:08:35 INFO]: [TAB] [WARN] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[18:08:35 INFO]: [TAB] [WARN] java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
[18:08:35 INFO]: [TAB] [WARN]   at TAB v4.0.6.jar//me.neznamy.tab.shared.placeholders.TabPlaceholder.<init>(TabPlaceholder.java:62)
[18:08:35 INFO]: [TAB] [WARN]   at TAB v4.0.6.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.<init>(PlayerPlaceholderImpl.java:39)
[18:08:35 INFO]: [TAB] [WARN]   at TAB v4.0.6.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.registerPlayerPlaceholder(PlaceholderManagerImpl.java:253)
[18:08:35 INFO]: [TAB] [WARN]   at TAB v4.0.6.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.registerPlayerPlaceholder(PlaceholderManagerImpl.java:32)
[18:08:35 INFO]: [TAB] [WARN]   at TAB v4.0.6.jar//me.neznamy.tab.shared.backend.BackendPlatform.registerPlaceholders(BackendPlatform.java:31)
[18:08:35 INFO]: [TAB] [WARN]   at TAB v4.0.6.jar//me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.registerPlaceholders(BukkitPlatform.java:110)
[18:08:35 INFO]: [TAB] [WARN]   at TAB v4.0.6.jar//me.neznamy.tab.shared.TAB.load(TAB.java:167)
[18:08:35 INFO]: [TAB] [WARN]   at TAB v4.0.6.jar//me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:24)
[18:08:35 INFO]: [TAB] [WARN]   at TAB v4.0.6.jar//me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:55)
[18:08:35 INFO]: [TAB] [WARN]   at TAB v4.0.6.jar//me.neznamy.tab.platforms.bukkit.BukkitTabCommand.onCommand(BukkitTabCommand.java:34)
[18:08:35 INFO]: [TAB] [WARN]   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:08:35 INFO]: [TAB] [WARN]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[18:08:35 INFO]: [TAB] [WARN]   at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989)
[18:08:35 INFO]: [TAB] [WARN]   at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[18:08:35 INFO]: [TAB] [WARN]   at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2207)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2167)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[18:08:35 INFO]: [TAB] [WARN]   at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.util.thread.IAsyncTaskHandler.bp(IAsyncTaskHandler.java:114)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1410)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[18:08:35 INFO]: [TAB] [WARN]   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[18:08:35 INFO]: [TAB] [WARN]   at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce (if known)

Using this config triggers the exception:
https://pastebin.com/GKZ6ydvF

### Additional info

This config has been working for a while, but we haven't updated in some time. If my config's wrong let me know where.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by codeHusky** [comment]
Adjusted placeholder-output-replacements to this and the error was resolved, not certain if the breaking change was intentional or my config was just a bit off. Here it is anyway:
```
placeholder-output-replacements:
  '%vanished%':
    'true': ' &8[&c&lV&8]'
    'false': ''
  '%afk%':
    'true': ' &o[AFK]&r'
    'false': ''
  '%displayname%': 
    "%displayname%": '%essentials_nickname%'
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
```

**Comment by Tanguygab** [comment]
This was never supported as far as I know, or at least never mentioned on the wiki.

**Comment by NEZNAMY** [comment]
`  '%displayname%': '%essentials_nickname%'` is not and was never a valid line for replacements. It is, and has always been a map named after placeholder identifier with the `key` being value to replace and `value` being value to replace with.
