### ISSUE TITLE
Team so tab break with Waterfall 1.20.2+

### ISSUE THREAD

**Issue by Funasitien** [NEZNAMY/TAB#1098]
### Server version

Paper 1.20.1 - Waterfall 1.20.2

### TAB version

4.0.3

### Stack trace

```java
06.10.2023 - 18:17:56 - [TAB v4.0.3] Tried to modify non-existing team null for player Funasitien
06.10.2023 - 18:18:07 - [TAB v4.0.3] An error was thrown when executing task
06.10.2023 - 18:18:07 - java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.packet.ScoreboardDisplay.<init>(byte, java.lang.String)'
06.10.2023 - 18:18:07 - 	at me.neznamy.tab.platforms.bungeecord.BungeeScoreboard.setDisplaySlot(BungeeScoreboard.java:28)
06.10.2023 - 18:18:07 - 	at me.neznamy.tab.shared.features.YellowNumber.onServerChange(YellowNumber.java:112)
06.10.2023 - 18:18:07 - 	at me.neznamy.tab.shared.FeatureManager.onServerChange(FeatureManager.java:172)
06.10.2023 - 18:18:07 - 	at me.neznamy.tab.shared.platform.EventListener.lambda$serverChange$3(EventListener.java:70)
06.10.2023 - 18:18:07 - 	at me.neznamy.tab.shared.CpuManager.run(CpuManager.java:252)
06.10.2023 - 18:18:07 - 	at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:105)
06.10.2023 - 18:18:07 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
06.10.2023 - 18:18:07 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
06.10.2023 - 18:18:07 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
06.10.2023 - 18:18:07 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
06.10.2023 - 18:18:07 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
06.10.2023 - 18:18:07 - 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce (if known)

Step 1 : Upgrade your waterfall proxy to a version supperior to build #537. https://papermc.io/downloads/waterfall
Setp 2 : Add TAB BRIDGE on the backend server
Step 3 : See the magic

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
update

**Comment by NEZNAMY** [comment]
On which marketplace is 4.0.3 latest?

**Comment by Funasitien** [comment]
I think it was on github

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/7c74e7a1-9ef1-4d8a-aea3-a7f6474cd31a)
?

**Comment by Funasitien** [comment]
Ok you are perfect
Sorry for the inconveniense, and thanks you for both the incredibely quick support time and the fix.
Have a good day!

**Comment by NEZNAMY** [comment]
We didn't provide you with support, support is not provided in issue tracker.
