### ISSUE TITLE
Reload Error

### ISSUE THREAD

**Issue by Russhvith** [NEZNAMY/TAB#1099]
### Server version

Carbon 1.8.9

### TAB version

4.0.6

### Stack trace

[10:17:21 WARN]: Unexpected exception while parsing console command "tab reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'tab' in plugin TAB v4.0.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[aOQHdmxohifkFWFlJzJG107221885945400155.jar:git-Carbon-9f25f4c]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[aOQHdmxohifkFWFlJzJG107221885945400155.jar:git-Carbon-9f25f4c]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:805) ~[aOQHdmxohifkFWFlJzJG107221885945400155.jar:git-Carbon-9f25f4c]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:768) ~[aOQHdmxohifkFWFlJzJG107221885945400155.jar:git-Carbon-9f25f4c]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:467) ~[aOQHdmxohifkFWFlJzJG107221885945400155.jar:git-Carbon-9f25f4c]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:427) ~[aOQHdmxohifkFWFlJzJG107221885945400155.jar:git-Carbon-9f25f4c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:878) ~[aOQHdmxohifkFWFlJzJG107221885945400155.jar:git-Carbon-9f25f4c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:709) ~[aOQHdmxohifkFWFlJzJG107221885945400155.jar:git-Carbon-9f25f4c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:131) ~[aOQHdmxohifkFWFlJzJG107221885945400155.jar:git-Carbon-9f25f4c]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.AbstractMethodError: Receiver class me.neznamy.tab.platforms.bukkit.features.BukkitTabExpansion does not define or inherit an implementation of the resolved method 'abstract boolean unregister()' of interface me.neznamy.tab.shared.placeholders.expansion.TabExpansion.
        at me.neznamy.tab.shared.FeatureManager.unload(FeatureManager.java:72) ~[?:?]
        at me.neznamy.tab.shared.TAB.unload(TAB.java:200) ~[?:?]
        at me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:23) ~[?:?]
        at me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:55) ~[?:?]
        at me.neznamy.tab.platforms.bukkit.BukkitTabCommand.onCommand(BukkitTabCommand.java:34) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[aOQHdmxohifkFWFlJzJG107221885945400155.jar:git-Carbon-9f25f4c]
        ... 9 more

### Additional info

I am running a Carbon (Fork of Spigot/Paper) server. When i do /tab reload the server throws a error, however on startup the config file loads and even the custom tab is visible, but later as /tab reload is done it breaks, however the custom tab is STILL visible

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
what's your PlaceholderAPI version?

**Comment by Russhvith** [comment]
> what's your PlaceholderAPI version?

Oh thanks for the heads up, i had uploaded the wrong version which was outdated. I have updated ad it is working fine. Thanks!
