### ISSUE TITLE
tab plugin is not available for 1.7.10 Thermos & 1.7.10Mohist.   在1.7.10 Thermos & 1.7.10Mohist 都无法使用tab插件。

### ISSUE THREAD

**Issue by jiahe666666** [NEZNAMY/TAB#1114]
### Server version

1.7.10 Thermos & 1.7.10Mohist

### TAB version

4.0.7

### Describe the bug

tab cannot be used on any 1.7.10 Thermos & 1.7.10Mohist. Please fix it. Thank you very much

### Expected behavior

tab cannot be used on any 1.7.10 Thermos & 1.7.10Mohist. Please fix it. Thank you very much

### Steps to reproduce

tab cannot be used on any 1.7.10 Thermos & 1.7.10Mohist. Please fix it. Thank you very much

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
what doesn't work? does it not load? does it throw any error? if yes, send them or send your server logs

**Comment by jiahe666666** [comment]
> 什么不起作用？它不加载吗？它会抛出任何错误吗？如果是，请发送它们或发送您的服务器日志

![2023-10-20_14 47 18](https://github.com/NEZNAMY/TAB/assets/141595201/a397624e-4e16-4d47-b03b-4af65c135377)
可以加载，但是不会有任何改变
重载会有报错
`[14:50:31 INFO]: jiahe666666 issued server command: /tab reload
[14:50:31 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tab' in plugin TAB v4.0.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-46]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-46]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:741) ~[CraftServer.class:1.7.10-46]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1298) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1035) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1017) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:437) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:835) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.AbstractMethodError: Method me/neznamy/tab/platforms/bukkit/features/BukkitTabExpansion.unregister()Z is abstract
        at me.neznamy.tab.platforms.bukkit.features.BukkitTabExpansion.unregister(BukkitTabExpansion.java) ~[?:?]
        at me.neznamy.tab.shared.FeatureManager.unload(FeatureManager.java:72) ~[?:?]
        at me.neznamy.tab.shared.TAB.unload(TAB.java:200) ~[?:?]
        at me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:23) ~[?:?]
        at me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:55) ~[?:?]
        at me.neznamy.tab.platforms.bukkit.BukkitTabCommand.onCommand(BukkitTabCommand.java:34) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-46]
        ... 13 more`
[latest.log](https://github.com/NEZNAMY/TAB/files/13050847/latest.log)
![2023-10-20_14 50 43](https://github.com/NEZNAMY/TAB/assets/141595201/1bdfe61f-16e3-4157-b965-b02e25f5207c)

**Comment by NEZNAMY** [comment]
Update or delete PlaceholderAPI.

**Comment by jiahe666666** [comment]
> 更新或删除占位符 API。

[PlaceholderAPI] The placeholder: essentials_nickname could not be found on the expansion cloud.  Are you sure that is a valid placeholder?
Now keep brushing this error。

**Comment by NEZNAMY** [comment]
No idea why that happens, but this is not exactly a TAB issue. You can delete the lines using those placeholders from groups.yml to avoid it.

**Comment by couleurm** [comment]
@jiahe666666 hello, this message is unrelated to this issue, this was the only place where i could contact you

if you would like to discuss about 1.7.10 mods / configuration feel free to start discussing with me on `couleur@riseup.net`

not disturbing you any more have a good day

**Comment by jiahe666666** [comment]
Deleted placeholder still does not work, hope to fix in 4.0.8 version 。thank you

**Comment by jiahe666666** [comment]
He doesn't work even on any 1.7.10 core. Even if there are placeholders and no errors are reported.

**Comment by jiahe666666** [comment]
I use a translator to communicate with you, there may be ambiguity, but I mean no harm. If you can fix it, I'll pay you.

**Comment by NEZNAMY** [comment]
I have no idea what do you want fixed.

**Comment by jiahe666666** [comment]
I want to fix any core of tab plugin in 1.7.10, not just mohist or Thermos, which does not work properly, please take time out of your busy schedule to test it. Even if the placeholder of another version does not report an error, it still does not work.......

**Comment by NEZNAMY** [comment]
Error when using a 3 year old version of PlaceholderAPI will be fixed in the next version. I don't know what else am I supposed to fix.

**Comment by jiahe666666** [comment]
Dear Sir, try it yourself and you will see that tab plugins do not work, they do not have any effect. At least that's how it was when I tested it. Shall I retest it now? If you have qq, please add my friend 1427309053, I will use the whiteboard live to show you

**Comment by NEZNAMY** [comment]
I have no idea what `qq` is and see no reason to use it. Explain "does not work". Check console log if the plugin started correctly and everything.

**Comment by jiahe666666** [comment]
I have tested well, you look at the video here, change the error.1 file name to error.mp4 can see the video, it is not effective, and then there is a spigot server. You can run your own test to see if it doesn't work as I said.
https://www.123pan.com/s/Df7yVv-ABBo3.html


I went home from work, I wish you a happy life, happy every day

**Comment by NEZNAMY** [comment]
I can see your name in tablist having color = teams are working. I can also see yellow number feature working. I am guessing you have bossbar and scoreboard disabled, so you don't have those visible. What else are you expecting?
