### ISSUE TITLE
No longer be able to use relational placeholders on group config

### ISSUE THREAD

**Issue by Elikill58** [NEZNAMY/TAB#1117]
### Server version

Spigot 1.8.8 and paper 1.20.2

### TAB version

4.0.7

### Describe the bug

I'm using custom placeholders as `%rel_some_placeholder%` in `groups.yml` (config below).

When using `/tab reload`, I get this error :
```
 Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
 java.lang.IllegalArgumentException: "rel_" is reserved for relational placeholder identifiers
   at TAB v4.0.7.jar//me.neznamy.tab.shared.placeholders.ServerPlaceholderImpl.<init>(ServerPlaceholderImpl.java:41)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.registerServerPlaceholder(PlaceholderManagerImpl.java:248)
   at TAB v4.0.7.jar//me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.registerUnknownPlaceholder(BukkitPlatform.java:145)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.getPlaceholder(PlaceholderManagerImpl.java:275)
   at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
   at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573)
   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
   at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
   at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.recalculateUsedPlaceholders(PlaceholderManagerImpl.java:221)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.addUsedPlaceholder(PlaceholderManagerImpl.java:212)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.features.types.Refreshable.lambda$addUsedPlaceholders$0(Refreshable.java:40)
   at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.features.types.Refreshable.addUsedPlaceholders(Refreshable.java:40)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.Property.analyze(Property.java:121)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.Property.<init>(Property.java:85)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.platform.TabPlayer.setProperty(TabPlayer.java:124)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.platform.TabPlayer.loadPropertyFromConfig(TabPlayer.java:250)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.platform.TabPlayer.loadPropertyFromConfig(TabPlayer.java:228)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.features.nametags.NameTag.updateProperties(NameTag.java:272)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.features.nametags.NameTag.load(NameTag.java:61)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.FeatureManager.load(FeatureManager.java:52)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.TAB.load(TAB.java:171)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:24)
   at TAB v4.0.7.jar//me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:55)
   at TAB v4.0.7.jar//me.neznamy.tab.platforms.bukkit.BukkitTabCommand.onCommand(BukkitTabCommand.java:34)
   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
   at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989)
   at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
   at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
   at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
   at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
   at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2207)
   at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2167)
   at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
   at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   at net.minecraft.server.TickTask.run(TickTask.java:18)
   at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
   at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
   at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
   at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
   at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
   at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
   at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
   at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
   at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
   at java.base/java.lang.Thread.run(Thread.java:833)
```
It seems not working without reload too. It were working in 4.0.3.

### Expected behavior

See tab/tab without error.

### Steps to reproduce

1: Create placeholders like that:
```java
TabAPI.getInstance().getEventBus().register(PlayerLoadEvent.class, event -> {
	TabAPI.getInstance().getPlaceholderManager().registerRelationalPlaceholder("%rel_some_placeholder%", 100, (viewer, target) -> {
		return "a";
	});
});
```
2: Use config like this:
```yml
_DEFAULT_:
  tabprefix: '%rel_some_placeholder%'
  tagprefix: '%rel_some_placeholder%'
```
3: Login
4: Now you see there is nothing in TAB, and if you do /tab reload you get the error

*Reproduced on local, with only TAB and a minimal plugin which is not my full plugin which firstly produce the error.*

### Additional info

Sorry, this will be a little off-topic but np.
I just read your v4.0.7 update and I want to send you some strength as I understand what you mean. I'm in the same case for few projects, I no longer use them but continue to update them during years only for people that I don't know and make money with them without giving few of it. It's not very enjoying but we will find a way.
A friend said like "Each time a plugin is no longer supported, another one appear to replace it". For example, ProtocolLib, HolographicDisplay, Essentials etc. Maybe it's the way: A day, stop it or let it die, and let others people do their one (or give ownership to someone else. I personally take the ownership of at least 2 plugins).
To conclude, good luck, hope some fix will appear, hope Bungeecord will merge Waterfall and stop this no-maj behavior.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Elikill58** [comment]
Thanks you, I love you. I don't have money (yet) but that so fast and it's working fine <3
