### ISSUE TITLE
UUID is null

### ISSUE THREAD

**Issue by yurchik228336** [NEZNAMY/TAB#1131]
### Server version

Patina 1.16.5

### TAB version

Latest

### Describe the bug

[11:31:49 ERROR]: java.lang.NullPointerException: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "uuid" is null

[11:31:49 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "uuid" is null

[11:31:49 WARN]: at net.minecraft.server.v1_16_R3.PacketDataSerializer.a(PacketDataSerializer.java:231)

[11:31:49 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayOutChat.b(PacketPlayOutChat.java:57)

[11:31:49 WARN]: at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:46)

[11:31:49 WARN]: at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:15)

[11:31:49 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)

[11:31:49 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)

[11:31:49 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)

[11:31:49 WARN]: at io.github.repooper.packetevents.Vulcan_Ez.write(Vulcan_Ez.java:54)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)

[11:31:49 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)

[11:31:49 WARN]: at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:134)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)

[11:31:49 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)

[11:31:49 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)

[11:31:49 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)

[11:31:49 WARN]: at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)

[11:31:49 WARN]: at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)

[11:31:49 WARN]: at net.minecraft.server.v1_16_R3.NetworkManager.lambda$writePacket$9(NetworkManager.java:455)

[11:31:49 WARN]: at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)

[11:31:49 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)

[11:31:49 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)

[11:31:49 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)

[11:31:49 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)

[11:31:49 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

[11:31:49 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)

### Expected behavior

.

### Steps to reproduce

.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
This is a bug in protocollib or a plugin using it and was fixed years ago. Nothing to do with TAB.
