### ISSUE TITLE
Cannot get ID for packet class 

### ISSUE THREAD

**Issue by Astralymc** [NEZNAMY/TAB#1146]
### Server version

Purpur 1.18.2

### TAB version

3.0.9

### Stack trace

[20:23:46 ERROR]: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Team in phase CONFIGURATION with direction TO_CLIENT for version  [764]
[20:23:46 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(Unknown Source)
[20:23:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(Unknown Source)
[20:23:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(Unknown Source)
[20:23:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(Unknown Source)
[20:23:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(Unknown Source)
[20:23:46 ERROR]:       at io.netty.channel.ChannelDuplexHandler.write(Unknown Source)
[20:23:46 ERROR]:       at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:134)
[20:23:46 ERROR]:       at me.neznamy.tab.platforms.bungeecord.BungeePipelineInjector$DeserializableBungeeChannelDuplexHandler.write(BungeePipelineInjector.java:226)
[20:23:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(Unknown Source)
[20:23:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(Unknown Source)
[20:23:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(Unknown Source)
[20:23:46 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(Unknown Source)
[20:23:46 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(Unknown Source)
[20:23:46 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Unknown Source)
[20:23:46 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(Unknown Source)
[20:23:46 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(Unknown Source)
[20:23:46 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(Unknown Source)
[20:23:46 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(Unknown Source)
[20:23:46 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:840)
[20:23:46 ERROR]: Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Team in phase CONFIGURATION with direction TO_CLIENT for version  [764]
[20:23:46 ERROR]:       at com.google.common.base.Preconditions.checkArgument(Unknown Source)
[20:23:46 ERROR]:       at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Unknown Source)
[20:23:46 ERROR]:       at net.md_5.bungee.protocol.MinecraftEncoder.encode(Unknown Source)
[20:23:46 ERROR]:       at net.md_5.bungee.protocol.MinecraftEncoder.encode(Unknown Source)
[20:23:46 ERROR]:       ... 19 more

### Steps to reproduce (if known)

When some users connect it happens

### Additional info

I use bungee tab and xcord

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
What is your discord username? I will send you a jar to test.

**Comment by Astralymc** [comment]
My discord is salchii2k

**Comment by NEZNAMY** [comment]
User did not accept friend request within a week, assuming they have died. The commit linked above might help with the issue.
