### ISSUE TITLE
plugin reload error.

### ISSUE THREAD

**Issue by MrPippi** [NEZNAMY/TAB#1147]
### Server version

Purpur 1.20.2

### TAB version

4.0.9

### Stack trace

19.11.2023 - 13:30:22 - [TAB v4.0.8] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
19.11.2023 - 13:30:22 - java.lang.NoSuchMethodException: net.md_5.bungee.protocol.packet.ScoreboardObjective.<init>(java.lang.String,net.md_5.bungee.api.chat.BaseComponent,net.md_5.bungee.protocol.packet.ScoreboardObjective$HealthDisplay,byte)
19.11.2023 - 13:30:22 - 	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
19.11.2023 - 13:30:22 - 	at java.base/java.lang.Class.getConstructor(Class.java:2271)
19.11.2023 - 13:30:22 - 	at me.neznamy.tab.platforms.bungeecord.BungeeMultiVersion.newScoreboardObjective(BungeeMultiVersion.java:113)
19.11.2023 - 13:30:22 - 	at me.neznamy.tab.platforms.bungeecord.BungeeScoreboard.registerObjective0(BungeeScoreboard.java:33)
19.11.2023 - 13:30:22 - 	at me.neznamy.tab.shared.platform.Scoreboard.registerObjective(Scoreboard.java:54)
19.11.2023 - 13:30:22 - 	at me.neznamy.tab.shared.features.YellowNumber.load(YellowNumber.java:66)
19.11.2023 - 13:30:22 - 	at me.neznamy.tab.shared.FeatureManager.load(FeatureManager.java:52)
19.11.2023 - 13:30:22 - 	at me.neznamy.tab.shared.TAB.load(TAB.java:171)
19.11.2023 - 13:30:22 - 	at me.neznamy.tab.shared.command.DisabledCommand.execute(DisabledCommand.java:31)
19.11.2023 - 13:30:22 - 	at me.neznamy.tab.platforms.bungeecord.BungeeTabCommand.execute(BungeeTabCommand.java:28)
19.11.2023 - 13:30:22 - 	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:213)
19.11.2023 - 13:30:22 - 	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:164)
19.11.2023 - 13:30:22 - 	at net.md_5.bungee.connection.UpstreamBridge.handleChat(UpstreamBridge.java:228)
19.11.2023 - 13:30:22 - 	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:197)
19.11.2023 - 13:30:22 - 	at net.md_5.bungee.protocol.packet.ClientCommand.handle(ClientCommand.java:109)
19.11.2023 - 13:30:22 - 	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
19.11.2023 - 13:30:22 - 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
19.11.2023 - 13:30:22 - 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
19.11.2023 - 13:30:22 - 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
19.11.2023 - 13:30:22 - 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
19.11.2023 - 13:30:22 - 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
19.11.2023 - 13:30:22 - 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
19.11.2023 - 13:30:22 - 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
19.11.2023 - 13:30:22 - 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
19.11.2023 - 13:30:22 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
19.11.2023 - 13:30:22 - 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
19.11.2023 - 13:30:22 - 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
19.11.2023 - 13:30:22 - 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
19.11.2023 - 13:30:22 - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
19.11.2023 - 13:30:22 - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
19.11.2023 - 13:30:22 - 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
19.11.2023 - 13:30:22 - 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
19.11.2023 - 13:30:22 - 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
19.11.2023 - 13:30:22 - 	at java.base/java.lang.Thread.run(Thread.java:833)

### Steps to reproduce (if known)

The server was running fine just after startup until I entered /btab reload to reload the plugin files, and that's when this error occurred.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Why does purpur show a bungeecord error?
How is this not a duplicate of #1135 ?

**Comment by MrPippi** [comment]
oh is bungeecord...
