### ISSUE TITLE
Server will not start when TAB is installed

### ISSUE THREAD

**Issue by 1Ltech** [NEZNAMY/TAB#1148]
### Server version

Fabric 1.19.2

### TAB version

4.0.3

### Stack trace

[07:11:12] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'tab'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.21-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoSuchMethodError: 'int net.minecraft.class_6489.method_48020()'
	at me.neznamy.tab.platforms.fabric.FabricTAB.onInitializeServer(FabricTAB.java:34) ~[TAB%20v4.0.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more

### Steps to reproduce (if known)

Step 1: Start server

### Additional info

I tried the latest version of TAB but that did not work because that is for 1.20.2 only and would give me a different error message. I tried with 4.0.3 and it seemed to work until I got the error message, yes I did read the comp wiki page and I was hoping it would work with it anyway because it was an older version of the mod for 1.19.2.

### Checklist

- [ ] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Fabric support was added in 4.0.0, which came out with MC 1.20, which is also the first version supported by official jars. Therefore it never supported 1.19.2 in the first place.
The error message you sent means the mod was compiled with a different MC version than what you are using. Since fabric has its own way of "deobfuscating" (if we can even call it that) the server jar and it is therefore not possible to support more than a single MC version at a time with the same jar.
I still learn and only recently I found out how to explicitly specify MC version which the mod will start on and will throw an explicit message saying server version is not supported.
If you want a version for 1.19.2, you'll need to get someone to backport it for you.
Also `~[TAB%20v4.0.1.jar:?]` doesn't sound like 4.0.3 to me.

**Comment by 1Ltech** [comment]
The file on my server says 4.0.3 to me so I must have made a mistake in the addition but as I am aware 4.0.1 is for fabric but not for 1.19.2
Do you know anyone who could backport it?

**Comment by NEZNAMY** [comment]
No, I don't know about anyone interested to work for your server. Try spigot forums or some other place for hiring.

**Comment by 1Ltech** [comment]
Wow! That was fast, another option I have is to update all the mods to 1.20.1 but I doubt all the mods are there yet plus we just updated our modpack so my server members would not be happy. I could just learn how to do it myself but I have little faith in myself.

**Comment by NEZNAMY** [comment]
I'm afraid I cannot help with that.

**Comment by 1Ltech** [comment]
It's fine :), I just wanted to make sure I wasn't just messing something up. Thanks for the help I hope to use your mod in the future.
