### ISSUE TITLE
Errors while server starts

### ISSUE THREAD

**Issue by BillZhucn** [NEZNAMY/TAB#115]
**Server version**
Paper-118 (1.15.2)

**Plugin version** ("latest" is not a version)
 v2.6.5

**Describe the bug**
errors while server starts

**How to reproduce**

**Expected behavior**

**Actual behavior**

**Additional info** (errors, screenshots, ...)
[10:37:16 INFO]: [TAB] Enabling TAB v2.6.5
[10:37:16 INFO]: [TAB] Server version: 1.15.2 (v1_15_R1)
[10:37:16 INFO]: [TAB] Failed to enable
[10:37:16 INFO]: java.lang.NullPointerException: null
[10:37:16 INFO]:        at me.neznamy.tab.shared.Configs.loadBossbar(Configs.java:235)
[10:37:16 INFO]:        at me.neznamy.tab.shared.Configs.loadFiles(Configs.java:139)
[10:37:16 INFO]:        at me.neznamy.tab.platforms.bukkit.Main.load(Main.java:112)
[10:37:16 INFO]:        at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:56)
[10:37:16 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:37:16 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[10:37:16 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
[10:37:16 INFO]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[10:37:16 INFO]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[10:37:16 INFO]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482)
[10:37:16 INFO]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[10:37:16 INFO]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[10:37:16 INFO]:        at java.lang.Thread.run(Unknown Source)

**Comment by rodrigozamorad** [comment]
Try updating tab

**Comment by BillZhucn** [comment]
Use the dev build?

**Comment by rodrigozamorad** [comment]
Yes, maybe your issue got fixed in a dev build

**Comment by BillZhucn** [comment]
I will try it. If the error still exists I will come back and report it to you.

**Comment by BillZhucn** [comment]
The problem is still there.

**Comment by rodrigozamorad** [comment]
Did you modify any file?

**Comment by BillZhucn** [comment]
Yes, I modified the config.yml

**Comment by rodrigozamorad** [comment]
Is there an error file on TAB folder?

**Comment by BillZhucn** [comment]
No error file on plugins/TAB

**Comment by rodrigozamorad** [comment]
Can you send your config?

**Comment by BillZhucn** [comment]
Ok

[config.zip](https://github.com/NEZNAMY/TAB/files/4253293/config.zip)

**Comment by rodrigozamorad** [comment]
Did you modify the bossbar file?

**Comment by BillZhucn** [comment]
I just change the text message in bossbar file.

**Comment by BillZhucn** [comment]
All my files in TAB folder
[TAB.zip](https://github.com/NEZNAMY/TAB/files/4253327/TAB.zip)

**Comment by rodrigozamorad** [comment]
Does the console error message is the same with the dev build?

**Comment by BillZhucn** [comment]
[11:12:57 INFO]: [TAB] Enabling TAB v2.7.0-pre14
[11:12:57 INFO]: [TAB] Server version: 1.15.2 (v1_15_R1)
[11:12:57 INFO]: [TAB] Converted old config.yml option nametag-refresh-interval-ticks (20) to new nametag-refresh-interval-milliseconds (1000)
[11:12:57 INFO]: [TAB] Converted old config.yml option tablist-refresh-interval-ticks (20) to new tablist-refresh-interval-milliseconds (1000)
[11:12:57 INFO]: [TAB] Converted old config.yml option header-footer-refresh-interval-ticks (1) to new header-footer-refresh-interval-milliseconds (50)
[11:12:57 INFO]: [TAB] Converted old config.yml option belowname.refresh-interval-ticks (5) to new belowname.refresh-interval-milliseconds (250)
[11:12:57 INFO]: [TAB] Removed old config.yml option placeholders.deluxetag-yes
[11:12:57 INFO]: [TAB] Removed old config.yml option placeholders.deluxetag-no
[11:12:57 INFO]: [TAB] Removed old config.yml option placeholders.faction-yes
[11:12:57 INFO]: [TAB] Removed old config.yml option placeholders.faction-no
[11:12:57 INFO]: [TAB] Failed to enable
[11:12:57 INFO]: java.lang.NullPointerException: null
[11:12:57 INFO]:        at me.neznamy.tab.shared.Configs.loadBossbar(Configs.java:274)
[11:12:57 INFO]:        at me.neznamy.tab.shared.Configs.loadFiles(Configs.java:107)
[11:12:57 INFO]:        at me.neznamy.tab.platforms.bukkit.Main.load(Main.java:120)
[11:12:57 INFO]:        at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:57)
[11:12:57 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:12:57 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[11:12:57 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
[11:12:57 INFO]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[11:12:57 INFO]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[11:12:57 INFO]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482)
[11:12:57 INFO]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[11:12:57 INFO]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[11:12:57 INFO]:        at java.lang.Thread.run(Unknown Source)

seems the same.

**Comment by NEZNAMY** [comment]
According to error message you deleted default-bars entirely instead of making it empty ( [] ).

**Comment by BillZhucn** [comment]
I found the mistake I met. I use the translated and outdated configuration file. I transferred my modified text and it works now. Thank you very much!
