### ISSUE TITLE
Chunk placeholder error

### ISSUE THREAD

**Issue by Has-X** [NEZNAMY/TAB#1152]
### Server version

Paper 1.12.1

### TAB version

4.0.9

### Stack trace

[19:01:46 ERROR]: Thread TAB Placeholder Refreshing Thread failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(:15) ~[leaf-1.20.jar:git-Leaf-"034c223"]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2556) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.getNMSEntities(:1053) ~[leaf-1.20.jar:git-Leaf-"034c223"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftRegionAccessor.getEntities(:445) ~[leaf-1.20.jar:git-Leaf-"034c223"]
        at com.extendedclip.papi.expansion.server.ServerExpansion.lambda$getTotalEntities$2(ServerExpansion.java:141) ~[?:?]
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:515) ~[?:?]
        at java.util.stream.IntPipeline.sum(IntPipeline.java:473) ~[?:?]
        at com.extendedclip.papi.expansion.server.ServerExpansion.getTotalEntities(ServerExpansion.java:142) ~[?:?]
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4924) ~[guava-32.0.1-jre.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3570) ~[guava-32.0.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2312) ~[guava-32.0.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189) ~[guava-32.0.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079) ~[guava-32.0.1-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4011) ~[guava-32.0.1-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4919) ~[guava-32.0.1-jre.jar:?]
        at com.extendedclip.papi.expansion.server.ServerExpansion.getCached(ServerExpansion.java:115) ~[?:?]
        at com.extendedclip.papi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:201) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.5.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.5.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.5.jar:?]
        at me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.lambda$registerUnknownPlaceholder$6(BukkitPlatform.java:158) ~[TAB v4.0.9.jar:?]
        at me.neznamy.tab.shared.placeholders.ServerPlaceholderImpl.request(ServerPlaceholderImpl.java:142) ~[TAB v4.0.9.jar:?]
        at me.neznamy.tab.shared.placeholders.ServerPlaceholderImpl.update0(ServerPlaceholderImpl.java:53) ~[TAB v4.0.9.jar:?]
        at me.neznamy.tab.shared.features.PlaceholderManagerImpl.updateServerPlaceholder(PlaceholderManagerImpl.java:140) ~[TAB v4.0.9.jar:?]
        at me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:68) ~[TAB v4.0.9.jar:?]
        at me.neznamy.tab.shared.cpu.CpuManager.lambda$enable$1(CpuManager.java:77) ~[TAB v4.0.9.jar:?]
        at me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:173) ~[TAB v4.0.9.jar:?]
        at me.neznamy.tab.shared.cpu.CpuManager.lambda$enable$2(CpuManager.java:75) ~[TAB v4.0.9.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Steps to reproduce (if known)

Step 1: Use any of these placeholders: %server_total_chunks%, %server_total_living_entities%, %server_total_entities%
Step 2: Electric boogaloo

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Placeholders#sync-refreshing ?

**Comment by Has-X** [comment]
> https://github.com/NEZNAMY/TAB/wiki/Placeholders#sync-refreshing ?

I'm trying it.

**Comment by Has-X** [comment]
Fixed, sorry
