### ISSUE TITLE
[Bug/Information] Attempted duplicate class definition for name "net/luckperms/api/LuckPermsProvider"

### ISSUE THREAD

**Issue by Baktus79** [NEZNAMY/TAB#116]
**Server version**
BungeeCord 1482

**Plugin version** ("latest" is not a version)
2.7.0-pre14

**Describe the bug**
TAB wont hook into Luckperms. See the console message further down in the post. I know this is a pre version so I should expect this kind of stuff, but take this into consideration if not already done so. I have noticed that this message has come from more than one plugin lately, after I updated the Luckperms plugin.

LuckPerms version: 5.0.81 

This is not an issue on the Bukkit server.

**How to reproduce**
Place the plugin in the plugin folder and start BungeeCord.

**Expected behavior**
I want to be able to use the `group-sorting-priority-list:` 
```yaml
group-sorting-priority-list:
- eier
- admin
- mod
- hjelper
- trymod
- default
```

**Additional info** (errors, screenshots, ...)

**On enable**
```
25.02.2020 - 23:05:40 - java.lang.LinkageError: loader (instance of  net/md_5/bungee/api/plugin/PluginClassloader): attempted  duplicate class definition for name: "net/luckperms/api/LuckPermsProvider"
25.02.2020 - 23:05:40 -        at java.lang.ClassLoader.defineClass1(Native Method)
25.02.2020 - 23:05:40 -        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
25.02.2020 - 23:05:40 -        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
25.02.2020 - 23:05:40 -        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
25.02.2020 - 23:05:40 -        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
25.02.2020 - 23:05:40 -        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
25.02.2020 - 23:05:40 -        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
25.02.2020 - 23:05:40 -        at java.security.AccessController.doPrivileged(Native Method)
25.02.2020 - 23:05:40 -        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
25.02.2020 - 23:05:40 -        at net.md_5.bungee.api.plugin.PluginClassloader.findClass0(PluginClassloader.java:44)
25.02.2020 - 23:05:40 -        at net.md_5.bungee.api.plugin.PluginClassloader.findClass0(PluginClassloader.java:56)
25.02.2020 - 23:05:40 -        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:37)
25.02.2020 - 23:05:40 -        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
25.02.2020 - 23:05:40 -        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
25.02.2020 - 23:05:40 -        at me.neznamy.tab.shared.PluginHooks.LuckPerms_getPrimaryGroup(PluginHooks.java:164)
25.02.2020 - 23:05:40 -        at me.neznamy.tab.platforms.bungee.TabPlayer.getGroupFromPermPlugin(TabPlayer.java:30)
25.02.2020 - 23:05:40 -        at me.neznamy.tab.shared.ITabPlayer.updateGroupIfNeeded(ITabPlayer.java:238)
25.02.2020 - 23:05:40 -        at me.neznamy.tab.shared.ITabPlayer.init(ITabPlayer.java:57)
25.02.2020 - 23:05:40 -        at me.neznamy.tab.platforms.bungee.TabPlayer.<init>(TabPlayer.java:27)
25.02.2020 - 23:05:40 -        at me.neznamy.tab.platforms.bungee.Main.a(Main.java:129)
25.02.2020 - 23:05:40 -        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
25.02.2020 - 23:05:40 -        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
25.02.2020 - 23:05:40 -        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
25.02.2020 - 23:05:40 -        at java.lang.reflect.Method.invoke(Method.java:498)
25.02.2020 - 23:05:40 -        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
25.02.2020 - 23:05:40 -        at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
25.02.2020 - 23:05:40 -        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:399)
25.02.2020 - 23:05:40 -        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:292)
25.02.2020 - 23:05:40 -        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:105)
25.02.2020 - 23:05:40 -        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
25.02.2020 - 23:05:40 -        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
25.02.2020 - 23:05:40 -        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
25.02.2020 - 23:05:40 -        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
25.02.2020 - 23:05:40 -        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
25.02.2020 - 23:05:40 -        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
25.02.2020 - 23:05:40 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
25.02.2020 - 23:05:40 -        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
25.02.2020 - 23:05:40 -        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
25.02.2020 - 23:05:40 -        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
25.02.2020 - 23:05:40 -        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
25.02.2020 - 23:05:40 -        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
25.02.2020 - 23:05:40 -        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
25.02.2020 - 23:05:40 -        at java.lang.Thread.run(Thread.java:748)
```

**On player connect**
```
25.02.2020 - 23:05:55 - [TAB v2.6.5] Failed to get permission group of Baktus_79 using LuckPerms
25.02.2020 - 23:05:55 - java.lang.LinkageError: net/luckperms/api/LuckPermsProvider
25.02.2020 - 23:05:55 -        at me.neznamy.tab.shared.PluginHooks.LuckPerms_getPrimaryGroup(PluginHooks.java:164)
25.02.2020 - 23:05:55 -        at me.neznamy.tab.platforms.bungee.TabPlayer.getGroupFromPermPlugin(TabPlayer.java:30)
25.02.2020 - 23:05:55 -        at me.neznamy.tab.shared.ITabPlayer.updateGroupIfNeeded(ITabPlayer.java:238)
25.02.2020 - 23:05:55 -        at me.neznamy.tab.shared.ITabPlayer.init(ITabPlayer.java:57)
25.02.2020 - 23:05:55 -        at me.neznamy.tab.platforms.bungee.TabPlayer.<init>(TabPlayer.java:27)
25.02.2020 - 23:05:55 -        at me.neznamy.tab.platforms.bungee.Main.a(Main.java:129)
25.02.2020 - 23:05:55 -        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
25.02.2020 - 23:05:55 -        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
25.02.2020 - 23:05:55 -        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
25.02.2020 - 23:05:55 -        at java.lang.reflect.Method.invoke(Method.java:498)
25.02.2020 - 23:05:55 -        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
25.02.2020 - 23:05:55 -        at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
25.02.2020 - 23:05:55 -        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:399)
25.02.2020 - 23:05:55 -        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:292)
25.02.2020 - 23:05:55 -        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:105)
25.02.2020 - 23:05:55 -        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
25.02.2020 - 23:05:55 -        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
25.02.2020 - 23:05:55 -        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
25.02.2020 - 23:05:55 -        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
25.02.2020 - 23:05:55 -        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
25.02.2020 - 23:05:55 -        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
25.02.2020 - 23:05:55 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
25.02.2020 - 23:05:55 -        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
25.02.2020 - 23:05:55 -        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
25.02.2020 - 23:05:55 -        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
25.02.2020 - 23:05:55 -        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
25.02.2020 - 23:05:55 -        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
25.02.2020 - 23:05:55 -        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
25.02.2020 - 23:05:55 -        at java.lang.Thread.run(Thread.java:748)
```

**My BungeeCord plugins**
![image](https://user-images.githubusercontent.com/19745447/75337818-00307f00-588e-11ea-9b2d-6d292cd8cb7b.png)

**Comment by Baktus79** [comment]
Didnt know I had to delete the error txt file. Seems to be working after removing it. I did update LuckPerms. That might have been the solution.

**Comment by NEZNAMY** [comment]
Deleting a file with errors won't remove cause of the errors.
