### ISSUE TITLE
CANNOT GET ID

### ISSUE THREAD

**Issue by Astralymc** [NEZNAMY/TAB#1167]
### Server version

xcord 

### TAB version

4.1.2

### Stack trace

[05:28:03 INFO]: [/191.95.29.201:9223|KarolDayanaYTzzz] <-> DownstreamBridge <-> [Prespawn] has disconnected
[05:28:03 ERROR]: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.StartConfiguration in phase CONFIGURATION with direction TO_CLIENT for version  [764]
[05:28:03 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.ChannelDuplexHandler.write(Unknown Source)
[05:28:03 ERROR]:       at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:134)
[05:28:03 ERROR]:       at me.neznamy.tab.platforms.bungeecord.BungeePipelineInjector$DeserializableBungeeChannelDuplexHandler.write(BungeePipelineInjector.java:217)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(Unknown Source)
[05:28:03 ERROR]:       at net.md_5.bungee.netty.ChannelWrapper.write(Unknown Source)
[05:28:03 ERROR]:       at net.md_5.bungee.UserConnection$1.sendPacket(Unknown Source)
[05:28:03 ERROR]:       at net.md_5.bungee.ServerConnector.cutThrough(Unknown Source)
[05:28:03 ERROR]:       at net.md_5.bungee.ServerConnector.handle(Unknown Source)
[05:28:03 ERROR]:       at net.md_5.bungee.protocol.packet.LoginSuccess.handle(Unknown Source)
[05:28:03 ERROR]:       at net.md_5.bungee.netty.HandlerBoss.channelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
[05:28:03 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.channelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(Unknown Source)
[05:28:03 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(Unknown Source)
[05:28:03 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(Unknown Source)
[05:28:03 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(Unknown Source)
[05:28:03 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(Unknown Source)
[05:28:03 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:840)
[05:28:03 ERROR]: Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.StartConfiguration in phase CONFIGURATION with direction TO_CLIENT for version  [764]
[05:28:03 ERROR]:       at com.google.common.base.Preconditions.checkArgument(Unknown Source)
[05:28:03 ERROR]:       at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Unknown Source)
[05:28:03 ERROR]:       at net.md_5.bungee.protocol.MinecraftEncoder.encode(Unknown Source)
[05:28:03 ERROR]:       at net.md_5.bungee.protocol.MinecraftEncoder.encode(Unknown Source)
[05:28:03 ERROR]:       ... 49 more

### Steps to reproduce (if known)

They simply enter the server and it kicks them showing that error

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Delete TAB and try again.

**Comment by Astralymc** [comment]
Do I delete the bungee tab and configure it again?

**Comment by NEZNAMY** [comment]
Any news @Astralymc ?

**Comment by NEZNAMY** [comment]
No response for 2 weeks, assuming user has died. The error is not caused by TAB.
