### ISSUE TITLE
Flamecord X B-Tab And TAB

### ISSUE THREAD

**Issue by Buttercuq** [NEZNAMY/TAB#1190]
### Server version

Purpur 1.17.1

### TAB version

4.0.9

### Stack trace

30.12.2023 - 09:13:26 - [TAB v4.0.9] An error was thrown when executing task
30.12.2023 - 09:13:26 - java.lang.NoSuchMethodException: net.md_5.bungee.protocol.packet.ScoreboardObjective.<init>(java.lang.String,net.md_5.bungee.api.chat.BaseComponent,net.md_5.bungee.protocol.packet.ScoreboardObjective$HealthDisplay,byte)
30.12.2023 - 09:13:26 - 	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
30.12.2023 - 09:13:26 - 	at java.base/java.lang.Class.getConstructor(Class.java:2271)
30.12.2023 - 09:13:26 - 	at me.neznamy.tab.platforms.bungeecord.BungeeMultiVersion.newScoreboardObjective(BungeeMultiVersion.java:113)
30.12.2023 - 09:13:26 - 	at me.neznamy.tab.platforms.bungeecord.BungeeScoreboard.registerObjective0(BungeeScoreboard.java:32)
30.12.2023 - 09:13:26 - 	at me.neznamy.tab.shared.platform.Scoreboard.registerObjective(Scoreboard.java:54)
30.12.2023 - 09:13:26 - 	at me.neznamy.tab.shared.features.YellowNumber.onJoin(YellowNumber.java:93)
30.12.2023 - 09:13:26 - 	at me.neznamy.tab.shared.FeatureManager.onJoin(FeatureManager.java:135)
30.12.2023 - 09:13:26 - 	at me.neznamy.tab.platforms.bungeecord.BungeeEventListener.lambda$onSwitch$0(BungeeEventListener.java:42)
30.12.2023 - 09:13:26 - 	at me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:173)
30.12.2023 - 09:13:26 - 	at me.neznamy.tab.shared.cpu.CpuManager.lambda$submit$3(CpuManager.java:98)
30.12.2023 - 09:13:26 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
30.12.2023 - 09:13:26 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
30.12.2023 - 09:13:26 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
30.12.2023 - 09:13:26 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
30.12.2023 - 09:13:26 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
30.12.2023 - 09:13:26 - 	at java.base/java.lang.Thread.run(Thread.java:842)
30.12.2023 - 09:13:27 - [TAB v4.0.9] An error was thrown when executing task
30.12.2023 - 09:13:27 - java.lang.NoSuchMethodException: net.md_5.bungee.protocol.packet.Team.<init>(java.lang.String,byte,net.md_5.bungee.api.chat.BaseComponent,net.md_5.bungee.api.chat.BaseComponent,net.md_5.bungee.api.chat.BaseComponent,java.lang.String,java.lang.String,int,byte,[Ljava.lang.String;)
30.12.2023 - 09:13:27 - 	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
30.12.2023 - 09:13:27 - 	at java.base/java.lang.Class.getConstructor(Class.java:2271)
30.12.2023 - 09:13:27 - 	at me.neznamy.tab.platforms.bungeecord.BungeeMultiVersion.newTeam(BungeeMultiVersion.java:126)
30.12.2023 - 09:13:27 - 	at me.neznamy.tab.platforms.bungeecord.BungeeScoreboard.registerTeam0(BungeeScoreboard.java:71)
30.12.2023 - 09:13:27 - 	at me.neznamy.tab.shared.platform.Scoreboard.registerTeam(Scoreboard.java:82)
30.12.2023 - 09:13:27 - 	at me.neznamy.tab.shared.features.nametags.NameTag.registerTeam(NameTag.java:265)
30.12.2023 - 09:13:27 - 	at me.neznamy.tab.shared.features.nametags.NameTag.registerTeam(NameTag.java:256)
30.12.2023 - 09:13:27 - 	at me.neznamy.tab.shared.features.sorting.Sorting.refresh(Sorting.java:82)
30.12.2023 - 09:13:27 - 	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:82)
30.12.2023 - 09:13:27 - 	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.lambda$refresh$0(PlaceholderManagerImpl.java:73)
30.12.2023 - 09:13:27 - 	at me.neznamy.tab.shared.cpu.CpuManager.lambda$runMeasuredTask$5(CpuManager.java:147)
30.12.2023 - 09:13:27 - 	at me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:173)
30.12.2023 - 09:13:27 - 	at me.neznamy.tab.shared.cpu.CpuManager.lambda$submit$3(CpuManager.java:98)
30.12.2023 - 09:13:27 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
30.12.2023 - 09:13:27 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
30.12.2023 - 09:13:27 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
30.12.2023 - 09:13:27 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
30.12.2023 - 09:13:27 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
30.12.2023 - 09:13:27 - 	at java.base/java.lang.Thread.run(Thread.java:842)

### Additional info

1. I Tested All Flamecord Versions, Latest Version and 1-2 Months Old
2. Since Flamecord does not support the new TAB and B-TAB plugin, I tried all versions from "November" and "October" with B-TAB
3. I tried 4.0.9 and 4.0.8 and the higher versions do not support flamecord for now
4. but there is a problem and there are a few different log errors, but basically there is a problem with the "bungee"
5. finally I tried these b-tab versions for 4.0.9 and 4.0.8 : 3.1.8 and 3.1.7

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/2c1320a5-71a6-4c5f-b6dd-6a1fcd5d6c2f)

![image](https://github.com/NEZNAMY/TAB/assets/6338394/5e28e6ac-89eb-4f98-a95d-01f61e687430)
On which marketplace is 4.0.9 latest?

**Comment by Buttercuq** [comment]
> ![image](https://private-user-images.githubusercontent.com/6338394/293455356-2c1320a5-71a6-4c5f-b6dd-6a1fcd5d6c2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzI5NTUsIm5iZiI6MTcwMzkzMjY1NSwicGF0aCI6Ii82MzM4Mzk0LzI5MzQ1NTM1Ni0yYzEzMjBhNS03MWE2LTRjNWYtYjZkZC02YTFmY2Q1ZDZjMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMTAzNzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDA1OWI0YzMyYWI1ZmI4ODllYWJjY2NjNWJiOTE5ZTc2MTQxYzMzMjFjNWVmNDg5NWIxZTg1NjIzOTIyZThhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Q1eKgTupU8SdzVAk6DA6c-77NW8dDMm7Fm_knX_wm0Y)
> 
> ![image](https://private-user-images.githubusercontent.com/6338394/293455364-5e28e6ac-89eb-4f98-a95d-01f61e687430.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzI5NTUsIm5iZiI6MTcwMzkzMjY1NSwicGF0aCI6Ii82MzM4Mzk0LzI5MzQ1NTM2NC01ZTI4ZTZhYy04OWViLTRmOTgtYTk1ZC0wMWY2MWU2ODc0MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMTAzNzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTA1N2E0NmJiNGNlN2IxZTliNWYzMDk1ZTViM2MzYTgyM2VmZWQyYjQ4MWY4MDkzMjlhNTI2ZTIxZTNjNmY1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PX32E9xvarmDSeS4VqnVMl6mEudAyxhyZewM9f2REsE) On which marketplace is 4.0.9 latest? Why does purpur throw a bungeecord error?

server purpur but proxy version flamecord 1.9.2

**Comment by Buttercuq** [comment]
I read the options but I couldn't send it so I clicked on all of them

**Comment by NEZNAMY** [comment]
How about the other question?

**Comment by Buttercuq** [comment]
the latest version for flamecord is 4.0.9 because they haven't updated the bungee api for 4.1.2 yet

> How about the other question?

**Comment by Buttercuq** [comment]
the highest version for me at the moment is 4.0.9

**Comment by Buttercuq** [comment]
but lower versions have the same problem

**Comment by Buttercuq** [comment]
In short, even if flamecord brings an update for your 4.1.2 version, I think you will still have the same error.

**Comment by NEZNAMY** [comment]
Flamecord had an update a week ago saying updated to latest BungeeCord.

**Comment by Buttercuq** [comment]
> Flamecord had an update a week ago saying updated to latest BungeeCord.

I have this problem when I test Flamecord in 4.1.2 with the latest version:

[10:34:18 WARN] [TAB]: The plugin requires BungeeCord build #1774 (released on N
ovember 25th, 2023) and up (or an equivalent fork) to work.
[10:34:18 INFO]: Enabled plugin TAB version 4.1.2 by NEZNAMY

**Comment by Buttercuq** [comment]
now the owner of flamecordu wrote me this message:

maybe it requires an update or requires entity rewrite to work which is not included in flamecord because it reduces performances a lot
Maybe give up using tab or ask the dev to not use entity rewrite features

**Comment by NEZNAMY** [comment]
Type /bungee and show output.

**Comment by Buttercuq** [comment]
i delete website toke ip sorry :
[10:49:15 INFO]: FlameCord is using Java compression
[10:49:15 INFO]: Enabled FlameCord version 1.9.2
[10:49:15 INFO]: Loaded plugin ajQueue version 2.6.0 by ajgeiss0702
[10:49:15 INFO]: Loaded plugin LuckPerms version 5.4.113 by Luck
[10:49:15 INFO]: Loaded plugin AdvancedNMotd version 10.0.1 by NamerPRO
[10:49:15 INFO]: Loaded plugin Lobbysystem version 2.4-SNAPSHOT by ObedMz
[10:49:15 INFO]: Loaded plugin SkinsRestorer version 14.2.12 by knat, AlexProgra
mmerDE, Th3Tr0LLeR, McLive, DoNotSpamPls
[10:49:15 INFO]: Loaded plugin TAB version 4.1.2 by NEZNAMY
[10:49:15 INFO]: Loaded plugin CommandForward version 0.4.0 by games647, https:/
/github.com/games647/CommandForward/graphs/contributors
[10:49:15 INFO]: Loaded plugin SlashServer version 3 by Bloodsplat
[10:49:15 INFO]: Loaded plugin LeaderOS version 1.0.3 by leaderos, geik
[10:49:15 INFO]: Loaded plugin BungeeCore version 1.1-SNAPSHOT by null
[10:49:15 INFO] [dev.simplix.protocolize.bungee.providers.BungeeCordProtocolRegi
strationProvider]: [Protocolize] Using BungeeCordPacketRegistrationStrategy
[10:49:15 INFO]: Loaded plugin Protocolize version 2.3.2:910 by Exceptionflug
[10:49:15 WARN]: Forced host server pvp is not defined
[10:49:15 INFO]: [FlameCord|Reconnect] Loading whitelisted items from file.
[10:49:15 INFO]: [FlameCord|Lockdown] Loading whitelisted items from file.
[10:49:15 INFO]: [FlameCord] Updating proxy database from 11 websites... (It can
 take a while!)
[10:49:15 WARN]: [FlameCord] IPSet feature requires Linux and root access to wor
k.
[10:49:15 INFO]: [FlameCord] Proxies are still loading (0.00%)!
[10:49:15 WARN] [ajQueue]: Could not find server named 'lobby-1' in servergroup
'lobbys'!
[10:49:15 WARN] [ajQueue]: Could not find server named 'lobby-2' in servergroup
'lobbys'!
[10:49:15 WARN] [ajQueue]: Could not find server named 'lobby-3' in servergroup
'lobbys'!
[10:49:15 WARN] [ajQueue]: Server group 'lobbys' has no servers! Ignoring it.
[10:49:15 INFO]: Enabled plugin ajQueue version 2.6.0 by ajgeiss0702
[10:49:16 INFO]:         __
[10:49:16 INFO]:   |    |__)   LuckPerms v5.4.113
[10:49:16 INFO]:   |___ |      Running on BungeeCord - FlameCord
[10:49:16 INFO]:
[10:49:16 INFO] [LuckPerms]: Loading configuration...
[10:49:16 INFO] [LuckPerms]: Loading storage provider... [MYSQL]
[10:49:16 INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hika
ri - Starting...
[10:49:16 INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hika
ri - Start completed.
[10:49:16 INFO] [LuckPerms]: Loading messaging service... [SQL]
[10:49:16 INFO] [LuckPerms]: Loading internal permission managers...
[10:49:16 INFO] [LuckPerms]: Performing initial data load...
[10:49:16 INFO] [LuckPerms]: Successfully enabled. (took 855ms)
[10:49:16 INFO]: Enabled plugin LuckPerms version 5.4.113 by Luck
[10:49:16 INFO]:
[10:49:16 INFO]: ---------------- AdvancedNMotd --------------
[10:49:16 INFO]:            AdvancedNMotd is enabled!
[10:49:16 INFO]: ---------------------------------------------
[10:49:16 INFO]:
[10:49:16 INFO]: Enabled plugin AdvancedNMotd version 10.0.1 by NamerPRO
[10:49:16 INFO]: [Lobby System] loaded correctly.
[10:49:16 INFO]: [Lobby System] 1 lobbys has been added.
[10:49:16 INFO]: Enabled plugin Lobbysystem version 2.4-SNAPSHOT by ObedMz
[10:49:17 INFO]: [SkinsRestorer] ----------------------------------------------
[10:49:17 INFO]: [SkinsRestorer]     +==================+
[10:49:17 INFO]: [SkinsRestorer]     |   SkinsRestorer  |
[10:49:17 INFO]: [SkinsRestorer]     +==================+
[10:49:17 INFO]: [SkinsRestorer] ----------------------------------------------
[10:49:17 INFO]: [SkinsRestorer]     Current version: 14.2.12
[10:49:17 INFO]: [SkinsRestorer]     New version: 15.0.4
[10:49:17 INFO]: [SkinsRestorer]     A new version is available! Download it at:

[10:49:17 INFO]: Enabled plugin SkinsRestorer version 14.2.12 by knat, AlexProgr
ammerDE, Th3Tr0LLeR, McLive, DoNotSpamPls
[10:49:17 INFO]: [SkinsRestorer]     https://github.com/SkinsRestorer/SkinsResto
rerX/releases/download/15.0.4/SkinsRestorer.jar
[10:49:17 INFO]: [SkinsRestorer] ----------------------------------------------
[10:49:17 WARN] [TAB]: The plugin requires BungeeCord build #1774 (released on N
ovember 25th, 2023) and up (or an equivalent fork) to work.
[10:49:17 INFO]: Enabled plugin TAB version 4.1.2 by NEZNAMY
[10:49:17 INFO]: Enabled plugin CommandForward version 0.4.0 by games647, https:
//github.com/games647/CommandForward/graphs/contributors
[10:49:17 WARN]: Exception encountered when loading plugin: SlashServer
java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method
'void <init>()' not found
        at com.minecraftdimensions.slashserver.configlibrary.YamlRepresenter.<in
it>(YamlRepresenter.java:11) ~[?:?]
        at com.minecraftdimensions.slashserver.configlibrary.YamlConfiguration.<
init>(YamlConfiguration.java:20) ~[?:?]
        at com.minecraftdimensions.slashserver.configlibrary.YamlConfiguration.l
oadConfiguration(YamlConfiguration.java:152) ~[?:?]
        at com.minecraftdimensions.slashserver.configlibrary.Config.<init>(Confi
g.java:19) ~[?:?]
        at com.minecraftdimensions.slashserver.SlashServer.setupConfig(SlashServ
er.java:33) ~[?:?]
        at com.minecraftdimensions.slashserver.SlashServer.onEnable(SlashServer.
java:28) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.
java:357) ~[FlameCord_1.9.2.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fbab
8b:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:312) ~[FlameCord_1.9
.2.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fbab8b:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:52) ~
[FlameCord_1.9.2.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fbab8b:unknown]

        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord_1.9.2.j
ar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:9fbab8b:unknown]
[10:49:17 INFO]: LeaderOS » Credit enabled.
[10:49:17 INFO]: LeaderOS » Auth enabled.
[10:49:17 INFO]: LeaderOS » Connect enabled.
[10:49:17 INFO]: LeaderOS » Discord closed.
[10:49:17 INFO]: Enabled plugin LeaderOS version 1.0.3 by leaderos, geik
[10:49:17 INFO]: Enabled plugin BungeeCore version 1.1-SNAPSHOT by null
[10:49:17 INFO]: ======= PROTOCOLIZE =======
[10:49:17 INFO]: Version 2.3.2:910 by Exceptionflug
[10:49:17 INFO]: Supported Platform: Yes (BungeeCordPacketRegistrationStrategy)
[10:49:17 INFO]:
[10:49:17 INFO]: ------------ AdvancedNMotd Updater ----------
[10:49:17 INFO]: You have the latest version of AdvancedNMotd!
[10:49:17 INFO]: Current version: 10.0.0.
[10:49:17 INFO]: ---------------------------------------------
[10:49:17 INFO]:
[10:49:17 INFO]: [FlameCord] Loaded a total of 67268 proxies to the database (1.
48s)!
[10:49:17 INFO]: LeaderOS » Connect module has been successfully connected to th
e room.
[10:49:17 INFO] [Protocolize]: Enabled module dev.simplix.protocolize.data.DataM
odule
[10:49:17 INFO]: Enabled plugin Protocolize version 2.3.2:910 by Exceptionflug
[10:49:17 INFO]: Listening on /0.0.0.0:25565
[10:49:18 INFO] [ajQueue]: You are up to date! (2.6.0)
> bungee
[10:49:20 INFO]: This server is running FlameCord version 1.9.2 by ArkFlame Deve
lopment.

**Comment by NEZNAMY** [comment]
Redownload FlameCord from BBB, that's where I got the jar from just now.

**Comment by Buttercuq** [comment]
> Type /bungee and show output. Works for me:

If it works for you, the problem may be in my plugins, I will try it in different ways, but I appreciate your support anyway.

**Comment by NEZNAMY** [comment]
Try without other plugins & with latest jar from BBB. 
Also this is not support, [support is not provided](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services).

**Comment by NEZNAMY** [comment]
Why did you close the issue? What happened?
