### ISSUE TITLE
[Fabric] Compatibility error with another mod

### ISSUE THREAD

**Issue by ruattd** [NEZNAMY/TAB#1212]
### Server version

1.20.1 with Fabric 0.14.25

### TAB version

4.1.3-SNAPSHOT

### Stack trace

```
[09:06:23 WARN] [Server thread]: [MinecraftServer] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[09:06:23 WARN] [Server thread]: [MinecraftServer] java.lang.ClassNotFoundException: net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at me.neznamy.tab.shared.chat.rgb.format.MiniMessageFormat.<init>(MiniMessageFormat.java:14)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at me.neznamy.tab.shared.chat.rgb.RGBUtils.<init>(RGBUtils.java:44)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at me.neznamy.tab.shared.chat.rgb.RGBUtils.<clinit>(RGBUtils.java:30)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at me.neznamy.tab.shared.placeholders.Animation.<init>(Animation.java:68)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at me.neznamy.tab.shared.placeholders.UniversalPlaceholderRegistry.registerPlaceholders(UniversalPlaceholderRegistry.java:107)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at me.neznamy.tab.shared.backend.BackendPlatform.registerPlaceholders(BackendPlatform.java:37)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at me.neznamy.tab.shared.TAB.load(TAB.java:173)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at me.neznamy.tab.shared.TAB.create(TAB.java:114)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at me.neznamy.tab.platforms.fabric.FabricTAB.lambda$onInitializeServer$2(FabricTAB.java:32)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at net.minecraft.server.MinecraftServer.handler$blb000$fabric-lifecycle-events-v1$beforeSetupServer(MinecraftServer.java:5837)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[09:06:23 WARN] [Server thread]: [MinecraftServer]      at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Additional info

The mod throws the exception after adding owo-lib 0.11.2

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Works for me
```
[11:32:51] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.3
[11:32:51] [main/WARN]: Warnings were found!
 - Mod 'TAB' (tab) 4.1.2 recommends any version of fabric-permissions-api-v0, which is missing!
	 - You should install any version of fabric-permissions-api-v0 for the optimal experience.
[11:32:51] [main/INFO]: Loading 46 mods:
	- fabric-api 0.91.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.3+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.11+d7b148e077
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.2.0+96dfa95977
	   |-- fabric-loot-tables-v1 1.1.44+9e7660c677
	   |-- fabric-message-api-v1 5.1.8+d7b148e077
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.7+29de845d77
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.3+c81d263177
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- java 18
	- minecraft 1.20.1
	- owo 0.11.2+1.20
	   \-- blue_endless_jankson 1.2.2
	- tab 4.1.2
[11:32:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/marti/OneDrive/Po%c4%8d%c3%adta%c4%8d/MC/fabric%201.20.1/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[11:32:51] [main/INFO]: Compatibility level set to JAVA_16
[11:32:51] [main/INFO]: Compatibility level set to JAVA_17
[11:32:52] [main/WARN]: Error loading class: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage (java.lang.ClassNotFoundException: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage)
[11:32:52] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[11:33:02] [main/INFO]: Maybe we take a page out of the Wisp Forest handbook: When in doubt, steal glisco's code
[11:33:03] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:33:05] [main/INFO]: Loaded 7 recipes
[11:33:05] [main/INFO]: Loaded 1271 advancements
[11:33:06] [main/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 2.103 ms
[11:33:06] [Server thread/INFO]: Performing configuration conversion from 4.0.3 to 4.0.4
[11:33:06] [Server thread/INFO]: [DEBUG] Feature PlaceholderManagerImpl processed load in 0ms
[11:33:06] [Server thread/INFO]: [DEBUG] Feature FabricPipelineInjector processed load in 0ms
[11:33:06] [Server thread/INFO]: [DEBUG] Feature HeaderFooter processed load in 0ms
[11:33:06] [Server thread/INFO]: [DEBUG] Feature YellowNumber processed load in 0ms
[11:33:06] [Server thread/INFO]: [DEBUG] Feature Sorting processed load in 0ms
[11:33:06] [Server thread/INFO]: [DEBUG] Feature NameTag processed load in 0ms
[11:33:06] [Server thread/INFO]: [DEBUG] Feature PlayerList processed load in 0ms
[11:33:06] [Server thread/INFO]: Enabled in 393ms
[11:33:06] [Server thread/INFO]: Starting minecraft server version 1.20.1
[11:33:06] [Server thread/INFO]: Loading properties
[11:33:06] [Server thread/INFO]: Default game type: SURVIVAL
[11:33:06] [Server thread/INFO]: Generating keypair
[11:33:06] [Server thread/INFO]: Starting Minecraft server on *:25565
[11:33:06] [Server thread/INFO]: Using default channel type
[11:33:07] [Server thread/INFO]: Preparing level "world"
[11:33:08] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[11:33:11] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[11:33:11] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[11:33:11] [Worker-Main-14/INFO]: Preparing spawn area: 0%
[11:33:11] [Worker-Main-14/INFO]: Preparing spawn area: 0%
[11:33:11] [Worker-Main-14/INFO]: Preparing spawn area: 0%
[11:33:11] [Worker-Main-12/INFO]: Preparing spawn area: 0%
[11:33:11] [Worker-Main-7/INFO]: Preparing spawn area: 0%
[11:33:12] [Worker-Main-13/INFO]: Preparing spawn area: 21%
[11:33:12] [Worker-Main-1/INFO]: Preparing spawn area: 91%
[11:33:12] [Server thread/INFO]: Time elapsed: 4047 ms
[11:33:12] [Server thread/INFO]: Done (5.675s)! For help, type "help"
```

**Comment by ruattd** [comment]
The new stack:

```
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB] java.lang.NoClassDefFoundError: net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.chat.rgb.format.MiniMessageFormat.<init>(MiniMessageFormat.java:14)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.chat.rgb.RGBUtils.<init>(RGBUtils.java:44)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.chat.rgb.RGBUtils.<clinit>(RGBUtils.java:30)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.placeholders.Animation.<init>(Animation.java:68)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.placeholders.UniversalPlaceholderRegistry.registerPlaceholders(UniversalPlaceholderRegistry.java:107)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.backend.BackendPlatform.registerPlaceholders(BackendPlatform.java:40)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.TAB.load(TAB.java:176)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.TAB.create(TAB.java:117)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.platforms.fabric.FabricTAB.lambda$onInitializeServer$2(FabricTAB.java:32)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at net.minecraft.server.MinecraftServer.handler$blb000$fabric-lifecycle-events-v1$beforeSetupServer(MinecraftServer.java:5837)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at java.base/java.lang.Thread.run(Thread.java:1583)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB] Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.chat.rgb.format.MiniMessageFormat.<init>(MiniMessageFormat.java:14)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.chat.rgb.RGBUtils.<init>(RGBUtils.java:44)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.chat.rgb.RGBUtils.<clinit>(RGBUtils.java:30)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.placeholders.Animation.<init>(Animation.java:68)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.placeholders.UniversalPlaceholderRegistry.registerPlaceholders(UniversalPlaceholderRegistry.java:107)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.backend.BackendPlatform.registerPlaceholders(BackendPlatform.java:40)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.TAB.load(TAB.java:176)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.shared.TAB.create(TAB.java:117)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at me.neznamy.tab.platforms.fabric.FabricTAB.lambda$onInitializeServer$2(FabricTAB.java:32)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at net.minecraft.server.MinecraftServer.handler$blb000$fabric-lifecycle-events-v1$beforeSetupServer(MinecraftServer.java:5837)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[04:52:48 WARN] [Server thread]: [MinecraftServer] [TAB]        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by ruattd** [comment]
I tried the latest action build but it didn't work either, with [the same error](#issuecomment-1891301781) thrown.
The class `MiniMessageFormat` might by initialized by JVM in advance, but I'm not sure.

**Comment by NEZNAMY** [comment]
You are using some mod shading a very old version of MiniMessage. Do you really have no idea which one or why is it using an old one?

**Comment by ruattd** [comment]
I fixed it by [a try-catch block](https://github.com/ruattd/TAB/commit/d61a31675d652dd596e5a1d9efebc274465ea33f).
It's not elegant but it works :)

**Comment by NEZNAMY** [comment]
The commit I linked should also fix it.
