### ISSUE TITLE
Placeholders in custom scoreboard not loading properly

### ISSUE THREAD

**Issue by TitianH** [NEZNAMY/TAB#1218]
### Server version

paper 1.20.4

### TAB version

4.1.3-SNAPSHOT

### Stack trace

Caused by: java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.shared.Property.updateAndGet()" because the return value of "me.neznamy.tab.shared.platform.TabPlayer.getProperty(String)" is null
        at me.neznamy.tab.shared.features.scoreboard.ScoreRefresher.getNumberFormat(ScoreRefresher.java:61) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.scoreboard.ScoreRefresher.refresh(ScoreRefresher.java:38) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.updateValue(PlayerPlaceholderImpl.java:56) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:47) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.getLastValue(PlayerPlaceholderImpl.java:89) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.PlaceholderManagerImpl.addUsedPlaceholder(PlaceholderManagerImpl.java:260) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.PlaceholderManagerImpl.getPlaceholder(PlaceholderManagerImpl.java:354) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
        at me.neznamy.tab.shared.features.PlaceholderManagerImpl.recalculateUsedPlaceholders(PlaceholderManagerImpl.java:269) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.PlaceholderManagerImpl.addUsedPlaceholder(PlaceholderManagerImpl.java:257) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.types.Refreshable.lambda$addUsedPlaceholders$0(Refreshable.java:40) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
        at me.neznamy.tab.shared.features.types.Refreshable.addUsedPlaceholders(Refreshable.java:40) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.Property.analyze(Property.java:141) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.Property.<init>(Property.java:89) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.platform.TabPlayer.setProperty(TabPlayer.java:122) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.platform.TabPlayer.setProperty(TabPlayer.java:147) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.scoreboard.ScoreRefresher.registerProperties(ScoreRefresher.java:49) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.scoreboard.lines.StableDynamicLine.register(StableDynamicLine.java:60) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.scoreboard.ScoreboardImpl.addLine(ScoreboardImpl.java:212) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at de.craftstuebchen.minez3.adapter.TabScoreboard.showBoard(TabScoreboard.java:29) ~[MzCore-0.34.0-all.jar:?]
        at de.craftstuebchen.minez3.scoreboard.MzScoreboardManager.showScore(MzScoreboardManager.java:88) ~[MzCore-0.34.0-all.jar:?]
        at de.craftstuebchen.minez3.scoreboard.MzScoreboardManager.editScoreBoard(MzScoreboardManager.java:162) ~[MzCore-0.34.0-all.jar:?]
        at de.craftstuebchen.minez3.scoreboard.MzScoreboardManager.toggleScore(MzScoreboardManager.java:104) ~[MzCore-0.34.0-all.jar:?]
        at de.craftstuebchen.minez3.scoreboard.ScoreboardCommand.onCommand(ScoreboardCommand.java:21) ~[MzCore-0.34.0-all.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Weeper-API-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more

### Steps to reproduce (if known)

Well.. thats a little hard without my plugin. I have some custom scoreboards toggleable through a command. In the 4.1.2 it worked flawlessly until i added the new spacing chars "||"to my custom scoreboard. The scores started mixing somehow. So i took a look here if there was any fix. In the commits i saw one exacly fixing my problem, so i tried the latest from actions.

But it seems to load any placeholder one by one with the exception shown top. When i toggle my scoreboard until all placeholders show up it works fine until the next restart.

### Additional info

no errors in placeholder-errors.log

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Try new build.

**Comment by TitianH** [comment]
Thanks for the quick response, but it doesnt seem to work.

```
Caused by: java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.shared.Property.get()" because the return value of "me.neznamy.tab.shared.platform.TabPlayer.getProperty(String)" is null
        at me.neznamy.tab.shared.features.scoreboard.lines.StableDynamicLine.unregister(StableDynamicLine.java:68) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.scoreboard.ScoreboardImpl.removeLine(ScoreboardImpl.java:223) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at de.craftstuebchen.minez3.adapter.TabScoreboard.showBoard(TabScoreboard.java:25) ~[MzCore-0.34.0-all.jar:?]
        at de.craftstuebchen.minez3.scoreboard.MzScoreboardManager.showScore(MzScoreboardManager.java:88) ~[MzCore-0.34.0-all.jar:?]
        at de.craftstuebchen.minez3.scoreboard.MzScoreboardManager.editScoreBoard(MzScoreboardManager.java:162) ~[MzCore-0.34.0-all.jar:?]
        at de.craftstuebchen.minez3.scoreboard.MzScoreboardManager.toggleScore(MzScoreboardManager.java:104) ~[MzCore-0.34.0-all.jar:?]
        at de.craftstuebchen.minez3.scoreboard.ScoreboardCommand.onCommand(ScoreboardCommand.java:21) ~[MzCore-0.34.0-all.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Weeper-API-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more
```

**Comment by NEZNAMY** [comment]
How did you get it? It looks like the scoreboard was never registered to the player, but player is in the list of registered players.

**Comment by TitianH** [comment]
since this code is used in a giant plugin, this is the snippet.
i will try to reproduce it in a smaller plugin, but takes a little :)


```
public void showBoard(Player player, List<String> lines) {
        String sbId = "minezboard" + player.getUniqueId();
        Scoreboard scoreboard = tabAPI.getScoreboardManager().getRegisteredScoreboards().get(sbId);

        if (scoreboard == null) {
            scoreboard = tabAPI.getScoreboardManager()
                .createScoreboard(sbId, "þ", Collections.emptyList());
        } else {
            for (int i = scoreboard.getLines().size() - 1; i >= 0; i--) {
                scoreboard.removeLine(i);
            }
        }
        for (String line : lines) {
            scoreboard.addLine(line);
        }
        tabAPI.getScoreboardManager()
            .showScoreboard(tabAPI.getPlayer(player.getUniqueId()), scoreboard);
    }
```

**Comment by TitianH** [comment]
I was able to reproduce it with:
- TAB latest from actions
- paper 1.20.4
- vault
- essentialsX
- placeholderapi
- vault eco placeholders with the vault extension (/papi ecloud download Vault)
- and my miniplugin here: https://dev.craftstuebchen.de/public-stuff/tab-test/-/blob/master/src/main/java/de/craftstuebchen/tabtest/Tab_test.java?ref_type=heads

typing /tab-test 1 reproduced the error:

```
Caused by: java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.shared.Property.updateAndGet()" because the return value of "me.neznamy.tab.shared.platform.TabPlayer.getProperty(String)" is null
        at me.neznamy.tab.shared.features.scoreboard.ScoreRefresher.getNumberFormat(ScoreRefresher.java:61) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.scoreboard.ScoreRefresher.refresh(ScoreRefresher.java:38) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.updateValue(PlayerPlaceholderImpl.java:56) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:47) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.placeholders.types.PlayerPlaceholderImpl.getLastValue(PlayerPlaceholderImpl.java:89) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.placeholders.types.TabPlaceholder.set(TabPlaceholder.java:84) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.Property.update(Property.java:237) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.Property.analyze(Property.java:144) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.Property.<init>(Property.java:89) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.platform.TabPlayer.setProperty(TabPlayer.java:122) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.platform.TabPlayer.setProperty(TabPlayer.java:147) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.scoreboard.ScoreRefresher.registerProperties(ScoreRefresher.java:49) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.scoreboard.lines.StableDynamicLine.register(StableDynamicLine.java:60) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at me.neznamy.tab.shared.features.scoreboard.ScoreboardImpl.addLine(ScoreboardImpl.java:212) ~[TAB-4.1.3-SNAPSHOT.jar:?]
        at de.craftstuebchen.tabtest.Tab_test.showBoard(Tab_test.java:69) ~[tab-test-1.0-SNAPSHOT.jar:?]
        at de.craftstuebchen.tabtest.Tab_test.onCommand(Tab_test.java:36) ~[tab-test-1.0-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Weeper-API-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more
```

typing /tab-test 2 worked fine

maybe something with different number formats in the same scoreboard?
%vault_eco_balance_formatted%
%vault_eco_balance_fixed%
%vault_eco_balance_commas%
%vault_eco_balance%

**Comment by NEZNAMY** [comment]
I was not able to reproduce this exact error, I only got a different one which I fixed. I also added a null check. Try new build.

**Comment by TitianH** [comment]
it works now! thank you very much for the quick fixes :)
