### ISSUE TITLE
Internal exception

### ISSUE THREAD

**Issue by vrazvang** [NEZNAMY/TAB#126]
**Server version** _BungeeCord latest version and Paper-145 (1.15.2)_

**Plugin version** _TAB 271_

**Describe the bug** Internal. Exception: io.nettLthandl.ercodecnecoderException: con9oo9l.e.9son—lson5LintaxException: congooql.e.gson.streaffilal.formed-lsonException: Use JsonFieader.setLenient(true. accept Nal.formed -1:5011 at line 1 col.unn 1 path $ 

**How to reproduce** When a player connects to the server, the one already on the server rejects it with this error.

**Additional info** (errors, screenshots, ...)

https://i.imgur.com/Ep6KXNe.png

**Comment by vrazvang** [comment]
From Bungee:

`       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:707) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at me.neznamy.tab.platforms.bungee.Main$2.write(Main.java:214) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:762) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1089) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at us.myles.viaversion.libs.bungeecordchat.api.chat.BaseComponent.toLegacyText(BaseComponent.java:226) ~[?:?]
        at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.ChatRewriter.jsonTextToLegacy(ChatRewriter.java:118) ~[?:?]
        at nl.matsv.viabackwards.protocol.protocol1_12_2to1_13.packets.PlayerPacket1_13$6$1.handle(PlayerPacket1_13.java:255) ~[?:?]
        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19) ~[?:?]
        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:127) ~[?:?]
        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:186) ~[?:?]
        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:427) ~[?:?]
        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81) ~[?:?]
        at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:62) ~[?:?]
        at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[waterfall-326.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        ... 20 more`

**Comment by NEZNAMY** [comment]
How is this an error in TAB when it's ViaVersion throwing nullpointer ? Can you send your config ?
