### ISSUE TITLE
[Velocity] Error in RedisBungee hook

### ISSUE THREAD

**Issue by funnycubeguy** [NEZNAMY/TAB#1266]
### Server version

1.20.1 Velocity

### TAB version

Latest github build (beta)

### Describe the bug

I have 3 velocity instances setup with redisbungee syncing all the player data between them. I am using the latest version of tab from github, when a velocity instance crash's I get this error in the log and the tablist vanishes.

[01:17:56 WARN] [tab]: §cFailed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[01:17:56 WARN] [tab]: §cjava.lang.NullPointerException: Cannot invoke "com.imaginarycode.minecraft.redisbungee.api.PubSubListener.addChannel(String[])" because the return value of "com.imaginarycode.minecraft.redisbungee.api.RedisBungeePlugin.getPubSubListener()" is null
[01:17:56 WARN] [tab]: §c       at com.imaginarycode.minecraft.redisbungee.AbstractRedisBungeeAPI.registerPubSubChannels(AbstractRedisBungeeAPI.java:271)
[01:17:56 WARN] [tab]: §c       at me.neznamy.tab.platforms.velocity.features.VelocityRedisSupport.register(VelocityRedisSupport.java:37)
[01:17:56 WARN] [tab]: §c       at me.neznamy.tab.shared.features.redis.RedisSupport.load(RedisSupport.java:165)
[01:17:56 WARN] [tab]: §c       at me.neznamy.tab.shared.FeatureManager.load(FeatureManager.java:58)
[01:17:56 WARN] [tab]: §c       at me.neznamy.tab.shared.TAB.load(TAB.java:177)
[01:17:56 WARN] [tab]: §c       at me.neznamy.tab.shared.command.DisabledCommand.execute(DisabledCommand.java:30)
[01:17:56 WARN] [tab]: §c       at me.neznamy.tab.platforms.velocity.VelocityTabCommand.execute(VelocityTabCommand.java:25)
[01:17:56 WARN] [tab]: §c       at me.neznamy.tab.platforms.velocity.VelocityTabCommand.execute(VelocityTabCommand.java:19)
[01:17:56 WARN] [tab]: §c       at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81)
[01:17:56 WARN] [tab]: §c       at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[01:17:56 WARN] [tab]: §c       at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:228)
[01:17:56 WARN] [tab]: §c       at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:261)
[01:17:56 WARN] [tab]: §c       at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[01:17:56 WARN] [tab]: §c       at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[01:17:56 WARN] [tab]: §c       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:17:56 WARN] [tab]: §c       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:17:56 WARN] [tab]: §c       at java.base/java.lang.Thread.run(Thread.java:840)

### Expected behavior

Don't show the error and tablist works

### Steps to reproduce

Setup 3 velocity tabs with redisbungee for velocity installed. Reboot one of the velocity tabs.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/1b51c421-c8b1-4205-9979-dc8b48b7b578)
This looks like a RedisBungee bug, assuming it's enabled properly.

**Comment by NEZNAMY** [comment]
This is most likely a RedisBungee bug. User may have not configured it correctly. User did not respond in a month, assuming they have died.
