### ISSUE TITLE
Could not initialize class me.neznamy.tab.shared.chat.rgb.RGBUtils

### ISSUE THREAD

**Issue by N1zard** [NEZNAMY/TAB#1280]
### Server version

Arclight Trials

### TAB version

4.1.4

### Stack trace

[15:03:07 INFO] [Console]: [TAB] [WARN] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[15:03:07 INFO] [Console]: [TAB] [WARN] java.lang.NoClassDefFoundError: Could not initialize class me.neznamy.tab.shared.chat.rgb.RGBUtils
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.placeholders.Animation.<init>(Animation.java:62)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.placeholders.UniversalPlaceholderRegistry.registerPlayerPlaceholders(UniversalPlaceholderRegistry.java:133)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.placeholders.UniversalPlaceholderRegistry.registerPlaceholders(UniversalPlaceholderRegistry.java:48)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.backend.BackendPlatform.registerPlaceholders(BackendPlatform.java:40)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.registerPlaceholders(BukkitPlatform.java:147)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.TAB.load(TAB.java:176)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.command.DisabledCommand.execute(DisabledCommand.java:30)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.platforms.bukkit.BukkitTabCommand.onCommand(BukkitTabCommand.java:25)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServerMixin.java:877)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at MC-BOOTSTRAP/brigadier@1.1.8/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.commands.Commands.m_242674_(CommandsMixin.java:257)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerPlayNetHandlerMixin.java:2853)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_244885_(ServerPlayNetHandlerMixin.java:1223)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:732)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at java.base/java.lang.Thread.run(Thread.java:840)
[15:03:07 INFO] [Console]: [TAB] [WARN] Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer [in thread "Server thread"]
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.chat.rgb.format.MiniMessageFormat.<clinit>(MiniMessageFormat.java:14)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.chat.rgb.RGBUtils.<init>(RGBUtils.java:43)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.chat.rgb.RGBUtils.<clinit>(RGBUtils.java:29)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.placeholders.Animation.<init>(Animation.java:62)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.placeholders.UniversalPlaceholderRegistry.registerPlayerPlaceholders(UniversalPlaceholderRegistry.java:133)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.placeholders.UniversalPlaceholderRegistry.registerPlaceholders(UniversalPlaceholderRegistry.java:48)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.backend.BackendPlatform.registerPlaceholders(BackendPlatform.java:40)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.registerPlaceholders(BukkitPlatform.java:147)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.TAB.load(TAB.java:176)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.shared.TAB.create(TAB.java:118)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at me.neznamy.tab.platforms.bukkit.BukkitTAB.onEnable(BukkitTAB.java:17)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.handler$bbf000$arclight$enablePlugins(MinecraftServerMixin.java:2137)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:385)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:308)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:164)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
[15:03:07 INFO] [Console]: [TAB] [WARN]         at java.base/java.lang.Thread.run(Thread.java:840)

### Steps to reproduce (if known)

1. start server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Will be fixed in the next version. In the meantime, you can get latest dev build from [actions](https://github.com/NEZNAMY/TAB/actions/runs/8939207820).
