### ISSUE TITLE
Virus or false positive in version 4.1.4?

### ISSUE THREAD

**Issue by XFlatoutDudeX** [NEZNAMY/TAB#1291]
### Server version

Paper 1.20.4

### TAB version

4.1.4

### Stack trace

java.io.FileNotFoundException: plugins\TAB v4.1.4.jar (Operation did not complete successfully because the file contains a virus or potentially unwanted software)
	at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:356) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:273) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:223) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1492) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1458) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:251) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:180) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:345) ~[?:?]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:60) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:47) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:101) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.Main.main(Main.java:120) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.craftbukkit.Main.main(Main.java:326) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps to reproduce (if known)

Download 4.1.4 via spigotmc, windows defender will say its a virus, if it was already in the folder when starting, the server will think its a virus (via console on windows)

### Additional info

![image](https://github.com/NEZNAMY/TAB/assets/44393004/00cdc42e-1bad-45dc-8bf9-3579443e9314)
this is what windows defender popped up when it detected it

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://www.spigotmc.org/threads/windows-defender-false-positives.639507/
