### ISSUE TITLE
Skin Glow plugin. Eglow , Fancyglow

### ISSUE THREAD

**Issue by mainulXD18** [NEZNAMY/TAB#1303]
### TAB version

4.1.6-SNAPSHOT

### Software causing compatibility issue

Server version : 1.20.4 pufferfish latest build

The issue: when i enable glow from the eglow plugin it can only display my tablist username color. And when i choose a different color it doesn't changes the glow color. So for example if my username color is white and i enable glow with a different color it doesn't shows that color rather it shows the username color. Disabling TAB plugin completely fixes it.

The Error on Startup:

[11:55:27] [Server thread/WARN]: [eGlow] Task #115 for eGlow v3.2.8 generated an exception
java.lang.NoSuchMethodError: 'me.neznamy.tab.shared.config.file.ConfigurationFile me.neznamy.tab.shared.TAB.getConfig()'
	at me.mrgraycat.eglow.addon.tab.TABAddon.loadTABSettings(TABAddon.java:90) ~[eGlow_3.2.8_1.9.4-1.20.4_1.jar:?]
	at me.mrgraycat.eglow.addon.tab.TABAddon.<init>(TABAddon.java:63) ~[eGlow_3.2.8_1.9.4-1.20.4_1.jar:?]
	at me.mrgraycat.eglow.EGlow$1.run(EGlow.java:118) ~[eGlow_3.2.8_1.9.4-1.20.4_1.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1143) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
That plugin is depending on an old version of TAB. If you want to use plugins using outdated versions of TAB, use outdated versions of TAB. Otherwise, update the other plugin and if it's already updated, contact the developer.

**Comment by mainulXD18** [comment]
TAB version 4.1.0 fixed the problem.
Thank you. W

Also waiting for the partnership announcement in root 🫡

**Comment by NEZNAMY** [comment]
You'll be waiting for a long time, I have cancelled it.
