### ISSUE TITLE
Failed to open plugin jar 

### ISSUE THREAD

**Issue by SirKillian** [NEZNAMY/TAB#1322]
### Server version

Paper version 1.21-21-master@0a1b133

### TAB version

4.1.6

### Stack trace

```[08:45:08] [ServerMain/ERROR]: [EntrypointUtil] Failed to open plugin jar plugins/TAB v4.1.6.jar
java.lang.RuntimeException: Failed to open plugin jar plugins/TAB v4.1.6.jar
	at io.papermc.paper.pluginremap.PluginRemapper.remap(PluginRemapper.java:339) ~[paper-1.21.jar:1.21-21-0a1b133]
	at io.papermc.paper.pluginremap.PluginRemapper.remapPlugin(PluginRemapper.java:266) ~[paper-1.21.jar:1.21-21-0a1b133]
	at io.papermc.paper.pluginremap.PluginRemapper.rewritePluginDirectory(PluginRemapper.java:204) ~[paper-1.21.jar:1.21-21-0a1b133]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:42) ~[paper-1.21.jar:1.21-21-0a1b133]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[paper-1.21.jar:1.21-21-0a1b133]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.21.jar:1.21-21-0a1b133]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[paper-1.21.jar:1.21-21-0a1b133]
	at net.minecraft.server.Main.main(Main.java:122) ~[paper-1.21.jar:1.21-21-0a1b133]
	at org.bukkit.craftbukkit.Main.main(Main.java:298) ~[paper-1.21.jar:1.21-21-0a1b133]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.util.zip.ZipException: zip END header not found
	at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1320) ~[jdk.zipfs:?]
	at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1541) ~[jdk.zipfs:?]
	at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179) ~[jdk.zipfs:?]
	at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125) ~[jdk.zipfs:?]
	at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120) ~[jdk.zipfs:?]
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528) ~[?:?]
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:440) ~[?:?]
	at io.papermc.paper.pluginremap.PluginRemapper.remap(PluginRemapper.java:290) ~[paper-1.21.jar:1.21-21-0a1b133]
	... 10 more
```

### Steps to reproduce (if known)

Simply upload TAB 4.1.6 to the server and restart.
This will fail loading and error will be present.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by SirKillian** [comment]
Redownloading seems to have done the trick. Thanks!
