### ISSUE TITLE
Error dispatching event ChatEvent

### ISSUE THREAD

**Issue by RICE0707** [NEZNAMY/TAB#1338]
### Server version

waterfall-1.21-579

### TAB version

4.1.2 / TAB-Bridge.v5.0.6

### Plugin list

![image](https://github.com/user-attachments/assets/fc597eb5-95ec-49d9-8684-239e9557374f)

### Describe the bug
```
[22:29:56] [Netty Worker IO Thread #36/WARN]: Error dispatching event ChatEvent(super=TargetedEvent(sender=XHIoCK, receiver=net.md_5.bungee.ServerConnection@2c8c9dff), cancelled=false, message=/sbt) to listener me.neznamy.tab.platforms.bungeecord.BungeeEventListener@68ffbc99
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.MinecraftEncoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
	at net.md_5.bungee.netty.ChannelWrapper.getEncodeProtocol(ChannelWrapper.java:51) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.UserConnection.sendPacketQueued(UserConnection.java:198) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:565) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:520) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:508) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at me.neznamy.tab.platforms.bungeecord.BungeeTabPlayer.sendMessage(BungeeTabPlayer.java:73) ~[?:?]
	at me.neznamy.tab.shared.platform.TabPlayer.sendMessage(TabPlayer.java:202) ~[?:?]
	at me.neznamy.tab.shared.command.SubCommand.sendMessage(SubCommand.java:98) ~[?:?]
	at me.neznamy.tab.shared.command.scoreboard.ScoreboardCommand.execute(ScoreboardCommand.java:35) ~[?:?]
	at me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:53) ~[?:?]
	at me.neznamy.tab.shared.features.scoreboard.ScoreboardManagerImpl.onCommand(ScoreboardManagerImpl.java:166) ~[?:?]
	at me.neznamy.tab.shared.FeatureManager.onCommand(FeatureManager.java:183) ~[?:?]
	at me.neznamy.tab.shared.platform.EventListener.command(EventListener.java:86) ~[?:?]
	at me.neznamy.tab.platforms.bungeecord.BungeeEventListener.onCommand(BungeeEventListener.java:63) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.connection.UpstreamBridge.handleChat(UpstreamBridge.java:227) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:205) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.protocol.packet.UnsignedClientCommand.handle(UnsignedClientCommand.java:36) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:128) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
```
### Expected behavior

Players can use the scoreboard's` toggle-command `function normally

### Steps to reproduce

Use` /sbt ` , but this doesn't seem to trigger every time, and I don't know a more specific way to reproduce it

### Checklist

- [] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by RICE0707** [comment]
btw Checklist has to check everything, but that doesn't mean I the boxes without actually reading them
![image](https://github.com/user-attachments/assets/90a1327d-2149-42ab-afe7-e6292b7be035)

**Comment by NEZNAMY** [comment]
No, you don't have to check the 3rd one.
On which marketplace is 4.1.2 latest? Wyy are you reporting already fixed error?

**Comment by RICE0707** [comment]
> No, you don't have to check the 3rd one. On which marketplace is 4.1.2 latest? Why are you reporting already fixed error?

In which version was this fixed?

**Comment by NEZNAMY** [comment]
I don't remember, why don't you just update to latest?

**Comment by RICE0707** [comment]
> I don't remember, why don't you just update to latest?

There seems to be a new version that changes the way hex works so that my chat plugin can't interpret hex color codes correctly, so I can't upgrade.

**Comment by RICE0707** [comment]
It seems to be an old version hexadecimal color code issue that occurred after adding 1.20.5 support (TAB 4.1.3)
My main server version is 1.20.2

**Comment by NEZNAMY** [comment]
TAB does not handle chat in any way. You didn't explain your issue either. What is not working exactly?

**Comment by RICE0707** [comment]
> TAB does not handle chat in any way. You didn't explain your issue either. What is not working exactly?

When I add the `tab_tagprefix` placeholder to `VentureChat`,
Since `tab_tagprefix` comes with hexadecimal color code (`tagprefix: '&#ff8080ꄆ'`),

After the `TAB 4.1.3` version, it seems that some codes of the hexadecimal color code have been changed,
While `VentureChat` has not yet processed `Java 1.20.5` and above,
So I cannot upgrade ` TAB ` to all versions above ` 4.1.3 `,
This is why I can't upgrade ` TAB `

**Comment by NEZNAMY** [comment]
And how is that a TAB issue?

**Comment by RICE0707** [comment]
> And how is that a TAB issue?

Back to the problem itself, this is a TAB error

**Comment by NEZNAMY** [comment]
You mean the one I fixed half a year ago?

**Comment by RICE0707** [comment]
> You mean the one I fixed half a year ago?

Did you fix it in a version after 4.1.2?

**Comment by NEZNAMY** [comment]
After checking the error again on PC, looks like this is a new BungeeCord bug that needs to be compensated for as well. I'll do it now, however, that doesn't change the fact that you'll need to update.

**Comment by RICE0707** [comment]
> After checking the error again on PC, looks like this is a new BungeeCord bug that needs to be compensated for as well. I'll do it now, however, that doesn't change the fact that you'll need to update.

Thank you for your confirmation. I will fork VentureChat myself, modify its code, and try to update to the new TAB version. Thank you for your positive response.

**Comment by RICE0707** [comment]
I found a solution. After removing the ` & ` in ` tagprefix: '&#ff8080ꄆ' `, the hexadecimal color code can be parsed normally, and I can upgrade TAB!
