### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Rexmen1** [NEZNAMY/TAB#1340]
### Server version

1.21

### TAB version

TAB.v4.1.6

### Stack trace

[11:21:14 WARN]: java.lang.IndexOutOfBoundsException: index: 925, length: 101 (expected: range(0, 1024))
[11:21:14 WARN]:        at TAB-Bridge.v5.0.7.jar//me.neznamy.tab.bridge.bukkit.BridgeChannelDuplexHandler.write(BridgeChannelDuplexHandler.java:31)
[11:21:20 WARN]: java.lang.IndexOutOfBoundsException: index: 925, length: 101 (expected: range(0, 1024))
[11:21:20 WARN]:        at TAB-Bridge.v5.0.7.jar//me.neznamy.tab.bridge.bukkit.BridgeChannelDuplexHandler.write(BridgeChannelDuplexHandler.java:31)

[11:16:09 INFO]: [TAB-Bridge] [WARN] Placeholder %javascript_boosts% took 56ms to return value for hobbes_2209
[11:16:11 INFO]: [TAB-Bridge] [WARN] Placeholder %javascript_boosts% took 71ms to return value for Baby_Dino2

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show the full stack trace. If it's missing, [here](https://github.com/NEZNAMY/TAB/wiki/Error-logging#about) is a tip to make it show. Then send ideally the whole server log.

**Comment by Rexmen1** [comment]
spam is in spigot server, and using tab in velocity

**Comment by Rexmen1** [comment]
https://mclo.gs/bJALGAt

**Comment by Rexmen1** [comment]
here updated one, i had console filter on

https://mclo.gs/P4Wcu3K

**Comment by NEZNAMY** [comment]
Did you add the startup flag? The error on the bottom is incomplete. Either way, the error is thrown at [this line](https://github.com/NEZNAMY/TAB-Bridge/blob/main/src/main/java/me/neznamy/tab/bridge/bukkit/BridgeChannelDuplexHandler.java#L31), which only forwards the packets in the pipeline. Checking the earlier errors, the issue is in `packetevents-spigot-2.4.0.jar`. Remove it and try again. Future TAB-Bridge version will remove this entirely, not showing TAB-Bridge in that error anymore.

**Comment by Rexmen1** [comment]
ok

**Comment by NEZNAMY** [comment]
No response for 3 weeks, assuming user has died. This issue is caused by another plugin.

**Comment by Rexmen1** [comment]
lol

**Comment by Rexmen1** [comment]
btw issue wasn't the error but this line to be exact
[11:16:11 INFO]: [TAB-Bridge] [WARN] Placeholder %javascript_boosts% took 71ms to return value for Baby_Dino2

**Comment by NEZNAMY** [comment]
That warn is purely informational and doesn't cause packet encoding errors.
