### ISSUE TITLE
Thread TAB Processing Thread failed main thread check: Chunk getEntities call java.lang.Throwable: null

### ISSUE THREAD

**Issue by PystoyPlayer** [NEZNAMY/TAB#1349]
### Server version

Purpur 1.20.1

### TAB version

4.1.6

### Stack trace

[17:42:06 INFO]: UUID of player sigma757575 is 223afd75-5526-3200-b89e-909591c70e42
[17:42:06 ERROR]: Thread TAB Processing Thread failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2646) ~[?:?]
        at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:2103) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntity(EntityUtilities.java:106) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:382) ~[ProtocolLib.jar:?]
        at net.citizensnpcs.ProtocolLibListener.getNPCFromPacket(ProtocolLibListener.java:232) ~[Citizens-2.0.32-b3208.jar:?]
        at net.citizensnpcs.ProtocolLibListener.access$000(ProtocolLibListener.java:56) ~[Citizens-2.0.32-b3208.jar:?]
        at net.citizensnpcs.ProtocolLibListener$1.onPacketSending(ProtocolLibListener.java:73) ~[Citizens-2.0.32-b3208.jar:?]
        at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:120) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:120) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:44) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:449) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2310) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2296) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at me.neznamy.tab.platforms.bukkit.nms.PacketSender.lambda$new$0(PacketSender.java:40) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.platforms.bukkit.nms.PacketSender.sendPacket(PacketSender.java:54) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.platforms.bukkit.entity.PacketEntityView.lambda$tryLoad$2(PacketEntityView.java:97) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.platforms.bukkit.entity.PacketEntityView.spawnEntity(PacketEntityView.java:328) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.backend.features.unlimitedtags.ArmorStand.spawn(ArmorStand.java:122) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.backend.features.unlimitedtags.BackendArmorStandManager.spawn(BackendArmorStandManager.java:161) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.backend.features.unlimitedtags.BackendNameTagX.spawnArmorStands(BackendNameTagX.java:100) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.backend.features.unlimitedtags.BackendNameTagX.onJoin(BackendNameTagX.java:76) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.FeatureManager.onJoin(FeatureManager.java:151) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.platform.EventListener.lambda$join$0(EventListener.java:27) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:171) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.cpu.CpuManager.lambda$submit$1(CpuManager.java:96) ~[TAB.v4.1.6.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[17:42:07 ERROR]: [Citizens] Unhandled exception occurred in onPacketSending(PacketEvent) for Citizens
java.lang.IllegalStateException: Unable to invoke method public net.minecraft.world.entity.Entity net.minecraft.server.level.WorldServer.b(int)
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:25) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntity(EntityUtilities.java:106) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:382) ~[ProtocolLib.jar:?]
        at net.citizensnpcs.ProtocolLibListener.getNPCFromPacket(ProtocolLibListener.java:232) ~[Citizens-2.0.32-b3208.jar:?]
        at net.citizensnpcs.ProtocolLibListener.access$000(ProtocolLibListener.java:56) ~[Citizens-2.0.32-b3208.jar:?]
        at net.citizensnpcs.ProtocolLibListener$1.onPacketSending(ProtocolLibListener.java:73) ~[Citizens-2.0.32-b3208.jar:?]
        at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:120) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:120) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:44) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:449) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2310) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2296) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at me.neznamy.tab.platforms.bukkit.nms.PacketSender.lambda$new$0(PacketSender.java:40) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.platforms.bukkit.nms.PacketSender.sendPacket(PacketSender.java:54) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.platforms.bukkit.entity.PacketEntityView.lambda$tryLoad$2(PacketEntityView.java:97) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.platforms.bukkit.entity.PacketEntityView.spawnEntity(PacketEntityView.java:328) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.backend.features.unlimitedtags.ArmorStand.spawn(ArmorStand.java:122) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.backend.features.unlimitedtags.BackendArmorStandManager.spawn(BackendArmorStandManager.java:161) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.backend.features.unlimitedtags.BackendNameTagX.spawnArmorStands(BackendNameTagX.java:100) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.backend.features.unlimitedtags.BackendNameTagX.onJoin(BackendNameTagX.java:76) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.FeatureManager.onJoin(FeatureManager.java:151) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.platform.EventListener.lambda$join$0(EventListener.java:27) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:171) ~[TAB.v4.1.6.jar:?]
        at me.neznamy.tab.shared.cpu.CpuManager.lambda$submit$1(CpuManager.java:96) ~[TAB.v4.1.6.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2646) ~[?:?]
        at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:2103) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib.jar:?]
        ... 40 more
[17:42:07 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata@6b20853[
    b=2000000960
    c=[b[id=0, serializer=net.minecraft.network.syncher.DataWatcherSerializer$1@6d3cd100, value=32], b[id=2, serializer=net.minecraft.network.syncher.DataWatcherSerializer$1@106ebf13, value=Optional[literal{}]], b[id=3, serializer=net.minecraft.network.syncher.DataWatcherSerializer$1@60169e52, value=false], b[id=15, serializer=net.minecraft.network.syncher.DataWatcherSerializer$1@6d3cd100, value=16]]
  ]
[17:42:07 INFO]: sigma757575 joined the game
[17:42:07 INFO]: sigma757575[/46.249.171.130:36437] logged in with entity id 703438 at ([world]0.5, 92.0, 0.5)
[17:42:07 INFO]: [AuthMe] sigma757575 logged in

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
replace %server_total_entities%. by %sync:server_total_entities%.

**Comment by PystoyPlayer** [comment]
> This is a bug in citizensnpcs plugin. It has a packet listener sync to called thread (TAB's thread in this case), which is calling a bukkit method that requires to be called in server thread. Unlimited nametags are now officially unsupported and will be removed in the next version anyway, so TAB will no longer be triggering this bug.

Oh, I see. Thanks for so fast reply! But how to set custom names without Unlimited nametags ? I have CMI custom nicknames and they work for customtabname but don't work for customtagname without unlimited name tags

**Comment by NEZNAMY** [comment]
> how to set custom names without Unlimited nametags ?

You don't with TAB. You'll need another plugin for that.

**Comment by NEZNAMY** [comment]
Issue is caused by another plugin and TAB only triggers it, although unlimited nametags will be removed in the future, so it will not even be triggering the issue anymore.
