### ISSUE TITLE
scoreboard error

### ISSUE THREAD

**Issue by dugesti** [NEZNAMY/TAB#1382]
### Server version

paper 1.18.2

### TAB version

5.0.1

### Stack trace

	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:229) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:219) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:213) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:353) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:265) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.network.protocol.game.ClientboundSetPlayerTeamPacket.<init>(ClientboundSetPlayerTeamPacket.java:30) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundSetPlayerTeamPacket.createAddOrModifyPacket(ClientboundSetPlayerTeamPacket.java:34) ~[?:?]
	at net.minecraft.server.players.PlayerList.updateEntireScoreboard(PlayerList.java:507) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:285) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:215) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:196) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:84) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:558) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:231) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1625) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1228) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
[20:42:04] [Server thread/INFO]: Sytex131 lost connection: Invalid player data

### Additional info

This error occurs at random intervals on my server and I cannot log in to the server. However, when I restart the server, the problem is resolved, but it happens again after a few days. I am using the latest version tab plugin and velocityscoreboardapi.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
TAB does not create server-sided teams. It only sends packets. Uninstall TAB and try again to confirm it will keep happening.

**Comment by dugesti** [comment]
This problem sometimes occurs once a week, sometimes once a day, and I cannot uninstall the tab plugin because there are active players. What could be causing the problem?

**Comment by NEZNAMY** [comment]
Some plugin (probably) created a team and added `null` as player into it, based on the stack trace. The issue is not caused by TAB and therefore I will not be investigating it.

**Comment by NEZNAMY** [comment]
No response for 2 weeks, assuming user has died. The issue is not caused by TAB.
