### ISSUE TITLE
A java.lang.IllegalStateException occurs as soon as a player joins when TAB and PremiumVanish are installed.

### ISSUE THREAD

**Issue by MemencioPerez** [NEZNAMY/TAB#1401]
### TAB version

5.0.3

### Software causing compatibility issue

PremiumVanish (2.9.16)

### Additional info

I encountered this bug using Arclight 1.16.5 and then tested it in Spigot 1.16.5 to confirm that it is not a strange interaction due to the former being a Forge/Bukkit hybrid. This problem only occurs when TAB is installed, if I remove it PremiumVanish seems to work fine. 

Stacktrace:
```
[22:51:21] [TAB Processing Thread/WARN]: java.lang.IllegalStateException: PlayerInfoPacketEvent cannot be triggered asynchronously from another thread.
[22:51:21] [TAB Processing Thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
[22:51:21] [TAB Processing Thread/WARN]: 	at de.myzelyam.premiumvanish.bukkit.visibility.hiders.PlayerInfoPacketAdapter.onPacketSending(PlayerInfoPacketAdapter.java:38)
[22:51:21] [TAB Processing Thread/WARN]: 	at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74)
[22:51:21] [TAB Processing Thread/WARN]: 	at com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:123)
[22:51:21] [TAB Processing Thread/WARN]: 	at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7)
[22:51:21] [TAB Processing Thread/WARN]: 	at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:123)
[22:51:21] [TAB Processing Thread/WARN]: 	at com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30)
[22:51:21] [TAB Processing Thread/WARN]: 	at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:102)
[22:51:21] [TAB Processing Thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528)
[22:51:21] [TAB Processing Thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516)
[22:51:21] [TAB Processing Thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528)
[22:51:21] [TAB Processing Thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44)
[22:51:21] [TAB Processing Thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233)
[22:51:21] [TAB Processing Thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:194)
[22:51:21] [TAB Processing Thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:164)
[22:51:21] [TAB Processing Thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1683)
[22:51:21] [TAB Processing Thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1656)
[22:51:21] [TAB Processing Thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:51:21] [TAB Processing Thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:51:21] [TAB Processing Thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:51:21] [TAB Processing Thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[22:51:21] [TAB Processing Thread/WARN]: 	at me.neznamy.tab.platforms.bukkit.nms.PacketSender.lambda$new$0(PacketSender.java:41)
[22:51:21] [TAB Processing Thread/WARN]: 	at me.neznamy.tab.platforms.bukkit.nms.PacketSender.sendPacket(PacketSender.java:56)
[22:51:21] [TAB Processing Thread/WARN]: 	at me.neznamy.tab.platforms.bukkit.tablist.PacketTabList18.updateDisplayName(PacketTabList18.java:120)
[22:51:21] [TAB Processing Thread/WARN]: 	at me.neznamy.tab.shared.platform.decorators.TrackedTabList.updateDisplayName(TrackedTabList.java:38)
[22:51:21] [TAB Processing Thread/WARN]: 	at me.neznamy.tab.shared.features.playerlist.PlayerList.updatePlayer(PlayerList.java:130)
[22:51:21] [TAB Processing Thread/WARN]: 	at me.neznamy.tab.shared.features.playerlist.PlayerList.onJoin(PlayerList.java:270)
[22:51:21] [TAB Processing Thread/WARN]: 	at me.neznamy.tab.shared.FeatureManager.lambda$onJoin$4(FeatureManager.java:191)
[22:51:21] [TAB Processing Thread/WARN]: 	at me.neznamy.tab.shared.cpu.TimedCaughtTask.run(TimedCaughtTask.java:28)
[22:51:21] [TAB Processing Thread/WARN]: 	at me.neznamy.tab.shared.FeatureManager.onJoin(FeatureManager.java:197)
[22:51:21] [TAB Processing Thread/WARN]: 	at me.neznamy.tab.shared.platform.EventListener.lambda$join$0(EventListener.java:28)
[22:51:21] [TAB Processing Thread/WARN]: 	at me.neznamy.tab.shared.cpu.CaughtTask.run(CaughtTask.java:18)
[22:51:21] [TAB Processing Thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[22:51:21] [TAB Processing Thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[22:51:21] [TAB Processing Thread/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[22:51:21] [TAB Processing Thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[22:51:21] [TAB Processing Thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[22:51:21] [TAB Processing Thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
[22:51:21] [TAB Processing Thread/WARN]: [PremiumVanish] Please include this information
[22:51:21] [TAB Processing Thread/WARN]: [PremiumVanish] if you report the issue.
```

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Report this to PV.
