### ISSUE TITLE
Tab 2.7.5

### ISSUE THREAD

**Issue by x1p** [NEZNAMY/TAB#154]
**Server version**
Paper 1.15.2

**Plugin version** ("latest" is not a version)
2.7.5 (premium)

**Describe the bug**
```
24.05.2020 - 20:27:25 - [TAB v2.7.5 Premium] An error occurred when refreshing header/footer
24.05.2020 - 20:27:25 - java.lang.NullPointerException: null
24.05.2020 - 20:27:25 -        at me.neznamy.tab.shared.CPUManager.addTime(CPUManager.java:151)
24.05.2020 - 20:27:25 -        at me.neznamy.tab.shared.CPUManager$4.run(CPUManager.java:89)
24.05.2020 - 20:27:25 -        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
24.05.2020 - 20:27:25 -        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
24.05.2020 - 20:27:25 -        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
24.05.2020 - 20:27:25 -        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
24.05.2020 - 20:27:25 -        at java.base/java.lang.Thread.run(Thread.java:834)
```
Does not happen with 2.7.5 pre 13

**How to reproduce**
- Place plugin on a test server
- Remove all TAB folders
- Restart server

**Expected behavior**
No errors

**Actual behavior**
Error file being filled

**Additional info** (errors, screenshots, ...)
-

**Comment by NEZNAMY** [comment]
Is the error spamming or more like one-time ?

**Comment by x1p** [comment]
Exactly 3 times

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/blob/master/src/me/neznamy/tab/shared/CPUManager.java#L151 there's even a check line before.

**Comment by x1p** [comment]
Second attempt after cleaning the folder entirely:
```
24.05.2020 - 21:13:02 - [TAB v2.7.5 Premium] An error occurred when setting placeholder %animation:Welcome% for Mammut10
24.05.2020 - 21:13:02 - java.lang.NullPointerException: null
24.05.2020 - 21:13:02 -        at me.neznamy.tab.shared.CPUManager.addTime(CPUManager.java:151)
24.05.2020 - 21:13:02 -        at me.neznamy.tab.shared.placeholders.ServerPlaceholder.getValue(ServerPlaceholder.java:26)
24.05.2020 - 21:13:02 -        at me.neznamy.tab.shared.placeholders.Placeholder.set(Placeholder.java:38)
24.05.2020 - 21:13:02 -        at me.neznamy.tab.shared.Property.isUpdateNeeded(Property.java:98)
24.05.2020 - 21:13:02 -        at me.neznamy.tab.shared.features.HeaderFooter.refreshHeaderFooter(HeaderFooter.java:53)
24.05.2020 - 21:13:02 -        at me.neznamy.tab.shared.features.HeaderFooter$1.run(HeaderFooter.java:21)
24.05.2020 - 21:13:02 -        at me.neznamy.tab.shared.CPUManager$4.run(CPUManager.java:88)
24.05.2020 - 21:13:02 -        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
24.05.2020 - 21:13:02 -        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
24.05.2020 - 21:13:02 -        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
24.05.2020 - 21:13:02 -        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
24.05.2020 - 21:13:02 -        at java.base/java.lang.Thread.run(Thread.java:834)
24.05.2020 - 21:13:04 - [TAB v2.7.5 Premium] An error occurred when setting placeholder %health% for Mammut10
24.05.2020 - 21:13:04 - java.lang.NullPointerException: null
24.05.2020 - 21:13:04 -        at me.neznamy.tab.shared.CPUManager.addTime(CPUManager.java:151)
24.05.2020 - 21:13:04 -        at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.getValue(PlayerPlaceholder.java:30)
24.05.2020 - 21:13:04 -        at me.neznamy.tab.shared.placeholders.Placeholder.set(Placeholder.java:38)
24.05.2020 - 21:13:04 -        at me.neznamy.tab.shared.Property.isUpdateNeeded(Property.java:98)
24.05.2020 - 21:13:04 -        at me.neznamy.tab.shared.features.BelowName$1.run(BelowName.java:33)
24.05.2020 - 21:13:04 -        at me.neznamy.tab.shared.CPUManager$4.run(CPUManager.java:88)
24.05.2020 - 21:13:04 -        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
24.05.2020 - 21:13:04 -        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
24.05.2020 - 21:13:04 -        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
24.05.2020 - 21:13:04 -        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
24.05.2020 - 21:13:04 -        at java.base/java.lang.Thread.run(Thread.java:834)
24.05.2020 - 21:13:04 - [TAB v2.7.5 Premium] Value "%health%" used in BelowName still has unparsed placeholders! Did you forget to download an expansion ?
```

**Comment by NEZNAMY** [comment]
Can you message me on discord ? I'll send you a jar to test.

**Comment by NEZNAMY** [comment]
Hotfixed.
