### ISSUE TITLE
Minecraft Louncher spam a error when plugin is installed in the server.

### ISSUE THREAD

**Issue by Jozznak** [NEZNAMY/TAB#175]
**Server version**
PaperSpigot 1.12 (Paper-1618)
Using ViaVersion to accept from 1.9 -1.5
Bug happens with players that are in any version accepted

**Plugin version** ("latest" is not a version)
2.7.7

**Describe the bug**
Players get a crash error in the louncher every time they log in and spams.

**How to reproduce**
I deleted all the config and started fresh. The error still happens. 

**Additional info** (errors, screenshots, ...)
```
[20:19:55] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
    at dnp.a(SourceFile:1789) ~[minecraft-1.15.2-client.jar:?]
    at mw.a(SourceFile:65) ~[minecraft-1.15.2-client.jar:?]
    at mw.a(SourceFile:10) ~[minecraft-1.15.2-client.jar:?]
    at lv.a(SourceFile:21) ~[minecraft-1.15.2-client.jar:?]
    at ais.c(SourceFile:144) [minecraft-1.15.2-client.jar:?]
    at aiw.c(SourceFile:23) [minecraft-1.15.2-client.jar:?]
    at ais.w(SourceFile:118) [minecraft-1.15.2-client.jar:?]
    at ais.bk(SourceFile:103) [minecraft-1.15.2-client.jar:?]
    at dbn.d(SourceFile:956) [minecraft-1.15.2-client.jar:?]
    at dbn.d(SourceFile:619) [minecraft-1.15.2-client.jar:?]
    at net.minecraft.client.main.Main.main(SourceFile:204) [minecraft-1.15.2-client.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by Tanguygab** [comment]
Try with the official minecraft launcher

**Comment by Jozznak** [comment]
I used the official minecraft Louncher

**Comment by Tanguygab** [comment]
you are not, I see MultiMC in the error

**Comment by Jozznak** [comment]
```
Error executing task on Client
java.lang.NullPointerException
	at cwl.d(SourceFile:199)
	at dnp.a(SourceFile:2117)
	at os.a(SourceFile:122)
	at os.a(SourceFile:16)
	at lv.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33)
	at lv$$Lambda$2431/1241590322.run(Unknown Source)
	at ais.c(ThreadTaskExecutor.java:173)
	at aiw.c(SourceFile:23)
	at ais.w(ThreadTaskExecutor.java:135)
	at ais.bk(ThreadTaskExecutor.java:115)
	at dbn.d(SourceFile:956)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
```

**Comment by Tanguygab** [comment]
can you try without TAB?

**Comment by Jozznak** [comment]
I did. And no error happends, Thats why i'm reporting it. I am complete sure is a TAB issue.

**Comment by NEZNAMY** [comment]
try adding `safe-team-register: false` into your config.yml

**Comment by Jozznak** [comment]
This crash shows up every time a player joins the server. It creates a crash for him and for me

```
Error executing task on Client
java.lang.NullPointerException
	at cwl.d(SourceFile:199)
	at dnp.a(SourceFile:2117)
	at os.a(SourceFile:122)
	at os.a(SourceFile:16)
	at lv.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33)
	at lv$$Lambda$2431/1241590322.run(Unknown Source)
	at ais.c(ThreadTaskExecutor.java:173)
	at aiw.c(SourceFile:23)
	at ais.w(ThreadTaskExecutor.java:135)
	at ais.bk(ThreadTaskExecutor.java:115)
	at dbn.d(SourceFile:956)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[CHAT] > ★Jozznak Join <
Error executing task on Client
java.lang.NullPointerException
	at cwl.d(SourceFile:199)
	at dnp.a(SourceFile:2117)
	at os.a(SourceFile:122)
	at os.a(SourceFile:16)
	at lv.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33)
	at lv$$Lambda$2431/1241590322.run(Unknown Source)
	at ais.c(ThreadTaskExecutor.java:173)
	at aiw.c(SourceFile:23)
	at ais.w(ThreadTaskExecutor.java:135)
	at ais.bk(ThreadTaskExecutor.java:115)
	at dbn.d(SourceFile:956)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[CHAT] > ★eUipKh join <
```

**Comment by NEZNAMY** [comment]
Try adding that option. How is this a crash though? It's just an error.

**Comment by Jozznak** [comment]
> safe-team-register: false

This worked

> Try adding that option. How is this a crash though? It's just an error.

Sorry I ment error. Sorry about that.

By the way, there is a bug with the "classic-vanilla-belowname"
When its true, it also dispolay on NPC, an as the other option "unlimited-tag" has the problem is the stand desapearing on death, I can use that.

**Comment by NEZNAMY** [comment]
Not a bug https://github.com/NEZNAMY/TAB/wiki/Limitations#belowname

**Comment by Jozznak** [comment]
> Not a bug https://github.com/NEZNAMY/TAB/wiki/Limitations#belowname

Oh thx, hope you can solve the other issue then. And thx for the quick aswers!

**Comment by NEZNAMY** [comment]
What is the other issue? I sent you the config option to use.

**Comment by Jozznak** [comment]
This one: https://github.com/NEZNAMY/TAB/issues/173#issue-642442913

The error in the louncher is now fixed with the `safe-team-register: false`, so you can put the post in solved.
Thank you again!

**Comment by NEZNAMY** [comment]
The other issue has been noted just like all the other unlimited nametag mode bugs.
