### ISSUE TITLE
1.7.X client crashes when changing servers on BungeeCord

### ISSUE THREAD

**Issue by Foulest** [NEZNAMY/TAB#191]
**Server version**
SSBungeeCord, BreadSpigot (1.8.8)

**Plugin version** ("latest" is not a version)
2.8.2

**Describe the bug**
When a client on 1.7.10 (ViaVersion, ViaRewind on the proxy) joins a server coming from another one (lobby to factions, lets say) their client crashes and this is pasted in the console: https://pastebin.com/raw/CxBaY37Z
Bug was experienced on Lunar Client. Haven't tested if it happens on other versions.

**Comment by NEZNAMY** [comment]
Try latest version, it should have less crashes. Is TAB installed (and enabled) on bungeecord only?

**Comment by Seanoo1** [comment]
I have same issue too. I'm using travertine bungee and 1.7.x~1.8.x paperspigot. I'm using latest build on spigot.

**Comment by NEZNAMY** [comment]
So you don't have TAB on bungee?

**Comment by Seanoo1** [comment]
I installed TAB on bungee.
If your meaning right now, I don't have on bungee right now.

**Comment by NEZNAMY** [comment]
So where do you have it? This is confusing.

**Comment by Seanoo1** [comment]
I installed only on travertine bungee.

**Comment by NEZNAMY** [comment]
Then it should not crash with this message on latest plugin version.

**Comment by Seanoo1** [comment]
wait a second, I will post my error log

**Comment by Seanoo1** [comment]
This is the error when I try to join with 1.7.x

io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at me.neznamy.tab.platforms.bungee.Main$2.write(Main.java:200) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
	at net.md_5.bungee.protocol.DefinedPacket.writeString(DefinedPacket.java:19) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at net.md_5.bungee.protocol.packet.PlayerListItem.v17Write(PlayerListItem.java:94) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.github.waterfallmc.travertine.protocol.MultiVersionPacketV17.write0(MultiVersionPacketV17.java:44) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:24) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[travertine-154.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
	... 15 more
[19:40:24] [Netty Worker IO Thread #0/INFO]: [test] disconnected with: EncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToByteEncoder:125
[19:40:24] [Netty Worker IO Thread #0/INFO]: [/127.0.0.1:51511|test] -> UpstreamBridge has disconnected
[19:40:24] [Netty Worker IO Thread #0/INFO]: [/127.0.0.1:51511|test] <-> DownstreamBridge <-> [lobby] has disconnected

**Comment by NEZNAMY** [comment]
Can you disable features one by one to find which one causes this?

**Comment by Foulest** [comment]
I'm actually using the latest version of TAB and the error occurs.

**Comment by NEZNAMY** [comment]
Oh it's two different people. So the original message is still present? What is your setup?

**Comment by Foulest** [comment]
SSBungeeCord, BreadSpigot (1.8.8)

Tab is on all servers in bukkit bridge mode, and on BungeeCord.

**Comment by NEZNAMY** [comment]
Are you sure you didn't forget to enable it somewhere? Alternatively remove it from the bukkit servers if it keeps crashing.

**Comment by Foulest** [comment]
Removing it from the bukkit servers is counter-intuitive.
A fix for a plugin bug isn't removing the plugin. I want to use TAB's features on all of my servers.

**Comment by Foulest** [comment]
Also, I have no clue who the other guy is, but my issue is different than his.
Refer to the top post.

**Comment by NEZNAMY** [comment]
Removing the plugin isn't a fix, but can help to find the bug. Right now the issue can be anywhere in the 500kb of code which is too much to go through. Finding the exact feature will help a ton.

**Comment by NEZNAMY** [comment]
@Seanoo1 join discord i will send you a fixed build.

**Comment by NEZNAMY** [comment]
@Foulest I was not able to reproduce your specific issue, but fixed other ones on 1.7, cna you join discord? I will send you a jar to test.

**Comment by Foulest** [comment]
Seems to be fixed. There's a new issue.
Check it out here: https://github.com/ViaVersion/ViaRewind/issues/191
