### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Axerr0** [NEZNAMY/TAB#192]
**Server version**
[01:08:48 INFO]: This server is running Paper version git-Paper-130 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Plugin version** ("latest" is not a version)
2.8.3

**Describe the bug**
Im getting stacktrace every 1 second :)

**How to reproduce**
Idk

**Expected behavior**
No stacktrace?

**Actual behavior**
Stacktrace

**Additional info** (errors, screenshots, ...)
```[01:10:49 ERROR]: java.lang.NullPointerException
[01:10:49 WARN]: java.lang.NullPointerException
[01:10:49 WARN]:        at net.minecraft.server.v1_16_R1.PacketDataSerializer.a(PacketDataSerializer.java:203)
[01:10:49 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayOutChat.b(PacketPlayOutChat.java:45)
[01:10:49 WARN]:        at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:42)
[01:10:49 WARN]:        at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:12)
[01:10:49 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
[01:10:49 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:10:49 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[01:10:49 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
[01:10:49 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[01:10:49 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
[01:10:49 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[01:10:49 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[01:10:49 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[01:10:49 WARN]:        at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:99)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[01:10:49 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[01:10:49 WARN]:        at su.fogus.engine.nms.packets.PacketManager$1.write(PacketManager.java:107)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[01:10:49 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[01:10:49 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[01:10:49 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[01:10:49 WARN]:        at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
[01:10:49 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[01:10:49 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[01:10:49 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[01:10:49 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[01:10:49 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[01:10:49 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:10:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by NEZNAMY** [comment]
Not caused by TAB. Remove it and it will keep happening.

**Comment by Axerr0** [comment]
So, how to fix it?

**Comment by NEZNAMY** [comment]
Find out which plugin is causing it and remove/update it.
