### ISSUE TITLE
Players get disconnected randomly

### ISSUE THREAD

**Issue by FastJoe0** [NEZNAMY/TAB#219]
Server version: Paper version git-Paper-204 (MC: 1.16.3)
Plugin version: 2.8.7

Players get disconnected randomly with no reason. Logs: 
```
[11:02:33] [Netty Epoll Server IO #0/ERROR]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[11:02:33] [Netty Epoll Server IO #0/WARN]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_16_R2.PacketDataSerializer.a(PacketDataSerializer.java:240)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayOutMapChunk.b(PacketPlayOutMapChunk.java:146)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_16_R2.PacketEncoder.encode(PacketEncoder.java:42)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_16_R2.PacketEncoder.encode(PacketEncoder.java:12)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:75)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_16_R2.NetworkManager.lambda$b$6(NetworkManager.java:300)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_16_R2.NetworkManager$$Lambda$4031/0000000000000000.run(Unknown Source)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:836)
[11:02:33] [Netty Epoll Server IO #0/WARN]: Caused by: java.lang.NullPointerException
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagLongArray.write(SourceFile:76)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.a(NBTTagCompound.java:454)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.write(NBTTagCompound.java:92)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:163)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:156)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_16_R2.PacketDataSerializer.a(PacketDataSerializer.java:238)
[11:02:33] [Netty Epoll Server IO #0/WARN]: 	... 24 more
[11:02:33] [Server thread/INFO]: Lebro2 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

```

**Comment by NEZNAMY** [comment]
Not caused by TAB. It doesn't send chunk packets.

**Comment by NEZNAMY** [comment]
@FastJoe0 did it happen without TAB as well?
