### ISSUE TITLE
Error when i want to set skin

### ISSUE THREAD

**Issue by LevM-A** [NEZNAMY/TAB#239]
[17:28:45 INFO]: Crazy_LeV issued server command: /skin 5opka
[17:28:45 WARN]: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[17:28:45 WARN]:        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[17:28:45 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:325)
[17:28:45 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:268)
[17:28:45 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
[17:28:45 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:645)
[17:28:45 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:464)
[17:28:45 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
[17:28:45 WARN]:        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[17:28:45 WARN]:        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:445)
[17:28:45 WARN]:        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:423)
[17:28:45 WARN]:        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
[17:28:45 WARN]:        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
[17:28:45 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1475)
[17:28:45 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1381)
[17:28:45 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441)
[17:28:45 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
[17:28:45 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
[17:28:45 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:171)
[17:28:45 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1600)
[17:28:45 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
[17:28:45 WARN]:        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
[17:28:45 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
[17:28:45 WARN]:        at eu.blackfire62.myskin.shared.util.MojangAPI.readURL(MojangAPI.java:70)
[17:28:45 WARN]:        at eu.blackfire62.myskin.shared.util.MojangAPI.getSkinProperty(MojangAPI.java:40)
[17:28:45 WARN]:        at eu.blackfire62.myskin.bukkit.command.SkinCommand$1.run(SkinCommand.java:132)
[17:28:45 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[17:28:45 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[17:28:45 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:28:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[17:28:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[17:28:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:851)
[17:28:45 WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[17:28:45 WARN]:        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
[17:28:45 WARN]:        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
[17:28:45 WARN]:        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
[17:28:45 WARN]:        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[17:28:45 WARN]:        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
[17:28:45 WARN]:        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:629)
[17:28:45 WARN]:        ... 26 more
[17:28:45 WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[17:28:45 WARN]:        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
[17:28:45 WARN]:        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
[17:28:45 WARN]:        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
[17:28:45 WARN]:        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
[17:28:45 WARN]:        ... 31 more

**Comment by Tanguygab** [comment]
what does it have to do with TAB?

**Comment by LevM-A** [comment]
becouse MySkin dont have github and i write here

**Comment by Tanguygab** [comment]
oh ok, but I don't think it should be reported here anyways. Paste the error on Hastebin and put the link in MySkin's spigot thread

**Comment by NEZNAMY** [comment]
Please don't use TAB's github for other plugins.

**Comment by LevM-A** [comment]
oh ok im sorry but you owner plugin MySkin,yes.
If yes can you give me link where i can report about this bug?

**Comment by NEZNAMY** [comment]
I am not. A friend is who abandoned it and transferred it to my account without my permission.

**Comment by LevM-A** [comment]
oh ok, again im sorry
