### ISSUE TITLE
Tab won't work when it comes to creating ranks for names for Thermos 1.7.10

### ISSUE THREAD

**Issue by anniemoar** [NEZNAMY/TAB#257]
[08:30:45] [Server thread/INFO]: [TAB] Enabling TAB v2.8.9
[08:30:45] [Server thread/INFO]: [TAB] Server version: 1.7.10 (v1_7_R4)
[08:30:45] [Server thread/WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/IChatBaseComponent
[08:30:45] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[08:30:45] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[08:30:45] [Server thread/WARN]: 	at me.neznamy.tab.platforms.bukkit.nms.PacketPlayOut.getNMSClass(PacketPlayOut.java:47)
[08:30:45] [Server thread/WARN]: 	at me.neznamy.tab.platforms.bukkit.nms.NMSHook.checkCompatibility(NMSHook.java:112)
[08:30:45] [Server thread/WARN]: 	at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:31)
[08:30:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[08:30:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[08:30:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[08:30:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
[08:30:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
[08:30:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
[08:30:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
[08:30:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
[08:30:45] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[08:30:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[08:30:45] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by NEZNAMY** [comment]
Thermos is not supported http://prntscr.com/w8rccq .
