### ISSUE TITLE
TAB disabling on start and telling me to report the error.

### ISSUE THREAD

**Issue by KillsT3aler69** [NEZNAMY/TAB#274]
**Server version**
1.12.2

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
When I try to start the server with the TAB plugin the following error appears and it automaticly disables the TAB plugin.

**How to reproduce**
Just start the server with TAB installed onto in and look into the config.

**Expected behavior**
It should initialize and enable TAB.

**Actual behavior**
It replies with an error and disables TAB.

**Additional info** (errors, screenshots, ...)
[22:52:40] [Server thread/INFO] []: [TAB] Server version: 1.12.2 (v1_12_R1)
[22:52:40] [Server thread/INFO] []: [TAB] Your server version is marked as compatible, but a compatibility issue was found. Please report the error below (include your server version & fork too)
[22:52:40] [Server thread/WARN] []: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.IChatBaseComponent
[22:52:40] [Server thread/WARN] []:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[22:52:40] [Server thread/WARN] []:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:99)
[22:52:40] [Server thread/WARN] []:     at java.lang.ClassLoader.loadClass(Unknown Source)
[22:52:40] [Server thread/WARN] []:     at java.lang.ClassLoader.loadClass(Unknown Source)
[22:52:40] [Server thread/WARN] []:     at java.lang.Class.forName0(Native Method)
[22:52:40] [Server thread/WARN] []:     at java.lang.Class.forName(Unknown Source)
[22:52:40] [Server thread/WARN] []:     at me.neznamy.tab.platforms.bukkit.nms.PacketPlayOut.getNMSClass(PacketPlayOut.java:47)
[22:52:40] [Server thread/WARN] []:     at me.neznamy.tab.platforms.bukkit.nms.NMSHook.isVersionSupported(NMSHook.java:114)
[22:52:40] [Server thread/WARN] []:     at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:21)
[22:52:40] [Server thread/WARN] []:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256)
[22:52:40] [Server thread/WARN] []:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[22:52:40] [Server thread/WARN] []:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[22:52:40] [Server thread/WARN] []:     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:420)
[22:52:40] [Server thread/WARN] []:     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:379)
[22:52:40] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:540)
[22:52:40] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:501)
[22:52:40] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:457)
[22:52:40] [Server thread/WARN] []:     at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
[22:52:40] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[22:52:40] [Server thread/WARN] []:     at java.lang.Thread.run(Unknown Source)
[22:52:40] [Server thread/INFO] [me.neznamy.tab.platforms.bukkit.Main]: [TAB] Disabling TAB v2.8.10

**Comment by NEZNAMY** [comment]
"(include your server version & fork too)"
You forgot to do it.

**Comment by NEZNAMY** [comment]
@KillsT3aler69 any news? Otherwise I will close this as an attempt to run it on officially unsupported modded servers.

**Comment by NEZNAMY** [comment]
Stack proves it's an unsupported fork which cannot be added support for.
