### ISSUE TITLE
Thermos 1.7.10 Startup error

### ISSUE THREAD

**Issue by toastontoast** [NEZNAMY/TAB#285]
**Since i am running a 1.7.10 Thermos Hybrid server which is very old and outdated** i doubt this will be valid but its worth a try anyway. When starting the Tab plugin up with a modified CrazyCraft3 Modpack its returns with this error:

`[00:53:33] [Server thread/INFO]: [TAB] Enabling TAB v2.8.10
[00:53:33] [Server thread/INFO]: [TAB] Server version: 1.7.10 (v1_7_R4)
[00:53:33] [Server thread/INFO]: [TAB] Your server version is marked as compatible, but a compatibility issue was found. Please report the error below (include your server version & fork too)
[00:53:33] [Server thread/WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/IChatBaseComponent
[00:53:33] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[00:53:33] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[00:53:33] [Server thread/WARN]: 	at me.neznamy.tab.platforms.bukkit.nms.PacketPlayOut.getNMSClass(PacketPlayOut.java:47)
[00:53:33] [Server thread/WARN]: 	at me.neznamy.tab.platforms.bukkit.nms.NMSHook.isVersionSupported(NMSHook.java:114)
[00:53:33] [Server thread/WARN]: 	at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:21)
[00:53:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[00:53:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[00:53:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[00:53:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
[00:53:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
[00:53:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
[00:53:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
[00:53:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
[00:53:33] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[00:53:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[00:53:33] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[00:53:33] [Server thread/INFO]: [TAB] Disabling TAB v2.8.10`

I am running MC version 1.7.10 and Thermos version Build 58 (ALPHA).
If this cant be fixed, no worries its understandable.

Edit: Pastebin link for better formatting: [https://pastebin.com/cwK1L293](https://pastebin.com/cwK1L293)

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/releases
http://prntscr.com/10q0y0t
??

**Comment by toastontoast** [comment]
Pr7 Worked perfectly. Thanks
