### ISSUE TITLE
KCauldron compatibility

### ISSUE THREAD

**Issue by Tomut0** [NEZNAMY/TAB#289]
**Server version**
KCauldron 1.7.10

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
There is error, when you trying to run a server.

**How to reproduce**
Start a server.

**Expected behavior**
Just load the plugin.

**Actual behavior**
Error ;c

**Additional info** (errors, screenshots, ...)
```
> [03:11:43 INFO]: [TAB] Enabling TAB v2.8.10
> [03:11:43 INFO]: [TAB] Server version: 1.7.10 (v1_7_R4)
> [03:11:43 INFO]: [TAB] Your server version is marked as compatible, but a compatibility issue was found. Please report the error below (include your server version & fork too)
> [03:11:43 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/IChatBaseComponent
> [03:11:43 WARN]: at java.lang.Class.forName0(Native Method)
> [03:11:43 WARN]: at java.lang.Class.forName(Class.java:264)
> [03:11:43 WARN]: at me.neznamy.tab.platforms.bukkit.nms.PacketPlayOut.getNMSClass(PacketPlayOut.java:47)
> [03:11:43 WARN]: at me.neznamy.tab.platforms.bukkit.nms.NMSHook.isVersionSupported(NMSHook.java:114)
> [03:11:43 WARN]: at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:21)
> [03:11:43 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
> [03:11:43 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
> [03:11:43 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
> [03:11:43 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
> [03:11:43 WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
> [03:11:43 WARN]: at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
> [03:11:43 WARN]: at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
> [03:11:43 WARN]: at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
> [03:11:43 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
> [03:11:43 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
> [03:11:43 WARN]: at java.lang.Thread.run(Thread.java:748)
> [03:11:43 INFO]: [TAB] Disabling TAB v2.8.10
```

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/releases/tag/2.8.11-pre5

**Comment by Tomut0** [comment]
> 
> 
> https://github.com/NEZNAMY/TAB/releases/tag/2.8.11-pre5

Oh, good job!
