### ISSUE TITLE
1.7.10 Error java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/IChatBaseComponent

### ISSUE THREAD

**Issue by KaneHart** [NEZNAMY/TAB#319]
**Server version**
1.7.10

**Plugin version** ("latest" is not a version)
latest ;) 2.8.10

**Describe the bug**
`[00:06:39] [Server thread/INFO]: [TAB] Enabling TAB v2.8.10
[00:06:39] [Server thread/INFO]: [0;37;22m[TAB] Server version: 1.7.10 (v1_7_R4)[m
[00:06:39] [Server thread/INFO]: [0;31;1m[TAB] Your server version is marked as compatible, but a compatibility issue was found. Please report the error below (include your server version & fork too)[m
[00:06:39] [Server thread/WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/IChatBaseComponent
[00:06:39] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[00:06:39] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[00:06:39] [Server thread/WARN]: 	at me.neznamy.tab.platforms.bukkit.nms.PacketPlayOut.getNMSClass(PacketPlayOut.java:47)
[00:06:39] [Server thread/WARN]: 	at me.neznamy.tab.platforms.bukkit.nms.NMSHook.isVersionSupported(NMSHook.java:114)
[00:06:39] [Server thread/WARN]: 	at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:21)
[00:06:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[00:06:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:362)
[00:06:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:409)
[00:06:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:402)
[00:06:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:336)
[00:06:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:514)
[00:06:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:488)
[00:06:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:448)
[00:06:39] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[00:06:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642)
[00:06:39] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

**How to reproduce**
1.7.10 Minecraft Server ;) Bukkit!

**Expected behavior**
It to load up and run!

**Actual behavior**
Plugin disabled with the above error.

**Additional info** (errors, screenshots, ...)

**Comment by MrGraycat** [comment]
Hello

Is this just bukkit or some wierd fork?
If it's a fork please link it

Thanks

**Comment by KaneHart** [comment]
Ahh sorry yeah it's Crucible in the past known as Thermos.

https://github.com/CrucibleMC/Crucible

**Comment by MrGraycat** [comment]
Use the pre release it added support for these modded forks
https://github.com/NEZNAMY/TAB/releases

**Comment by KaneHart** [comment]
Thank you and confirmed working. I saw another post on it but I thought you had releases since then so I assumed sadly. My mistake and thank you for the quick reply.
