### ISSUE TITLE
[HolographicDisplays conflict] Exception Async entity get

### ISSUE THREAD

**Issue by Official-DenBeKKer** [NEZNAMY/TAB#330]
CraftBukkit version 3147-Spigot-9472b09-d7ef1e9 (MC: 1.17)
TAB Plugin version 2.9.1

HolographicDisplays Exception on teleport (Living entity spawn i think, async packet send)

Look at
https://github.com/filoghost/HolographicDisplays/issues/475#issuecomment-864139765

**Comment by Official-DenBeKKer** [comment]
```[14:16:31] [pool-19-thread-18/ERROR]: [HolographicDisplays] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:1795) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.server.level.WorldServer.getEntity(WorldServer.java:1306) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.NmsManagerImpl.getNMSEntityBaseFromID(NmsManagerImpl.java:139) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getNMSEntityBase(ProtocolLibHookImpl.java:308) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getHologramLine(ProtocolLibHookImpl.java:299) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getHologramLine(ProtocolLibHookImpl.java:291) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.access$000(ProtocolLibHookImpl.java:55) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:139) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.network.NetworkManager.b(NetworkManager.java:203) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:183) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1708) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at net.minecraft.server.network.PlayerConnection.sendPacket(PlayerConnection.java:1694) ~[spigot.jar:3147-Spigot-9472b09-d7ef1e9]
        at jdk.internal.reflect.GeneratedMethodAccessor32.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at me.neznamy.tab.platforms.bukkit.BukkitTabPlayer.sendPacket(BukkitTabPlayer.java:150) ~[TAB%20v2.9.1.jar:?]
        at me.neznamy.tab.shared.ITabPlayer.sendPacket(ITabPlayer.java:538) ~[TAB%20v2.9.1.jar:?]
        at me.neznamy.tab.platforms.bukkit.features.unlimitedtags.BukkitArmorStand.spawn(BukkitArmorStand.java:139) ~[TAB%20v2.9.1.jar:?]
        at me.neznamy.tab.platforms.bukkit.features.unlimitedtags.BukkitArmorStand.lambda$sneak$0(BukkitArmorStand.java:185) ~[TAB%20v2.9.1.jar:?]
        at me.neznamy.tab.platforms.bukkit.features.unlimitedtags.BukkitArmorStand.sneak(BukkitArmorStand.java:190) ~[TAB%20v2.9.1.jar:?]
        at me.neznamy.tab.api.ArmorStandManager.lambda$sneak$1(ArmorStandManager.java:52) ~[TAB%20v2.9.1.jar:?]
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2093) ~[?:?]
        at me.neznamy.tab.api.ArmorStandManager.sneak(ArmorStandManager.java:52) ~[TAB%20v2.9.1.jar:?]
        at me.neznamy.tab.platforms.bukkit.features.unlimitedtags.EventListener.lambda$onSneak$0(EventListener.java:39) ~[TAB%20v2.9.1.jar:?]
        at me.neznamy.tab.shared.cpu.CPUManager$2.run(CPUManager.java:116) [TAB%20v2.9.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]```

**Comment by NEZNAMY** [comment]
Add a try/catch or something. I will not move the plugin to the main thread and drop everyone's TPS.

**Comment by Official-DenBeKKer** [comment]
But on 1.16 this exception was not appears

**Comment by NEZNAMY** [comment]
I still insist on what I said.
