### ISSUE TITLE
How can we put the server version the player is playing in next to their name in tab?

### ISSUE THREAD

**Issue by ZayanPlayz** [NEZNAMY/TAB#335]
![image](https://user-images.githubusercontent.com/78526458/123050582-e9faea80-d411-11eb-8313-4aeca5048927.png)
I want it to be like this. Anyone knows how to do it?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Mini-guides-collection#showing-player-version-in-tablist

**Comment by ZayanPlayz** [comment]
Hey, so when I did that it worked but the rank of the player was gone. I am using power ranks. I want the rank to be there also the version placeholder

**Comment by NEZNAMY** [comment]
Then use both rank placeholder and version placeholder in suffix.

**Comment by ZayanPlayz** [comment]
how can you show how?

**Comment by NEZNAMY** [comment]
Just put whatever you had there before, for example tabprefix: "%vault-suffix% %player-version%".

**Comment by ZayanPlayz** [comment]
Now I am getting this log error

**Comment by ZayanPlayz** [comment]
[12:16:13 WARN]: java.util.UnknownFormatConversionException: Conversion = 'p'
[12:16:13 WARN]: 	at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:105)
[12:16:13 WARN]: 	at nl.svenar.PowerRanks.Events.OnChat.onPlayerChat(OnChat.java:159)
[12:16:13 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor7.execute(Unknown Source)
[12:16:13 WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:16:13 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[12:16:13 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:16:13 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[12:16:13 WARN]: 	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:234)
[12:16:13 WARN]: 	at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:116)
[12:16:13 WARN]: 	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:65)
[12:16:13 WARN]: 	at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2102)
[12:16:13 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2013)
[12:16:13 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1979)
[12:16:13 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat$1.run(PacketPlayInChat.java:40)
[12:16:13 WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[12:16:13 WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[12:16:13 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[12:16:13 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[12:16:13 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by NEZNAMY** [comment]
The error message says powerranks. Send it to it's author.

**Comment by ZayanPlayz** [comment]
so what should i do

**Comment by NEZNAMY** [comment]
Read my message above yours.

**Comment by ZayanPlayz** [comment]
i still don't understand?????

**Comment by NEZNAMY** [comment]
> The error message says powerranks. Send it to it's author.

**Comment by ZayanPlayz** [comment]
how do i fix then

**Comment by NEZNAMY** [comment]
Send it to powerranks author.

**Comment by ZayanPlayz** [comment]
otherwise, can you tell them how to create ranks and give permissions?

**Comment by NEZNAMY** [comment]
I don't know I didn't make that plugin.

**Comment by ZayanPlayz** [comment]
otherwise, can you tell me how to create a rank and give to people and give permissions in the tab plugin itself?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-assign-players-into-groups

**Comment by ZayanPlayz** [comment]
IDK how to add perms and give ranks can you just give the commands over here?

**Comment by NEZNAMY** [comment]
The commands must be ran in powerranks which I don't know how to do because I didn't make it.

**Comment by ZayanPlayz** [comment]
k

**Comment by ZayanPlayz** [comment]
the health thing doesn't come under players nametag how to fix it?
![image](https://user-images.githubusercontent.com/78526458/123074650-8cbe6380-d428-11eb-9288-3ff38a5eab85.png)

Config: https://paste.gg/p/anonymous/45a81075ec7446cbad8d35a42fc1467c

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-info

**Comment by ZayanPlayz** [comment]
can you tell me what should i do instead of giving GitHub links -_-

**Comment by NEZNAMY** [comment]
Additional info
#1 This feature makes nametag invisible so it can display armor stands instead. Visibility rule also applies to Vanilla belowname, making it not display. In that case, you can just disable it as you won't see it anyway. To restore the visual, run /tab group _OTHER_ belowname %health% Health.

**Comment by ZayanPlayz** [comment]
and also I want the player rank to come up in name tag know how to do that?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Mini-guides-collection#taking-prefixessuffixes-from-permission-plugin

**Comment by ZayanPlayz** [comment]
Thanks for the help dude
