### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by Ad-973** [NEZNAMY/TAB#349]
**Server version**
CatServer-83bb041-universal.jar

**Plugin version** ("latest" is not a version)
v2.9.2

**Describe the bug**
A bug occurred during loading.

**How to reproduce**
No

**Expected behavior**
No

**Actual behavior**
No

**Additional info** (errors, screenshots, ...)

[14:31:31] [Server thread/WARN]: java.lang.NoSuchMethodException: No method found with possible names [setNameTagVisibility, a] in class net.minecraft.scoreboard.ScorePlayerTeam
[14:31:31] [Server thread/WARN]:        at me.neznamy.tab.platforms.bukkit.nms.NMSStorage.getMethod(NMSStorage.java:616)
[14:31:31] [Server thread/WARN]:        at me.neznamy.tab.platforms.bukkit.nms.NMSStorage.initializeMethods(NMSStorage.java:523)
[14:31:31] [Server thread/WARN]:        at me.neznamy.tab.platforms.bukkit.nms.NMSStorage.<init>(NMSStorage.java:233)
[14:31:31] [Server thread/WARN]:        at me.neznamy.tab.platforms.bukkit.Main.isVersionSupported(Main.java:79)
[14:31:31] [Server thread/WARN]:        at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:25)
[14:31:31] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:31:31] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328)
[14:31:31] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:31:31] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:436)
[14:31:31] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384)
[14:31:31] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:387)
[14:31:31] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
[14:31:31] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596)
[14:31:31] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by Tanguygab** [comment]
try on a normal Spigot server, if it works there, then it's an issue with CatServer
