### ISSUE TITLE
TAB 3.0.0 and 2.9.2 Broke Suddenly

### ISSUE THREAD

**Issue by nissiongot** [NEZNAMY/TAB#422]
**Server version**
Paper 1.17.1

**Plugin version** ("latest" is not a version)
2.9.2 & 3.0.0

**Describe the bug**
My TAB was working fine on 2.9.2 for MONTHS but then i saw 3.0.0 come out on McM, i downloaded that release. From then on everything went bad. The sorting on tab was fine, the old configs were saved and everything was fine. However whenever I ran /lp user <myname> parent set owner (for me, and I am OP) or set default, it gives me the message that "Server you are on went down, connecting you to the fallback server" and it disconnects me. The server doesnt crash but it throws me out with that message.

So I downgrade to 2.9.2 and then go in, and when I type the luckperms commands now it works fine.. except the tablist is NOT sorted (given i replaced the 3.0.0 generated configs with the old configs). 3.0.0 copied from the old configs and it worked just fine in sorting so its definitely not an issue with my conifguration. Adhere, the old configs worked fine for months! The weird part is when I switch server in my bungee, it sometimes reorients itself perfectly, then breaks again. Also on my bungee TAB is on the backends not on the bungee itself.

Things I tried to fix:
Change Paper Versions (some of the latest releases in 1.17)
Use older versions of 1.17 Paper
Use last Tuinity 1.17 Release
Doesn't work with either so not a server software issue im guessing?
Downgraded ViaVersion & ViaBackwards to remove 1.18 compatbiility but still didn't work.
Tried with older luckperm releases, still doesn't work. 

**How to reproduce**
I dont know if this will work for everyone but maybe have luckperms and get 3.0.0 and then type /lp user <user> parent set <group> and go back and forth and it crashes in a try or two. Then replace with 2.9.2 and maybe it goes haywire again.

**Expected behavior**
For TAB to be sorted and 3.0.0 to not crash

**Actual behavior**
3.0.0 Crashes when i run the Luckperms command to change group, and downgrading to 2.9.2 doesn't keep it sorted.

**Additional info** (errors, screenshots, ...)
![Screenshot from 2021-12-03 14-50-08](https://user-images.githubusercontent.com/29209924/144577858-25205259-a416-4e7b-a42d-757f494af608.png)

**Comment by NEZNAMY** [comment]
Whenever you get "Server you are on went down, connecting you to the fallback server", you should get the full error message in console. I can't do anything without that message.

**Comment by nissiongot** [comment]
The thing is it doesn't give any logs, this is all it sends: 

`[21:03:03 INFO]: [BuycraftX] Fetched due players (0 found).
[21:04:23 INFO]: [LP] LOG > (ALEviLDeEdZ@survival) [U] (alevildeedz)
[21:04:23 INFO]: [LP] LOG > parent set default
[21:05:03 INFO]: [BuycraftX] Fetching all due players...
[21:05:03 INFO]: [BuycraftX] Fetched due players (0 found).
[21:05:10 INFO]: [LP] LOG > (ALEviLDeEdZ@survival) [U] (alevildeedz)
[21:05:10 INFO]: [LP] LOG > parent set owner
[21:06:08 INFO]: [LP] LOG > (ALEviLDeEdZ@survival) [U] (alevildeedz)
[21:06:08 INFO]: [LP] LOG > parent set vipultra
[21:06:52 INFO]: [LP] LOG > (ALEviLDeEdZ@survival) [U] (alevildeedz)
[21:06:52 INFO]: [LP] LOG > parent set owner
[21:07:03 INFO]: [BuycraftX] Fetching all due players...
[21:07:03 INFO]: [BuycraftX] Fetched due players (0 found).
[21:07:40 INFO]: [LP] LOG > (ALEviLDeEdZ@survival) [U] (alevildeedz)
[21:07:40 INFO]: [LP] LOG > parent set default
[21:08:23 INFO]: UUID of player ALEviLDeEdZ is 4944d779-34de-4c3e-9bd4-0575392f34f5
[21:08:23 INFO]: [VoidChest-1.8.4] Join listener: Data for: ALEviLDeEdZ have been removed.
[21:08:23 INFO]: Player owned: 0 voidchests.
[21:08:23 INFO]: Booster: 1.0, No active booster
[21:08:23 INFO]: [VoidChest-1.8.4] End of debugging.
[21:08:23 INFO]: [DiscordSRV] Player ALEviLDeEdZ joined with silent joining permission, not sending a join message
[21:08:23 INFO]: ALEviLDeEdZ[/51.77.31.63:54936] logged in with entity id 3715 at ([world]-52.88201527721292, 71.91665415988346, -127.1468585982114)
[21:08:26 INFO]: [mcMMO] Creating new data for player: ALEviLDeEdZ
[21:08:29 INFO]: ALEviLDeEdZ issued server command: /lp user ALEviLDeEdZ parent set default
[21:08:29 INFO]: [LuckPerms] [Messaging] Sending log with id: 2ed0f94d-9048-4398-b5eb-bdd3f3fe8ada
[21:08:29 INFO]: [LP] LOG > (ALEviLDeEdZ@skyblock) [U] (alevildeedz)
[21:08:29 INFO]: [LP] LOG > parent set default
[21:08:29 INFO]: [LuckPerms] [Messaging] Sending user ping for 'alevildeedz' with id: 0deebf9f-31ef-4138-aa59-ae0c1e0b0884
[21:08:32 INFO]: ALEviLDeEdZ issued server command: /lp user ALEviLDeEdZ parent set owner
[21:08:32 INFO]: [LuckPerms] [Messaging] Sending log with id: 66d697e7-1e0b-4a63-8948-9e7a02dd51fa
[21:08:32 INFO]: [LP] LOG > (ALEviLDeEdZ@skyblock) [U] (alevildeedz)
[21:08:32 INFO]: [LP] LOG > parent set owner
[21:08:32 INFO]: [LuckPerms] [Messaging] Sending user ping for 'alevildeedz' with id: f7dc8d56-7091-4188-b701-1e2acb881929
[21:08:34 INFO]: ALEviLDeEdZ issued server command: /lp user ALEviLDeEdZ parent set default
[21:08:34 INFO]: [LuckPerms] [Messaging] Sending log with id: f1e5240d-e10b-422b-b065-dabf9c1fb3e5
[21:08:34 INFO]: [LP] LOG > (ALEviLDeEdZ@skyblock) [U] (alevildeedz)
[21:08:34 INFO]: [LP] LOG > parent set default
[21:08:34 INFO]: [LuckPerms] [Messaging] Sending user ping for 'alevildeedz' with id: 766ebcf3-1038-4df7-9c15-038b8f8e5e20
[21:08:37 INFO]: ALEviLDeEdZ issued server command: /lp user ALEviLDeEdZ parent set owner
[21:08:37 INFO]: [LuckPerms] [Messaging] Sending log with id: c1b9ee75-0b04-4198-be54-f3233b9fd6a4
[21:08:37 INFO]: [LP] LOG > (ALEviLDeEdZ@skyblock) [U] (alevildeedz)
[21:08:37 INFO]: [LP] LOG > parent set owner
[21:08:37 INFO]: [LuckPerms] [Messaging] Sending user ping for 'alevildeedz' with id: 6a5548df-5a47-4a2e-a538-4631332ddea5
[21:08:41 INFO]: ALEviLDeEdZ issued server command: /lp
[21:08:49 INFO]: ALEviLDeEdZ issued server command: /lp user ALEviLDeEdZ parent set default
[21:08:49 INFO]: [LuckPerms] [Messaging] Sending log with id: c4966231-e214-43ae-8b9a-bfa9a3818ab3
[21:08:49 INFO]: [LP] LOG > (ALEviLDeEdZ@skyblock) [U] (alevildeedz)
[21:08:49 INFO]: [LP] LOG > parent set default
[21:08:49 INFO]: [LuckPerms] [Messaging] Sending user ping for 'alevildeedz' with id: 2c90452a-e103-4e9f-a4c5-14aafc6f4614
[21:08:54 INFO]: ALEviLDeEdZ issued server command: /lp user ALEviLDeEdZ parent set owner
[21:08:54 INFO]: [LuckPerms] [Messaging] Sending log with id: 5b6259d5-eb21-48bd-8e48-6efb03584e73
[21:08:54 INFO]: [LP] LOG > (ALEviLDeEdZ@skyblock) [U] (alevildeedz)
[21:08:54 INFO]: [LP] LOG > parent set owner
[21:08:54 INFO]: [LuckPerms] [Messaging] Sending user ping for 'alevildeedz' with id: 60ee256c-d015-4b4b-b973-0a3a70b9c16f
[21:08:54 INFO]: [DiscordSRV] Player ALEviLDeEdZ quit with silent quitting permission, not sending a quit message
[21:08:54 INFO]: [VoidChest-1.8.4] Quit listener: Data for: ALEviLDeEdZ have been removed.
`

**Comment by NEZNAMY** [comment]
In console of the backend server.

**Comment by nissiongot** [comment]
Yep, the one where I got disconnected.

**Comment by NEZNAMY** [comment]
Some bungeecord plugins allow you to see disconnect message, try getting one and display it.

**Comment by nissiongot** [comment]
Okay got the logs! These are on my bungee:

[13:09:41 ERROR]: [/217.182.27.250:57055|ALEviLDeEdZ] <-> DownstreamBridge <-> [test] - encountered exception
java.lang.IllegalArgumentException: Team 12ALEviLDeEdZA already exists in this scoreboard
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:243) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[13:09:41 INFO]: [ALEviLDeEdZ] disconnected with: The server you were previously on went down, you have been connected to a fallback server

**Comment by NEZNAMY** [comment]
This is a bungeecord bug, I will look into further ways of avoiding it.

**Comment by nissiongot** [comment]
Oh i see thanks!

**Comment by NEZNAMY** [comment]
Shouldn't be, since this bug is already present in bungeecord for years.

**Comment by NEZNAMY** [comment]
Found the reason why this is an issue more than it was before and it will be fixed in the next version.

**Comment by nissiongot** [comment]
I see, is there any temporary fix for this?
