### ISSUE TITLE
errors.log random error

### ISSUE THREAD

**Issue by Zoro-6191** [NEZNAMY/TAB#442]
**Server version**
Paper 1.18 68

**Plugin version** ("latest" is not a version)
3.0.0

```
11.12.2021 - 11:16:26 - [TAB v3.0.0] An error occurred when refreshing placeholders
11.12.2021 - 11:16:26 - java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.task.RepeatingTask.getInterval()" because "this.refreshTask" is null
11.12.2021 - 11:16:26 -        at TAB.v3.0.0.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:64)
11.12.2021 - 11:16:26 -        at TAB.v3.0.0.jar//me.neznamy.tab.shared.TabRepeatingTask.lambda$createTask$0(TabRepeatingTask.java:40)
11.12.2021 - 11:16:26 -        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
11.12.2021 - 11:16:26 -        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
11.12.2021 - 11:16:26 -        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
11.12.2021 - 11:16:26 -        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
11.12.2021 - 11:16:26 -        at java.base/java.lang.Thread.run(Thread.java:833)
```

Appeared just once, didn't cause any issues.

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/blob/039c1e702784bb57289df4ed6b2da378f663ce9d/shared/src/main/java/me/neznamy/tab/shared/features/PlaceholderManagerImpl.java#L59 it's already initialized in constructor, it cannot be null.

**Comment by MrGraycat** [comment]
This error is from the 3.0.0 version while 3.0.1 is out try updating instead.
