### ISSUE TITLE
Bug with holder (over head)

### ISSUE THREAD

**Issue by monikon22** [NEZNAMY/TAB#45]
Plugin ver: 2.5.2
Server version: SPIGOT 1.11-R1

We updated the plugin to version 2.5.2, but often a bug began to occur with text above the players head. Some players for some reason have 2 names, one from the minecraft itself, and the other from the plugin. If such a player gets into the boat, he will receive only a vanilla (minecraft) holder. Also, their names in the tab rise.

PlaceHolderApi is also used for belowname and abovename.
![bug2](https://user-images.githubusercontent.com/55911809/65814234-c298ce80-e1e7-11e9-987a-5f4379a9aedf.png)
![bug1](https://user-images.githubusercontent.com/55911809/65814235-c3316500-e1e7-11e9-9735-1cf4778664a6.png)

**Comment by NEZNAMY** [comment]
Can you check errors.txt ?

**Comment by monikon22** [comment]
this happened on my 2 servers after this update, I did not install new plugins.

floods this error only, but only the old version

```
20.09.2019 - 15:58:17 - [TAB v2.5.1] An error occured when processing sprint toggle
20.09.2019 - 15:58:17 - java.lang.NullPointerException: null
20.09.2019 - 15:58:17 -        at me.neznamy.tab.bukkit.NameTagLineManager.sneak(NameTagLineManager.java:24)
20.09.2019 - 15:58:17 -        at me.neznamy.tab.bukkit.NameTagX$3.run(NameTagX.java:82)
20.09.2019 - 15:58:17 -        at me.neznamy.tab.shared.Shared$3.run(Shared.java:169)
20.09.2019 - 15:58:17 -        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20.09.2019 - 15:58:17 -        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20.09.2019 - 15:58:17 -        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
20.09.2019 - 15:58:17 -        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
20.09.2019 - 15:58:17 -        at java.lang.Thread.run(Thread.java:748)
```

and

```
20.09.2019 - 15:59:36 - [TAB v2.5.1] An error occured when processing sprint toggle
20.09.2019 - 15:59:36 - java.lang.NullPointerException: null
```

no more

**Comment by NEZNAMY** [comment]
This really looks like another plugin could be doing it, do you have any ideas ?

**Comment by Savag3life** [comment]
I can reproduce. Kind of the same issue. For some reason, the first 2 - 5 names on TAB are broken unless the plugin is reloaded. Once you relog it is broken again.

Before Reload ->
![image](https://user-images.githubusercontent.com/22297532/66668415-98a1cc00-ec2b-11e9-90c1-a91546cac767.png)

After Reload (Correct Format) -> 
![image](https://user-images.githubusercontent.com/22297532/66668450-afe0b980-ec2b-11e9-900b-1ab37e11e381.png)

**Comment by NEZNAMY** [comment]
What's your client version ?

**Comment by Savag3life** [comment]
Client version 1.8  forge. Server version 1.8.8 paperspigot

**Comment by NEZNAMY** [comment]
Read FAQ. 1.8.0 has bugs and this is one of them.

**Comment by NEZNAMY** [comment]
Are these bugged players actually online ?

**Comment by NEZNAMY** [comment]
Closing due to inactivity of issue author and inability to reproduce.
