### ISSUE TITLE
Could not pass event PlayerChangedWorldEvent

### ISSUE THREAD

**Issue by RanWhite** [NEZNAMY/TAB#455]
TAB v3.0.1
Pufferfish-23 (MC: 1.18.1)

terException: Cannot invoke "me.neznamy.tab.api.ArmorStandManager.getNearbyPlayers()" because the return value of "me.neznamy.tab.api.TabPlayer.getArmorStandManager()" is null
        at me.neznamy.tab.platforms.bukkit.features.unlimitedtags.EventListener.onWorldChange(EventListener.java:69) ~[TAB.v3.0.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor420.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:git-Pufferfish-25]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:982) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:815) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1006) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at org.bukkit.craftbukkit.v1_18_R1.entity.CraftEntity.teleport(CraftEntity.java:556) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at cc.baka9.catseedlogin.Listeners.onPlayerJoin(Listeners.java:173) ~[CatSeedLogin-1.2.6-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor412.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:git-Pufferfish-25]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:982) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:815) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1006) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at org.bukkit.craftbukkit.v1_18_R1.entity.CraftEntity.teleport(CraftEntity.java:556) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at cc.baka9.catseedlogin.Listeners.onPlayerJoin(Listeners.java:173) ~[CatSeedLogin-1.2.6-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor412.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:git-Pufferfish-25]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]  
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:307) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1638) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[pufferfish-1.18.1.jar:git-Pufferfish-25] 
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1266) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-25]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by NEZNAMY** [comment]
Did the player switch world immediately on join?

**Comment by RanWhite** [comment]
> Did the player switch world immediately on join?

Yeah , Can you fix this ?
