### ISSUE TITLE
[Bug?] MySQL issue

### ISSUE THREAD

**Issue by Yurinann** [NEZNAMY/TAB#466]
**Server version**
FlameCord (Bungee), MySQL 5.7.34

**Plugin version** ("latest" is not a version)
3.0.2-pre2

**Describe the bug**
MySQL may fail to connect when the plugin is loaded or when the server is not restarted for a long time

**How to reproduce**
~I can't describe it exactly. The problem appears almost without pattern.~
I did, in fact, fail to find an obvious pattern for it to occur. I referenced the link in the reply below and I was able to confirm that I don't have problems with all of my messages, the only possibility is that the network environment is affecting it, but other plugins have never had this problem when set up correctly.

**Expected behavior**
MySQL can connect properly.

**Actual behavior**
MySQL can't connect properly.

**Additional info** (errors, screenshots, ...)
on plugin load:
```
[15:15:28 INFO]: [TAB v3.0.2-pre1] Failed to connect to MySQL
[15:15:28 INFO]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[15:15:28 INFO]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[15:15:28 INFO]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[15:15:28 INFO]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
[15:15:28 INFO]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[15:15:28 INFO]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[15:15:28 INFO]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[15:15:28 INFO]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
[15:15:28 INFO]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
[15:15:28 INFO]:        at TAB-3.0.2-pre1.jar//me.neznamy.tab.shared.config.MySQL.openConnection(MySQL.java:34)
[15:15:28 INFO]:        at TAB-3.0.2-pre1.jar//me.neznamy.tab.shared.config.MySQL.<init>(MySQL.java:29)
[15:15:28 INFO]:        at TAB-3.0.2-pre1.jar//me.neznamy.tab.shared.config.Configs.loadConfig(Configs.java:111)
[15:15:28 INFO]:        at TAB-3.0.2-pre1.jar//me.neznamy.tab.shared.config.Configs.loadFiles(Configs.java:77)
[15:15:28 INFO]:        at TAB-3.0.2-pre1.jar//me.neznamy.tab.shared.TAB.load(TAB.java:148)
[15:15:28 INFO]:        at TAB-3.0.2-pre1.jar//me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:52)
[15:15:28 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:15:28 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:15:28 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[15:15:28 INFO]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[15:15:28 INFO]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[15:15:28 INFO]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[15:15:28 INFO]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[15:15:28 INFO]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[15:15:28 INFO]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:15:28 INFO]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

<br>

on /tab reload :
```
[15:14:03] [Paper Watchdog Thread/ERROR]: ------------------------------
[15:14:08] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-404 (MC: 1.17.1) ---
[15:14:08] [Paper Watchdog Thread/ERROR]: The server has not responded for 25 seconds! Creating thread dump
[15:14:08] [Paper Watchdog Thread/ERROR]: ------------------------------
[15:14:08] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[15:14:08] [Paper Watchdog Thread/ERROR]: ------------------------------
[15:14:08] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[15:14:08] [Paper Watchdog Thread/ERROR]: 	PID: 45 | Suspended: false | Native: true | State: RUNNABLE
[15:14:08] [Paper Watchdog Thread/ERROR]: 	Stack:
[15:14:08] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/sun.nio.ch.Net.poll(Native Method)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:285)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.net.SocksSocketImpl.readSocksReply(SocksSocketImpl.java:123)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:390)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.net.Socket.connect(Socket.java:633)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//com.mysql.cj.NativeSession.connect(NativeSession.java:144)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		platform/java.sql@17.0.1/java.sql.DriverManager.getConnection(DriverManager.java:681)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		platform/java.sql@17.0.1/java.sql.DriverManager.getConnection(DriverManager.java:229)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		TAB-3.0.2-pre1.jar//me.neznamy.tab.shared.config.MySQL.openConnection(MySQL.java:34)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		TAB-3.0.2-pre1.jar//me.neznamy.tab.shared.config.MySQL.<init>(MySQL.java:29)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		TAB-3.0.2-pre1.jar//me.neznamy.tab.shared.config.Configs.loadConfig(Configs.java:111)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		TAB-3.0.2-pre1.jar//me.neznamy.tab.shared.config.Configs.loadFiles(Configs.java:77)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		TAB-3.0.2-pre1.jar//me.neznamy.tab.shared.TAB.load(TAB.java:148)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		TAB-3.0.2-pre1.jar//me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:22)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		TAB-3.0.2-pre1.jar//me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:58)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		TAB-3.0.2-pre1.jar//me.neznamy.tab.platforms.bukkit.Main$TABCommand.onCommand(Main.java:173)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:529)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:491)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer$$Lambda$3768/0x00000008014c93a0.run(Unknown Source)
[15:14:08] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
[15:14:08] [Paper Watchdog Thread/ERROR]: ------------------------------
[15:14:08] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[15:14:08] [Paper Watchdog Thread/ERROR]: ------------------------------
```

**Comment by Tanguygab** [comment]
https://stackoverflow.com/a/2985169

**Comment by Yurinann** [comment]
> https://stackoverflow.com/a/2985169

I did, in fact, fail to find an obvious pattern for it to occur. I referenced the link in the reply below and I was able to confirm that I don't have problems with all of my messages, the only possibility is that the network environment is affecting it, but other plugins have never had this problem when set up correctly.

**Comment by NEZNAMY** [comment]
If it's local, network connection should not affect it.

**Comment by Yurinann** [comment]
```
04.01.2022 - 13:58:48 - [TAB v3.0.2-pre2] Failed to load data of Yurinann from MySQL
04.01.2022 - 13:58:48 - java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1648)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1564)
04.01.2022 - 13:58:48 -        at me.neznamy.tab.shared.config.MySQL.prepareStatement(MySQL.java:71)
04.01.2022 - 13:58:48 -        at me.neznamy.tab.shared.config.MySQL.getCRS(MySQL.java:86)
04.01.2022 - 13:58:48 -        at me.neznamy.tab.shared.config.mysql.MySQLUserConfiguration.lambda$load$10(MySQLUserConfiguration.java:84)
04.01.2022 - 13:58:48 -        at me.neznamy.tab.shared.CpuManager.lambda$submit$4(CpuManager.java:151)
04.01.2022 - 13:58:48 -        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
04.01.2022 - 13:58:48 -        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
04.01.2022 - 13:58:48 -        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
04.01.2022 - 13:58:48 -        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
04.01.2022 - 13:58:48 -        at java.base/java.lang.Thread.run(Thread.java:833)
```

Errors in errors.log, which are reported every time a player joins the server.

**Comment by Yurinann** [comment]
```
04.01.2022 - 13:58:48 - [TAB v3.0.2-pre2] Failed to load data of Yurinann from MySQL
04.01.2022 - 13:58:48 - java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1648)
04.01.2022 - 13:58:48 -        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1564)
04.01.2022 - 13:58:48 -        at me.neznamy.tab.shared.config.MySQL.prepareStatement(MySQL.java:71)
04.01.2022 - 13:58:48 -        at me.neznamy.tab.shared.config.MySQL.getCRS(MySQL.java:86)
04.01.2022 - 13:58:48 -        at me.neznamy.tab.shared.config.mysql.MySQLUserConfiguration.lambda$load$10(MySQLUserConfiguration.java:84)
04.01.2022 - 13:58:48 -        at me.neznamy.tab.shared.CpuManager.lambda$submit$4(CpuManager.java:151)
04.01.2022 - 13:58:48 -        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
04.01.2022 - 13:58:48 -        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
04.01.2022 - 13:58:48 -        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
04.01.2022 - 13:58:48 -        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
04.01.2022 - 13:58:48 -        at java.base/java.lang.Thread.run(Thread.java:833)
```

Errors in errors.log, which are reported every time a player joins the server.

**Comment by NEZNAMY** [comment]
Try latest build from actions.

**Comment by Yurinann** [comment]
> Try latest build from actions.

The error does not appear and runs normally.

**Comment by NEZNAMY** [comment]
So is this solved then?

**Comment by Yurinann** [comment]
> So is this solved then?

Thank you very much for your help, the problem of not being able to load player data has been solved. However, with all due respect to my lack of skill, I am not sure if the issue is the same as the initial feedback (or can be resolved mutually).

**Comment by NEZNAMY** [comment]
This is up to you to confirm if this fixed all of your issues or not.

**Comment by Yurinann** [comment]
> This is up to you to confirm if this fixed all of your issues or not.

As I said above, the initial feedback was difficult to determine, so I assumed that the issue had been resolved, and if the initial issue reappeared, I would confirm it and reopen the issue.

Once again, thank you sincerely for your help.
