### ISSUE TITLE
PremiumConfig error

### ISSUE THREAD

**Issue by rookieCookies** [NEZNAMY/TAB#474]
1.18.1

3.0.1

Probably the plugin trying to access a file before it creates it

1.18.1 paper server with the latest release

To the plugin to start up?

plugin no work

`
[19:50:13 INFO]: [TAB] Enabling TAB v3.0.1
[19:50:13 INFO]: [TAB] Server version: 1.18.1 (v1_18_R1)
[19:50:13 INFO]: [TAB] Loaded NMS hook in 10ms
[19:50:13 INFO]: [TAB] File plugins/TAB/errors.log exists and is not empty. Take a look at the error messages and try to resolve them. After you do, delete the file.
[19:50:13 INFO]: [TAB] --------------------------------------------------------------
[19:50:13 INFO]: [TAB] Performing configuration conversion from 2.9.2 to 3.0.0
[19:50:13 INFO]: [TAB] Please note that this may not be 100% accurate
[19:50:13 INFO]: [TAB] Review your configuration and verify everything is as you want it to be
[19:50:13 INFO]: [TAB] --------------------------------------------------------------
[19:50:13 INFO]: [TAB v3.0.1] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[19:50:13 INFO]: java.nio.file.NoSuchFileException: plugins/TAB/premiumconfig.yml
[19:50:13 INFO]:        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[19:50:13 INFO]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[19:50:13 INFO]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[19:50:13 INFO]:        at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:249)
[19:50:13 INFO]:        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
[19:50:13 INFO]:        at java.base/java.nio.file.Files.delete(Files.java:1152)
[19:50:13 INFO]:        at TAB.v3.0.1.jar//me.neznamy.tab.shared.config.Configs.createConfigYml(Configs.java:484)
[19:50:13 INFO]:        at TAB.v3.0.1.jar//me.neznamy.tab.shared.config.Configs.convertToV3(Configs.java:252)
[19:50:13 INFO]:        at TAB.v3.0.1.jar//me.neznamy.tab.shared.config.Configs.loadConfig(Configs.java:106)
[19:50:13 INFO]:        at TAB.v3.0.1.jar//me.neznamy.tab.shared.config.Configs.loadFiles(Configs.java:83)
[19:50:13 INFO]:        at TAB.v3.0.1.jar//me.neznamy.tab.shared.TAB.load(TAB.java:145)
[19:50:13 INFO]:        at TAB.v3.0.1.jar//me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:52)
[19:50:13 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:50:13 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:50:13 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[19:50:13 INFO]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[19:50:13 INFO]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[19:50:13 INFO]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[19:50:13 INFO]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[19:50:13 INFO]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[19:50:13 INFO]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[19:50:13 INFO]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:50:13 INFO]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by NEZNAMY** [comment]
Will be fixed in the next version.
