### ISSUE TITLE
Could not pass event PlayerChangedWorldEvent to TAB v3.0.1

### ISSUE THREAD

**Issue by RanWhite** [NEZNAMY/TAB#482]
mirai 1.18.1
it happen in paper 1.18.1 too
Tab 3.0.1

When player switch world immediately on join 

[01:39:42] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to TAB v3.0.1
java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.ArmorStandManager.getNearbyPlayers()" because the return value of "me.neznamy.tab.api.TabPlayer.getArmorStandManager()" is null
	at me.neznamy.tab.platforms.bukkit.features.unlimitedtags.EventListener.onWorldChange(EventListener.java:69) ~[TAB.v3.0.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor380.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[mirai-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[mirai-api-1.18.1-R0.1-SNAPSHOT.jar:git-Mirai-"609e1f9"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[mirai-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:641) ~[mirai-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:998) ~[mirai-1.18.1.jar:git-Mirai-"609e1f9"]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:831) ~[mirai-1.18.1.jar:git-Mirai-"609e1f9"]
	at org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1020) ~[mirai-1.18.1.jar:git-Mirai-"609e1f9"]
	at org.bukkit.craftbukkit.v1_18_R1.entity.CraftEntity.teleport(CraftEntity.java:556) ~[mirai-1.18.1.jar:git-Mirai-"609e1f9"]
	at cc.baka9.catseedlogin.Listeners.onPlayerJoin(Listeners.java:173) ~[CatSeedLogin-1.2.6-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor372.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[mirai-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[mirai-api-1.18.1-R0.1-SNAPSHOT.jar:git-Mirai-"609e1f9"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[mirai-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:641) ~[mirai-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[mirai-1.18.1.jar:git-Mirai-"609e1f9"]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[mirai-1.18.1.jar:git-Mirai-"609e1f9"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:309) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1654) ~[mirai-1.18.1.jar:git-Mirai-"609e1f9"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:493) ~[mirai-1.18.1.jar:git-Mirai-"609e1f9"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1487) ~[mirai-1.18.1.jar:git-Mirai-"609e1f9"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1276) ~[mirai-1.18.1.jar:git-Mirai-"609e1f9"]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[mirai-1.18.1.jar:git-Mirai-"609e1f9"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/commit/486546918f541cbb5a55b98cbc7dc28291e86a02, will be fixed in thenext version.
