### ISSUE TITLE
Issue with api

### ISSUE THREAD

**Issue by Conutik** [NEZNAMY/TAB#487]
I'm trying to use the TAB Api with my plugin but I keep getting this error when trying to load: 
```
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.TabAPI.getTeamManager()" because the return value of "me.neznamy.tab.api.TabAPI.getInstance()" is null
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.17.1.jar:git-Paper-384]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Paper-384]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Paper-384]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-384]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-384]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.TabAPI.getTeamManager()" because the return value of "me.neznamy.tab.api.TabAPI.getInstance()" is null
at com.conutik.vtags.Main.<init>(Main.java:14) ~[vtags.jar:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
at java.lang.Class.newInstance(Class.java:645) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[patched_1.17.1.jar:git-Paper-384]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.1.jar:git-Paper-384]
... 7 more
```

I tried setting TAB as softdepend and depend but nothing changed. My Code: 

```
public class Main extends JavaPlugin implements Listener {
    TabAPI TABInstance = TabAPI.getInstance();
    TeamManager teamManager = TabAPI.getInstance().getTeamManager();
    @Override
    public void onEnable() {
        new BukkitRunnable() {
            @Override
            public void run() {
                for (Player p : Bukkit.getOnlinePlayers()) {
                    for (Player ps : Bukkit.getOnlinePlayers()) {
                        if (Functions.blockBetweenPlayers(p, ps)) {
                            teamManager.hideNametag(TABInstance.getPlayer(p.getUniqueId()), TABInstance.getPlayer(ps.getUniqueId()));
                            teamManager.hideNametag(TABInstance.getPlayer(ps.getUniqueId()), TABInstance.getPlayer(p.getUniqueId()));
                        } else {
                            teamManager.showNametag(TABInstance.getPlayer(p.getUniqueId()), TABInstance.getPlayer(ps.getUniqueId()));
                            teamManager.showNametag(TABInstance.getPlayer(ps.getUniqueId()), TABInstance.getPlayer(p.getUniqueId()));
                        }
                    }

                }
            }
        }.runTaskTimer(this, 0, getConfig().getInt("update_period"));

        Bukkit.getPluginManager().registerEvents(this, this);
        Bukkit.getServer().getConsoleSender().sendMessage(ChatColor.GREEN + "VTags is now working");
    }
}
```

TAB is downloaded on my server, and I have it as a dependency. (Using spigot/paper for 1.17.1)

**Comment by NEZNAMY** [comment]
API was null. That means you either shaded the plugin's classes into your jar or your code ran before TAB loaded.

**Comment by Conutik** [comment]
> That means you either shaded the plugin's classes into your jar or your code ran before TAB lo

Ok So I fixed that issue now, so it runs after TAB Loaded. But I'm still getting the issue.

My Code:

```public class Main extends JavaPlugin implements Listener {
    TabAPI TABInstance;
    TeamManager teamManager;
    @Override
    public void onEnable() {
        new BukkitRunnable() {
            @Override
            public void run() {
                TABInstance = TabAPI.getInstance();
                teamManager = TabAPI.getInstance().getTeamManager();
                for (Player p : Bukkit.getOnlinePlayers()) {
                    for (Player ps : Bukkit.getOnlinePlayers()) {
                        if (Functions.blockBetweenPlayers(p, ps)) {
                            teamManager.hideNametag(TABInstance.getPlayer(p.getUniqueId()), TABInstance.getPlayer(ps.getUniqueId()));
                            teamManager.hideNametag(TABInstance.getPlayer(ps.getUniqueId()), TABInstance.getPlayer(p.getUniqueId()));
                        } else {
                            teamManager.showNametag(TABInstance.getPlayer(p.getUniqueId()), TABInstance.getPlayer(ps.getUniqueId()));
                            teamManager.showNametag(TABInstance.getPlayer(ps.getUniqueId()), TABInstance.getPlayer(p.getUniqueId()));
                        }
                    }

                }
            }
        }.runTaskTimer(this, 0, getConfig().getInt("update_period"));

        Bukkit.getPluginManager().registerEvents(this, this);
        Bukkit.getServer().getConsoleSender().sendMessage(ChatColor.GREEN + "VTags is now working");
    }
}```

**Comment by NEZNAMY** [comment]
Send full console log. Null API means the plugin is not enabled.

**Comment by Conutik** [comment]
```java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.TabAPI.getTeamManager()" because the return value of "me.neznamy.tab.api.TabAPI.getInstance()" is null
at com.conutik.vtags.Main$1.run(Main.java:21) ~[vtags.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-384]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-384]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-384]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-384]
at java.lang.Thread.run(Thread.java:833) ~[?:?]```

Just checked, the plugin (TAB) is enabled

**Comment by NEZNAMY** [comment]
Random stack trace won't help me at all. I have no idea what is on line 21 of your main class. Send full console log.

**Comment by Conutik** [comment]
That's the full log in console.

```public class Main extends JavaPlugin implements Listener {
    TabAPI TABInstance;
    TeamManager teamManager;
    @Override
    public void onEnable() {
        new BukkitRunnable() {
            @Override
            public void run() {
                TABInstance = TabAPI.getInstance();
                teamManager = TabAPI.getInstance().getTeamManager();
                for (Player p : Bukkit.getOnlinePlayers()) {
                    for (Player ps : Bukkit.getOnlinePlayers()) {
                        if (Functions.blockBetweenPlayers(p, ps)) {
                            teamManager.hideNametag(TABInstance.getPlayer(p.getUniqueId()), TABInstance.getPlayer(ps.getUniqueId()));
                            teamManager.hideNametag(TABInstance.getPlayer(ps.getUniqueId()), TABInstance.getPlayer(p.getUniqueId()));
                        } else {
                            teamManager.showNametag(TABInstance.getPlayer(p.getUniqueId()), TABInstance.getPlayer(ps.getUniqueId()));
                            teamManager.showNametag(TABInstance.getPlayer(ps.getUniqueId()), TABInstance.getPlayer(p.getUniqueId()));
                        }
                    }

                }
            }
        }.runTaskTimer(this, 0, getConfig().getInt("update_period"));

        Bukkit.getPluginManager().registerEvents(this, this);
        Bukkit.getServer().getConsoleSender().sendMessage(ChatColor.GREEN + "VTags is now working");
    }
}
```


Starting from line 12 and going up

**Comment by NEZNAMY** [comment]
The API works. Many are using it. If you refuse to provide requested information I will not help you.

**Comment by Conutik** [comment]
Where can I find the full log?

**Comment by NEZNAMY** [comment]
logs/latest.log. If you don't know this, you may not be ready to use API from other plugins.

**Comment by Conutik** [comment]
> If you don't know this, you may not be ready to use API from other plu

No I know but I meant like you want the one before the change or after?

This is the after one: https://www.toptal.com/developers/hastebin/ujepexofuy.sql

**Comment by NEZNAMY** [comment]
Open your jar and check if it contains tab classes.

**Comment by Conutik** [comment]
![image](https://user-images.githubusercontent.com/60240193/151612151-3428f46b-0c25-47a2-b872-9fa7ee237184.png)
Yes it does

**Comment by Conutik** [comment]
they are defined and everything,

**Comment by NEZNAMY** [comment]
The final compiled jar file containing code.

**Comment by Conutik** [comment]
![image](https://user-images.githubusercontent.com/60240193/151612401-07dc79a7-6a6a-4f4f-8638-7367ee77abbd.png)

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/issues/487#issuecomment-1024534418 as I said, your jar contains TAB's classes which is not allowed.

**Comment by Conutik** [comment]
oh ok

**Comment by Conutik** [comment]
Works, Thank you! I kept it shaded when was debugging alone and forgot to remove. Sorry
