### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xAspired** [NEZNAMY/TAB#504]
### Server version

Velocity 3.1.1

### TAB version

3.0.2

### Stack trace

```
24.02.2022 - 23:56:54 - [TAB v3.0.2] An error occurred when processing ServerPostConnectEvent
24.02.2022 - 23:56:54 - java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.TabPlayer.getServer()" because "changed" is null
24.02.2022 - 23:56:54 -        at me.neznamy.tab.shared.FeatureManagerImpl.onServerChange(FeatureManagerImpl.java:180)
24.02.2022 - 23:56:54 -        at me.neznamy.tab.platforms.velocity.VelocityEventListener.lambda$onConnect$2(VelocityEventListener.java:42)
24.02.2022 - 23:56:54 -        at me.neznamy.tab.shared.CpuManager.lambda$submit$5(CpuManager.java:155)
24.02.2022 - 23:56:54 -        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
24.02.2022 - 23:56:54 -        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
24.02.2022 - 23:56:54 -        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
24.02.2022 - 23:56:54 -        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
24.02.2022 - 23:56:54 -        at java.base/java.lang.Thread.run(Thread.java:833)

```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/155629211-15e14845-b3fa-47b0-a5eb-9f6c1da221a8.png)
if you really did check that, then you should read it again

**Comment by Tanguygab** [comment]
nah, it's supposed to be a cross, but Windows shows it weirdly

**Comment by xAspired** [comment]
Oh sorry, my bad than
