### ISSUE TITLE
1.18.2 Not Supported

### ISSUE THREAD

**Issue by xpvtryanx** [NEZNAMY/TAB#515]
### Server version

1.18.2 Paper

### TAB version

3.0.2

### Stack trace

TAB isn't working

### Steps to reproduce (if known)

Just install 1.18.2

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
" I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform"
?

**Comment by MrJorman** [comment]
```org.bukkit.command.CommandException: Cannot execute command 'tab' in plugin TAB v3.0.2 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2380) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2191) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2172) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1414) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1249) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>
```

**Comment by NEZNAMY** [comment]
Update with 1.18.2 support will be release after I fix a few more final issues.

**Comment by msmanui** [comment]
While you wait for the new update, i suggest you add ViaVersion, so players with 1.18.2 will be able to join regardless if you have an older server-version
Updating is not an easy job and requieres lot of time for testing. Its a better option to wait for a secure and stable update than a faster one with bugs. :)

**Comment by DJLost12** [comment]
we know it takes time nez! somehow we will survive with a vanilla tab. thanks for being on top of things for so many months/years with this plugin!
