### ISSUE TITLE
java.lang.IllegalArgumentException: signature cannot be null

### ISSUE THREAD

**Issue by RealTriassic** [NEZNAMY/TAB#516]
### Server version

Purpur 1.18.2

### TAB version

3.1.0

### Stack trace

05.03.2022 - 06:07:32 - [TAB v3.1.0] An error occurred when reading packets
05.03.2022 - 06:07:32 - java.lang.IllegalArgumentException: signature cannot be null
05.03.2022 - 06:07:32 - 	at TAB-3.1.0.jar//me.neznamy.tab.api.util.Preconditions.checkNotNull(Preconditions.java:8)
05.03.2022 - 06:07:32 - 	at TAB-3.1.0.jar//me.neznamy.tab.api.protocol.Skin.<init>(Skin.java:25)
05.03.2022 - 06:07:32 - 	at TAB-3.1.0.jar//me.neznamy.tab.platforms.bukkit.BukkitPacketBuilder.readPlayerInfo(BukkitPacketBuilder.java:337)
05.03.2022 - 06:07:32 - 	at TAB-3.1.0.jar//me.neznamy.tab.shared.FeatureManagerImpl.onPacketPlayOutPlayerInfo(FeatureManagerImpl.java:83)
05.03.2022 - 06:07:32 - 	at TAB-3.1.0.jar//me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:67)
05.03.2022 - 06:07:32 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
05.03.2022 - 06:07:32 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
05.03.2022 - 06:07:32 - 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
05.03.2022 - 06:07:32 - 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
05.03.2022 - 06:07:32 - 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
05.03.2022 - 06:07:32 - 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
05.03.2022 - 06:07:32 - 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
05.03.2022 - 06:07:32 - 	at ProtocolLib-#546.jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
05.03.2022 - 06:07:32 - 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:462)
05.03.2022 - 06:07:32 - 	at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:436)
05.03.2022 - 06:07:32 - 	at ProtocolLib-#546.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:354)
05.03.2022 - 06:07:32 - 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
05.03.2022 - 06:07:32 - 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
05.03.2022 - 06:07:32 - 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
05.03.2022 - 06:07:32 - 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
05.03.2022 - 06:07:32 - 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
05.03.2022 - 06:07:32 - 	at java.base/java.lang.Thread.run(Thread.java:833)

### Additional info

These errors only began appearing in the error.log file after updating to Minecraft 1.18.2 with TAB 3.1.0.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by RealTriassic** [comment]
Not sure if this is useful, but I am also using Geyser with the "." prefix for Bedrock players.
