### ISSUE TITLE
a error text

### ISSUE THREAD

**Issue by hsiachihMain** [NEZNAMY/TAB#537]
### Server version

Paper 1.18.2

### TAB version

3.1.0

### Stack trace

[07:22:23 ERROR]: Thread TAB Processing Thread failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2352) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftWorld.getNMSEntities(CraftWorld.java:1058) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.CraftRegionAccessor.getEntities(CraftRegionAccessor.java:399) ~[paper-1.18.2.jar:git-Paper-267]
        at com.extendedclip.papi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:190) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160) ~[PlaceholderAPI-2.10.10.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[PlaceholderAPI-2.10.10.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[PlaceholderAPI-2.10.10.jar:?]
        at me.neznamy.tab.platforms.bukkit.BukkitPlatform.lambda$registerUnknownPlaceholder$2(BukkitPlatform.java:187) ~[TAB.v3.1.0.jar:?]
        at me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:114) ~[TAB.v3.1.0.jar:?]
        at me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:52) ~[TAB.v3.1.0.jar:?]
        at me.neznamy.tab.shared.features.PlaceholderManagerImpl.updatePlayerPlaceholder(PlaceholderManagerImpl.java:121) ~[TAB.v3.1.0.jar:?]
        at me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:67) ~[TAB.v3.1.0.jar:?]
        at me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$8(CpuManager.java:353) ~[TAB.v3.1.0.jar:?]
        at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:115) ~[TAB.v3.1.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Additional info

this error spamming the console
1 second every time
but in fact,it seems doesnt make any thing stop working,just spamming...oh.I'm not sure.Maybe.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Placeholders#sync-refreshing
