### ISSUE TITLE
 java.lang.NullPointerException: Cannot invoke 

### ISSUE THREAD

**Issue by Rollczi** [NEZNAMY/TAB#540]
### Server version

Paper 1.16.5

### TAB version

TAB-Bridge v2.0.0

### Stack trace

```
[18:07:01 WARN]: java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.bridge.bukkit.BridgePlayer.sendPacket(Object)" because the return value of "me.neznamy.tab.bridge.bukkit.BukkitBridge.getPlayer(org.bukkit.entity.Player)" is null
[18:07:01 WARN]:        at me.neznamy.tab.bridge.bukkit.DataBridge.processPluginMessage(DataBridge.java:180)
[18:07:01 WARN]:        at me.neznamy.tab.bridge.bukkit.BukkitBridge.lambda$onPluginMessageReceived$0(BukkitBridge.java:88)
[18:07:01 WARN]:        at me.neznamy.tab.bridge.bukkit.DataBridge.lambda$submitTask$4(DataBridge.java:193)
[18:07:01 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[18:07:01 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[18:07:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:07:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:07:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Checklist

- [x] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Already fixed in 2.0.1
