### ISSUE TITLE
Players being kicked "Team LD_mwzhm7460nus already exists in this scoreboard"

### ISSUE THREAD

**Issue by Akiranya** [NEZNAMY/TAB#548]
### Server version

Waterfall + Purpur 1.18.2

### TAB version

3.1.0

### Stack trace

```
[14:01:46] [Netty Worker IO Thread #5/ERROR]: [/1.192.166.201:9420|Library_of_ruina] <-> DownstreamBridge <-> [sur] - encountered exception
java.lang.IllegalArgumentException: Team LD_mwzhm7460nus already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:248) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[14:01:46] [Netty Worker IO Thread #5/INFO]: [Library_of_ruina] disconnected with: The server you were previously on went down, you have been connected to a fallback server.
[14:01:46] [Netty Worker IO Thread #5/INFO]: [MC] Un-Registered player Library_of_ruina
[14:01:46] [Netty Worker IO Thread #5/INFO]: [/1.192.166.201:9420|Library_of_ruina] -> UpstreamBridge has disconnected
[14:01:46] [Netty Worker IO Thread #5/INFO]: [/1.192.166.201:9420|Library_of_ruina] <-> DownstreamBridge <-> [sur] has disconnected
```

### Steps to reproduce (if known)

Sorry I really have no idea how to reproduce thiss issue because it just happens randomly ... Sometimes I was afk in the game and I was kicked then the exception I pasted was shown on the console.

### Additional info

I searched in the previous issues #427 #422. It seems this issue has been fixed but not really ...

Here is my startup logs of Waterfall, hopefully this helps: 

```
[02:06:13] [main/INFO]: Using mbed TLS based native cipher.
[02:06:13] [main/INFO]: Using zlib based native compressor.
[02:06:13] [main/INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482
[02:06:13] [main/INFO]: Not on Windows, attempting to use enhanced EpollEventLoop
[02:06:13] [main/INFO]: Epoll is working, utilising it!
[02:06:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
[02:06:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
[02:06:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
[02:06:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
[02:06:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
[02:06:13] [main/INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
[02:06:13] [main/INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:739eda6:482 by WaterfallMC
[02:06:13] [main/INFO]: Loaded plugin LuckPerms version 5.4.1 by Luck
[02:06:13] [main/INFO]: Loaded plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:739eda6:482 by WaterfallMC
[02:06:13] [main/INFO]: Loaded plugin TAB version 3.1.0 by NEZNAMY
[02:06:13] [main/INFO]: Loaded plugin ForceResourcepacks version 1.11.18.1 (build 570) by Phoenix616
[02:06:13] [main/INFO]: Loaded plugin MultiChat version 1.9.6 by Revilo410
[02:06:13] [main/INFO]: Loaded plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:739eda6:482 by WaterfallMC
[02:06:13] [main/INFO]: Loaded plugin LiteBans version 2.8.13 by Ruan
[02:06:13] [main/INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:739eda6:482 by WaterfallMC
[02:06:13] [main/INFO]: Loaded plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:739eda6:482 by WaterfallMC
[02:06:13] [main/INFO]: Loaded plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:739eda6:482 by WaterfallMC
[02:06:13] [main/INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:739eda6:482 by WaterfallMC
[02:06:13] [main/INFO]:         __    
[02:06:13] [main/INFO]:   |    |__)   LuckyPerms v5.4.1
[02:06:13] [main/INFO]:   |___ |      Running on BungeeCord - Waterfall
[02:06:13] [main/INFO]: 
[02:06:13] [main/INFO] [LuckPerms]: Loading configuration...
[02:06:14] [main/INFO] [LuckPerms]: Loading storage provider... [MYSQL]
[02:06:14] [main/INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Starting...
[02:06:14] [main/INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Start completed.
[02:06:14] [main/INFO] [LuckPerms]: Loading messaging service... [PLUGINMSG]
[02:06:14] [main/INFO] [LuckPerms]: Loading internal permission managers...
[02:06:14] [main/INFO] [LuckPerms]: Performing initial data load...
[02:06:15] [main/INFO] [LuckPerms]: Successfully enabled. (took 1445ms)
[02:06:15] [main/INFO]: Enabled plugin LuckPerms version 5.4.1 by Luck
[02:06:15] [main/INFO]: Enabled plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:739eda6:482 by WaterfallMC
[02:06:15] [main/INFO] [TAB]: Enabled in 76ms
[02:06:15] [main/INFO]: Enabled plugin TAB version 3.1.0 by NEZNAMY
[02:06:15] [main/INFO] [ForceResourcepacks]: Loading config!
[02:06:15] [main/INFO] [ForceResourcepacks]: Debug level: FINE
[02:06:15] [main/INFO] [ForceResourcepacks]: Found locale en
[02:06:15] [main/WARN] [ForceResourcepacks]: No default config 'languages/lang.zh.yml' found in ForceResourcepacks.jar!
[02:06:15] [main/INFO] [ForceResourcepacks]: Loading packs:
[02:06:15] [main/INFO] [ForceResourcepacks]: devia - https://mimaru.oss-cn-zhangjiakou.aliyuncs.com/assets/devia.zip - 9fcb9d061b4015381bb01a292737f9445b2be210
[02:06:15] [main/INFO] [ForceResourcepacks]: allpack - https://mimaru.oss-cn-zhangjiakou.aliyuncs.com/assets/allpack.zip - 9ce5897422dc4e8486063a5f160f0c13be43e911
[02:06:15] [main/INFO] [ForceResourcepacks]: allpacktest - https://mimaru.oss-cn-zhangjiakou.aliyuncs.com/assets/allpacktest.zip - 63d3a0c254f694d3d02b09d63da7c02116c4b3a2
[02:06:15] [main/INFO] [ForceResourcepacks]: Empty pack - http://cdn.moep.tv/files/Empty.zip - 01517226212d27586ea0c5d6aff1aa5492dd2484
[02:06:15] [main/INFO] [ForceResourcepacks]: Loading global assignment...
[02:06:15] [main/INFO] [ForceResourcepacks]: Loading server assignments...
[02:06:15] [main/INFO] [ForceResourcepacks]: Loading assignment for server devrpg...
[02:06:15] [main/INFO] [ForceResourcepacks]: Loading assignment for server devia...
[02:06:15] [main/INFO] [ForceResourcepacks]: Update notifications are enabled!
[02:06:15] [main/INFO]: Enabled plugin ForceResourcepacks version 1.11.18.1 (build 570) by Phoenix616
[02:06:15] [main/INFO]: Loading config.yml...
[02:06:15] [main/INFO]: Loading joinmessages.yml...
[02:06:15] [main/INFO]: Loading messages.yml...
[02:06:15] [main/INFO]: Loading chatcontrol.yml...
[02:06:15] [main/INFO]: Loading messages_fr.yml...
[02:06:15] [main/INFO]: Loading joinmessages_fr.yml...
[02:06:15] [main/INFO]: Loading config_fr.yml...
[02:06:15] [main/INFO]: Loading chatcontrol_fr.yml...
[02:06:15] [main/INFO]: [MultiChat] Config Version: 1.9.6
[02:06:15] [main/INFO]: [MultiChat] Starting load routine for data files
[02:06:15] [main/INFO]: [MultiChat] [COMPLETE] Load sequence finished! (Any errors reported above)
[02:06:15] [main/INFO]: Enabled plugin MultiChat version 1.9.6 by Revilo410
[02:06:15] [main/INFO]: Enabled plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:739eda6:482 by WaterfallMC
[02:06:15] [main/INFO] [LiteBans]: Loading SQL driver: mariadb 2.5.2 (org.mariadb.jdbc.Driver)
[02:06:15] [main/INFO] [LiteBans]: Connecting to database...
[02:06:15] [main/INFO] [LiteBans]: litebans-pool - Starting...
[02:06:16] [main/INFO] [LiteBans]: litebans-pool - Start completed.
[02:06:16] [main/INFO] [LiteBans]: Connected to MariaDB database successfully (82.2 ms).
[02:06:16] [main/INFO] [LiteBans]: [Sync] Server name: mewcraft
[02:06:16] [main/INFO] [LiteBans]: [Sync] Server UUID: d528417e93884254a777fe91b9856fa7 <1>
[02:06:16] [main/INFO] [LiteBans]: Database connection fully initialized (98.8 ms).
[02:06:16] [main/INFO] [LiteBans]: v2.8.13 enabled. Startup took 529 ms.
[02:06:16] [main/INFO]: Enabled plugin LiteBans version 2.8.13 by Ruan
[02:06:16] [main/INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:739eda6:482 by WaterfallMC
[02:06:16] [main/INFO]: Enabled plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:739eda6:482 by WaterfallMC
[02:06:16] [main/INFO]: Enabled plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:739eda6:482 by WaterfallMC
[02:06:16] [Netty Boss IO Thread #0/INFO]: Listening on /0.0.0.0:25565
```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Akiranya** [comment]
Here is my `config.yml`:

```
# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  disable-in-worlds: {}
  disable-in-servers: {}
  header:
    - "&7&l>> %animation:welcome%&3 &l%player%&7&l! &7&l<<"
    - ""
  footer:
    - ""
    - "&b&l上古时代 &eMEWCRAFT &dwww.mewcraft.cc"
  per-server:
    server1:
      header: {}
      footer: {}
    server2;server3:
      header: {}

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Tablist-name-formatting
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds: {}
  disable-in-servers:
  - devmisc
  - devrpg
  - devia

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags
scoreboard-teams:
  enabled: false
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist
  sorting-types:
    - "PLACEHOLDER_A_TO_Z:%player%"
  case-sensitive-sorting: false
  disable-in-worlds: {}
  disable-in-servers: {}
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode
  unlimited-nametag-mode:
    enabled: false
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    space-between-lines: 0.22
    disable-in-worlds: {}
    disable-in-servers: {}
    dynamic-lines:
      - abovename
      - nametag #the original one, combination of tagprefix + customtagname + tagsuffix
      - belowname
      - another
    static-lines:
      myCustomLine: 0.66

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Yellow-number
yellow-number-in-tablist:
  enabled: false
  value: "%ping%"
  disable-in-worlds: {}
  disable-in-servers: {}

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Global-playerlist
global-playerlist:
  enabled: true
  display-others-as-spectators: false
  display-vanished-players-as-spectators: false
  isolate-unlisted-servers: false
  update-latency: false
  spy-servers: {}
  server-groups: {}

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Belowname
belowname-objective:
  enabled: false
  number: "%player_health%"
  text: "&c❤"
  disable-in-worlds: {}
  disable-in-servers:
  # 生产服务器
  - act
  - hub
  - build
  - speed
  # 开发服务器
  - devmisc
  - devrpg
  - devia

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Spectator-fix
prevent-spectator-effect:
  enabled: false

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Bossbar
bossbar:
  enabled: true
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds: {}
  disable-in-servers:
  - act
  - hub
  - build
  - speed
  - devmisc
  - devrpg
  - devia
  bars:
    mmobars:
      style: "PROGRESS"
      color: "WHITE"
      progress: "100"
      text: "&c❤ %mmocore_health%/%mmocore_max_health% &f| %mmocore_mana_icon% %mmocore_mana%/%mmocore_stat_max_mana% &f| &6❖ %mmocore_stellium%/%mmocore_stat_max_stellium% &f| &7⛨ %mmocore_stat_armor%&8(&7%mmocore_stat_armor_toughness%&8)"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds: {}
  disable-in-servers: {}
  scoreboards:
    admin:
      # Only players with tab.scoreboard.admin can see this scoreboard, others will see scoreboard1
      display-condition: "permission:tab.scoreboard.admin"
      title: "Admin scoreboard"
      lines:
        - "&6Online:"
        - "* &eOnline&7: &f%online%&7/&4%maxplayers%"
        - "* &eCurrent World&7: &f%worldonline%"
        - " "
        - "&6Server Info:"
        - "* &bTPS&7: %tps%"
        - "* &bUptime&7: &f%server_uptime%"
        - "* &bMemory&7: &f%memory-used%&7/&4%memory-max%"
    # scoreboard1:
    #   title: "Default"
    #   lines:
    #     - "%animation:dividing%"
    #     - "&6My Stats:"
    #     - "* &eKills&7: &f%statistic_player_kills%"
    #     - "* &eDeaths&7: &f%statistic_deaths%"
    #     - "* &eHealth&7: &f%health%"
    #     - " "
    #     - "&6Personal Info:"
    #     - "* &bRank&7: &f%group%"
    #     - "* &bPing&7: &f%ping%&7ms"
    #     - "* &bWorld&7: &f%world%"
    #     - "%animation:dividing%"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Ping-Spoof
ping-spoof:
  enabled: false
  value: 0

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Pet-name-fix
fix-pet-names:
  enabled: false

placeholders:
  date-format: "yyyy.MM.dd"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0
  register-tab-expansion: false

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements
placeholder-output-replacements:
  "%essentials_vanished%":
    "yes": "&7| 已隐藏"
    "no": ""
  "%essentials_nickname%":
    "%essentials_nickname%": "%player%" # placeholder did not parse correctly, show real name instead
    
  # bukkit-only placeholders used in default groups.yml, doing this as a fix
  "%afk%":
    "%afk%": "" 
  "%vault-prefix%":
    "%vault-prefix%" : ""
  "%vault-suffix%":
    "%vault-suffix%" : ""

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders
conditions:
  nick: # use it with %condition:nick%
    conditions:
      - "%player%=%essentials_nickname%"
    yes: "%player%"
    no: "~%essentials_nickname%"

placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_factionsuuid_relation_color%": 1000

# assigning groups by permission nodes instead of taking them from permission plugin
assign-groups-by-permissions: false

# if the option above is true, all groups are taken based on permissions and the one higher in this list is used as primary
# Warning! This is not sorting list and has nothing to do with sorting players in tablist!
primary-group-finding-list: {}

debug: false

# https://github.com/NEZNAMY/TAB/wiki/MySQL
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: bungeecord
  username: minecraft
  password: ''

use-bukkit-permissions-manager: false

```

**Comment by Akiranya** [comment]
Here is more error logs: https://pastebin.com/Dzeac7Ai

**Comment by NEZNAMY** [comment]
LD = LibsDisguises, not TAB.
