### ISSUE TITLE
Error when using TAB-Bridge-2.0.1

### ISSUE THREAD

**Issue by makksgam** [NEZNAMY/TAB#562]
### Server version

Paper 1.12.2

### TAB version

Tab 3.1.1 , Tab-Bridge 2.0.1

### Stack trace

[20:43:26] [Craft Scheduler Thread - 67/WARN]: java.sql.SQLSyntaxErrorException: Unknown column 'expires_at' in 'where clause'
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at com.niko.auction.sql.AuctionSQL.fixStorageItemsExpiration(AuctionSQL.java:244)
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at com.niko.auction.sql.AuctionSQL.getStorageItems(AuctionSQL.java:186)
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at com.niko.auction.Auction$1.lambda$onPlayerJoin$0(Auction.java:97)
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[20:43:26] [Craft Scheduler Thread - 67/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)

### Steps to reproduce (if known)

1. Put TAB and Tab-Bridge on the server and TAB on bungeecord
2. Connect the database and turn on the server

### Additional info

I want to combine the tab with Hub-1 and Server-1 so that all players are shown there. I did this, I put on Server-1 and Hub-1, Tab-Bridge and Tab plugins and put TAB on bungeecord, connected Tab with mysql, but placeholders are not shown in my tab and writes an error in the console. I hope for your help, read the documentation and did not understand well because I used a translator

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
[20:43:26] [Craft Scheduler Thread - 67/WARN]: at com.niko.auction.Auction$1.lambda$onPlayerJoin$0(Auction.java:97) 

Auction?

**Comment by makksgam** [comment]
This is a plugin for Auctions so that players sell their items and so on. Is that the problem?

**Comment by NEZNAMY** [comment]
It clearly is. TAB is not anywhere in that error.

**Comment by makksgam** [comment]
Sorry I'm stupid
