### ISSUE TITLE
TeamManager setPrefix NullPointerException

### ISSUE THREAD

**Issue by ChanceSD** [NEZNAMY/TAB#585]
### Server version

1.18.2

### TAB version

3.1.1

### Stack trace

[09:42:01 WARN]: Exception in thread "pool-92-thread-1" java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.Property.setTemporaryValue(String)" because the return value of "me.neznamy.tab.api.TabPlayer.getProperty(String)" is null
[09:42:01 WARN]:        at TAB v3.1.1.jar//me.neznamy.tab.shared.features.nametags.NameTag.setPrefix(NameTag.java:318)
[09:42:01 WARN]:        at PvPManager.jar//nc.ej.b(SourceFile:125)
[09:42:01 WARN]:        at PvPManager.jar//nc.ej.a(SourceFile:232)
[09:42:01 WARN]:        at PvPManager.jar//nc.ej.c(SourceFile:108)
[09:42:01 WARN]:        at PvPManager.jar//nc.ej.<init>(SourceFile:45)
[09:42:01 WARN]:        at PvPManager.jar//me.NoChance.PvPManager.PvPlayer.a(SourceFile:400)
[09:42:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[09:42:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[09:42:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Steps to reproduce (if known)

I received this stack trace from a user of my plugin, I hook into the TAB API and it seems to happen when using setPrefix on TeamManager. 

### Additional info

I'm not sure if this is a bug coming from TAB or something I can/should guard against. I do have checks that TeamManager is not null as well as a TabPlayer null check. The prefix String being set is also not null, if I missed something please let me know.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
When are you calling this? On join? There's a chance the player is still being loaded by the plugin asynchronously.

**Comment by ChanceSD** [comment]
Oh, yes it seems to have been on join that this happened. I never had any issues before though, maybe that specific server was slower loading the player or something, so I guess the only solution is to wait a few ticks before setting the prefix?

**Comment by NEZNAMY** [comment]
Or listen to [PlayerLoadEvent](https://github.com/NEZNAMY/TAB/wiki/Developer-API#events)

**Comment by ChanceSD** [comment]
Alright thanks, that would definitely be much better, will give it a try
