### ISSUE TITLE
Packet encoding of packet ERROR

### ISSUE THREAD

**Issue by IPECTER** [NEZNAMY/TAB#595]
### Server version

PURPUR 1.18.2

### TAB version

3.1.1

### Describe the bug

If an error occurs, all players will be disconnected.
I asked all the plugin I using involved in **DataWatcher**, **Packet** about this, but it wasn't bug of those plugins...
I have been told that this is likely to be a problem with Armor Stand Packet Spawn.
If it is not TAB's bug, please let me know the relevant information... 
I've been suffering from this for half a year

### Expected behavior

hmm...

### Steps to reproduce

JUST PLAY WITH SOME PLUGIN

### Additional info

[20:23:13] [Netty Epoll Server IO #2/ERROR]: Packet encoding of packet ID 77 threw (skippable? false)
java.lang.NullPointerException: Cannot invoke "net.minecraft.network.syncher.DataWatcher$Item.a()" because "entry" is null
at net.minecraft.network.syncher.SynchedEntityData.writeDataItem(SynchedEntityData.java:223) ~[?:?]
at net.minecraft.network.syncher.SynchedEntityData.pack(SynchedEntityData.java:168) ~[?:?]
at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:33) ~[?:?]
at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[prismarine-1.18.2.jar:git-Prismarine-"d609343"]
at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[prismarine-1.18.2.jar:git-Prismarine-"d609343"]
at jdk.internal.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at com.viaversion.viaversion.util.PipelineUtil.callEncode(PipelineUtil.java:93) ~[ViaVersion-4.2.2-SNAPSHOT.jar:?]
at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:71) ~[ViaVersion-4.2.2-SNAPSHOT.jar:?]
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at de.sportkanone123.clientdetector.spigot.packetevents.injector.modern.PlayerChannelHandlerModern.write(PlayerChannelHandlerModern.java:54) ~[ClientDetector.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:88) ~[TAB.v3.1.1.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at xuan.cat.fartherviewdistance.code.branch.v18.Branch_18_Minecraft$1.write(Branch_18_Minecraft.java:102) ~[FartherViewDistance-LATEST-[9.2.3].jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:195) ~[ProtocolLib.jar:?]
at net.minecraft.network.Connection.doSendPacket(Connection.java:462) ~[?:?]
at net.minecraft.network.Connection.lambda$writePacket$10(Connection.java:431) ~[?:?]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Disable unlimited nametag mode and try again.

**Comment by IPECTER** [comment]
> Disable unlimited nametag mode and try again.
okay Ill try!
This error may take a few days to check because it sometimes appears

**Comment by IPECTER** [comment]
> 

fixed thx!
but.... I must use unlimited nametag.... to change Nickname and Health display...
Can you fix it quickly?

**Comment by NEZNAMY** [comment]
No, because I don't have enough info to fix it.

**Comment by IPECTER** [comment]
> No, because I don't have enough info to fix it. On top of that, according to the stack trace you are not using purpur, but something else. The mappings are also incorrect, these are mojang mappings, which public server jars don't use and which TAB doesn't support.

But this is also a problem with PURPUR, PAPER

**Comment by NEZNAMY** [comment]
Use one of them and send new error.

**Comment by IPECTER** [comment]
I said it last time, this error happens sometimes, so it depends on luck. It could take a few days
If there is an error, I will send it right away

**Comment by IPECTER** [comment]
https://pastebin.com/3fHwMDhC
here!!! finally!!!!

**Comment by NEZNAMY** [comment]
Remove XuanCatAPI or how it's called and try again.

**Comment by IPECTER** [comment]
![image](https://user-images.githubusercontent.com/80433772/168253425-eb6a6e41-4504-4117-8633-9545587ac80d.png)
umm......

**Comment by NEZNAMY** [comment]
Delete farther view distance plugin temporarily and try again.

**Comment by IPECTER** [comment]
I forgot
I was so busy that I didn't have time to test it
Ill test tonight

**Comment by IPECTER** [comment]
???????????
I didnt anything...


before 15 days (Enabled Unlimited NameTag) (Error often occur)
https://pastebin.com/3fHwMDhC

now (Disabled Unlimited NameTag) (There was no error for 15 days, but it suddenly happened today)
https://pastebin.com/ne3kUWVe

**Comment by IPECTER** [comment]
Ill try more test without FVD

**Comment by NEZNAMY** [comment]
That means TAB is not causing this error, assuming both unlimited nametag mode and fix-pet-names options are disabled.

**Comment by IPECTER** [comment]
> 

I think it is TAB problem....
I finally finished test.

all run with other packet plugin (like FVD)

1. Off Unlimited-NameTag + Off Fix-Pet-Name = No Bug
2. On Unlimited-NameTag + On Fix-Pet-Name = Often Bug
3. Off Unlimited-NameTag + On Fix-Pet-Name = Once in a while Bug

**Comment by NEZNAMY** [comment]
I asked you to try without fatherviewdistance, not with.

**Comment by IPECTER** [comment]
> I asked you to try without fatherviewdistance, not with.

oh.... sry I forgot
Ill test again without fatherviewdistance

**Comment by NEZNAMY** [comment]
Any news @IPECTER ?

**Comment by IPECTER** [comment]
Last time I updated TAB and PURPUR, I have been testing it with various settings in copy Test server so far So far, there is no problem. It seems to have been fixed!!
Thx for help!
