### ISSUE TITLE
[TAB-Bridge] Unlimited nametag error in servers

### ISSUE THREAD

**Issue by KahpotVanilla** [NEZNAMY/TAB#601]
### Server version

Waterfall

### TAB version

3.1.0

### Stack trace

[22:38:39 WARN]: java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.bridge.bukkit.features.unlimitedtags.ArmorStandManager.getArmorStand(String)" because the return value of "me.neznamy.tab.bridge.bukkit.features.unlimitedtags.BridgeNameTagX.getArmorStandManager(me.neznamy.tab.bridge.bukkit.BridgePlayer)" is null
[22:38:39 WARN]:        at TAB-Bridge v2.0.0.jar//me.neznamy.tab.bridge.bukkit.features.unlimitedtags.BridgeNameTagX.readMessage(BridgeNameTagX.java:219)
[22:38:39 WARN]:        at TAB-Bridge v2.0.0.jar//me.neznamy.tab.bridge.bukkit.DataBridge.processPluginMessage(DataBridge.java:122)
[22:38:39 WARN]:        at TAB-Bridge v2.0.0.jar//me.neznamy.tab.bridge.bukkit.BukkitBridge.lambda$onPluginMessageReceived$0(BukkitBridge.java:88)
[22:38:39 WARN]:        at TAB-Bridge v2.0.0.jar//me.neznamy.tab.bridge.bukkit.DataBridge.lambda$submitTask$4(DataBridge.java:193)
[22:38:39 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[22:38:39 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[22:38:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:38:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:38:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Steps to reproduce (if known)

1. Install TAB in your proxy
2. Install TAB-Bridge in your backend server
3. Enable "unlimited-nametag-mode" in TAB config.yml
4. Restarting proxy
5. Watch for console errors in one of the server

### Additional info

It happens only when I enable the "unlimited-nametag-mode".

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
You are outdated.
