### ISSUE TITLE
Header & Footer error

### ISSUE THREAD

**Issue by D4rkSoul67** [NEZNAMY/TAB#637]
### Server version

Spigot 1.16.5

### TAB version

3.1.2

### Stack trace

[20:45:18] [Server thread/INFO]: [TAB] [TAB v3.1.2] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[20:45:18] [Server thread/INFO]: [TAB] java.nio.charset.MalformedInputException: Input length = 1
[20:45:18] [Server thread/INFO]: [TAB]  at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
[20:45:18] [Server thread/INFO]: [TAB]  at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:352)
[20:45:18] [Server thread/INFO]: [TAB]  at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
[20:45:18] [Server thread/INFO]: [TAB]  at java.base/java.io.InputStreamReader.read(InputStreamReader.java:178)
[20:45:18] [Server thread/INFO]: [TAB]  at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
[20:45:18] [Server thread/INFO]: [TAB]  at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
[20:45:18] [Server thread/INFO]: [TAB]  at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
[20:45:18] [Server thread/INFO]: [TAB]  at java.base/java.nio.file.Files.readAllLines(Files.java:3399)
[20:45:18] [Server thread/INFO]: [TAB]  at java.base/java.nio.file.Files.readAllLines(Files.java:3436)
[20:45:18] [Server thread/INFO]: [TAB]  at me.neznamy.tab.api.config.ConfigurationFile.detectHeader(ConfigurationFile.java:401)
[20:45:18] [Server thread/INFO]: [TAB]  at me.neznamy.tab.api.config.ConfigurationFile.<init>(ConfigurationFile.java:69)
[20:45:18] [Server thread/INFO]: [TAB]  at me.neznamy.tab.api.config.YamlConfigurationFile.<init>(YamlConfigurationFile.java:53)
[20:45:18] [Server thread/INFO]: [TAB]  at me.neznamy.tab.shared.config.Configs.<init>(Configs.java:25)
[20:45:18] [Server thread/INFO]: [TAB]  at me.neznamy.tab.shared.TAB.load(TAB.java:155)
[20:45:18] [Server thread/INFO]: [TAB]  at me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:22)
[20:45:18] [Server thread/INFO]: [TAB]  at me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:54)
[20:45:18] [Server thread/INFO]: [TAB]  at me.neznamy.tab.platforms.bukkit.Main$TABCommand.onCommand(Main.java:113)
[20:45:18] [Server thread/INFO]: [TAB]  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:45:18] [Server thread/INFO]: [TAB]  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[20:45:18] [Server thread/INFO]: [TAB]  at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:761)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1936)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1779)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1732)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970)
[20:45:18] [Server thread/INFO]: [TAB]  at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
[20:45:18] [Server thread/INFO]: [TAB]  at java.base/java.lang.Thread.run(Thread.java:831)

### Steps to reproduce (if known)

![image_2022-07-02_204828662](https://user-images.githubusercontent.com/65168541/177011135-d287af92-0494-4129-b3aa-350b38509265.png)
![image](https://user-images.githubusercontent.com/65168541/177011158-8ede85f2-ca0d-4374-bbc7-9c4463b32a8d.png)
![image](https://user-images.githubusercontent.com/65168541/177011166-1afefc48-a048-410d-8749-cf9fbbc29f64.png)
![image](https://user-images.githubusercontent.com/65168541/177011175-6f171979-a9ca-44b8-9e39-a2123685be9a.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Set encoding to UTF-8.

**Comment by D4rkSoul67** [comment]
Thank you! It works perfect now.
