### ISSUE TITLE
Player cannot be null

### ISSUE THREAD

**Issue by AntonErlandsson** [NEZNAMY/TAB#639]
### Server version

Paper 1.19

### TAB version

3.1.2

### Stack trace

`[02:04:47 WARN]: org.bukkit.command.CommandException: Unhandled exception executing command 'tab' in plugin TAB v3.1.2
[02:04:47 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
[02:04:47 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[02:04:47 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:907)
[02:04:47 WARN]:        at Maintenance-4.0.1.jar//eu.kennytv.maintenance.spigot.MaintenanceSpigotPlugin.executeConsoleCommand(MaintenanceSpigotPlugin.java:149)
[02:04:47 WARN]:        at Maintenance-4.0.1.jar//eu.kennytv.maintenance.core.MaintenancePlugin.setMaintenance(MaintenancePlugin.java:98)
[02:04:47 WARN]:        at Maintenance-4.0.1.jar//eu.kennytv.maintenance.core.command.subcommand.ToggleCommand.execute(ToggleCommand.java:40)
[02:04:47 WARN]:        at Maintenance-4.0.1.jar//eu.kennytv.maintenance.core.command.MaintenanceCommand.execute(MaintenanceCommand.java:106)
[02:04:47 WARN]:        at Maintenance-4.0.1.jar//eu.kennytv.maintenance.spigot.command.MaintenanceSpigotCommand.onCommand(MaintenanceSpigotCommand.java:44)
[02:04:47 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:04:47 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[02:04:47 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:907)
[02:04:47 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2376)
[02:04:47 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2147)
[02:04:47 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:04:47 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[02:04:47 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[02:04:47 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1358)
[02:04:47 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[02:04:47 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[02:04:47 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1335)
[02:04:47 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1328)
[02:04:47 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[02:04:47 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1306)
[02:04:47 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
[02:04:47 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[02:04:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[02:04:47 WARN]: Caused by: java.lang.IllegalArgumentException: player cannot be null
[02:04:47 WARN]:        at TAB.v3.1.2.jar//me.neznamy.tab.shared.features.scoreboard.ScoreboardManagerImpl.showScoreboard(ScoreboardManagerImpl.java:259)
[02:04:47 WARN]:        at TAB.v3.1.2.jar//me.neznamy.tab.shared.command.ScoreboardCommand.show(ScoreboardCommand.java:103)
[02:04:47 WARN]:        at TAB.v3.1.2.jar//me.neznamy.tab.shared.command.ScoreboardCommand.execute(ScoreboardCommand.java:39)
[02:04:47 WARN]:        at TAB.v3.1.2.jar//me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:54)
[02:04:47 WARN]:        at TAB.v3.1.2.jar//me.neznamy.tab.platforms.bukkit.Main$TABCommand.onCommand(Main.java:113)
[02:04:47 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:04:47 WARN]:        ... 25 more`

### Steps to reproduce (if known)

1. Create another scoreboard
2. run `tab scoreboard show <SCOREBOARD>` in another plugin (only tried [Maintenance](https://www.spigotmc.org/resources/maintenance-bungee-and-spigot-support.40699/))

### Additional info

When i tried to switch to another scoreboard by running a command "with" the maintenance plugin i get the error.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Chris6ix** [comment]
"I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform" are you really sure?

The Wiki clearly states: "The plugin supports all versions from 1.5.x to 1.18.2."

And you're trying to run it on 1.19 -_-

**Comment by AntonErlandsson** [comment]
Well...

The latest release says that it supports 1.19 and so I thought you just hadn't updated that page... but alright.

**Comment by Chris6ix** [comment]
True, that needs to be updated then, I forgot that TAB has a 1.19 build and I only looked at the wiki because it says "I have read the Compatibility wiki page"...

**Comment by Tanguygab** [comment]
you need to specify a player to send the scoreboard to, otherwise it'll try to take the player executing the command, and since it's the maintenance plugin, it's not a player and thus is null.
![Screenshot_20220703-080153_Opera.jpg](https://user-images.githubusercontent.com/45695833/177027042-c900ef5e-e2e8-42bd-b5a0-2891c8ecbf6b.jpg)

**Comment by AntonErlandsson** [comment]
How can i show it to everyone then?

**Comment by Tanguygab** [comment]
I don't think that's possible with the current commands

**Comment by AntonErlandsson** [comment]
Hmm okay... I guess I will just show it to myself for now then. It isn't super important but it would be nice to be able to!

**Comment by Tanguygab** [comment]
Understandable, I'll try to see if I can make a PR to add, once I get out of my bed of course 😅...

**Comment by AntonErlandsson** [comment]
👍

**Comment by Tanguygab** [comment]
Added `*|` in `/tab scoreboard show <scoreboard>*` to send it to all players, you can try my build here.
https://github.com/Tanguygab/TAB/actions/runs/2604363252
I'll open a PR

**Comment by Tanguygab** [comment]
Hey @AntonErlandsson, do you want to make all players online have the new scoreboard, or online players + players that join afterwards?

**Comment by AntonErlandsson** [comment]
Everyone. So everyone that is online and everyone that is joining afterwards.

**Comment by Tanguygab** [comment]
alright, NEZ is making some changes so the `/tab scoreboard announce` command do just that.
It does require a duration, but you can just put an extremely long amount and it shouldn't be a problem

**Comment by AntonErlandsson** [comment]
Alright awesome! Should I close this issue now?

**Comment by NEZNAMY** [comment]
I will be close it once next version fixing this error is out. You can close it sooner if you wish.
