### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by editon96** [NEZNAMY/TAB#642]
### Server version

Purpur 1.19 and Velocity 3.1.2 Build 1.6.1

### TAB version

v3.1.2

### Stack trace

[21:40:48 ERROR]: Unable to load plugin plugins/TAB v3.1.2.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file TAB v3.1.2.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:151) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:61) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:92) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:346) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:224) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]

### Additional info

You Latest Plugin dont support Velocity.
I need it for my Server.

Maybe you check protocolize-velocity if that help?

Hope get Support back dont found an alternative....

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by editon96** [comment]
[21:41:12 INFO] [TAB]: [TAB v3.1.2] Failed to initialize bungee internal fields
[21:41:12 INFO] [TAB]: java.lang.ClassNotFoundException: net.md_5.bungee.connection.InitialHandler
[21:41:12 INFO] [TAB]:  at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:100)
[21:41:12 INFO] [TAB]:  at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:78)
[21:41:12 INFO] [TAB]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[21:41:12 INFO] [TAB]:  at java.base/java.lang.Class.forName0(Native Method)
[21:41:12 INFO] [TAB]:  at java.base/java.lang.Class.forName(Class.java:375)
[21:41:12 INFO] [TAB]:  at me.neznamy.tab.platforms.bungeecord.BungeeTabPlayer.<clinit>(BungeeTabPlayer.java:38)
[21:41:12 INFO] [TAB]:  at me.neznamy.tab.platforms.bungeecord.BungeeEventListener.lambda$onSwitch$1(BungeeEventListener.java:43)
[21:41:12 INFO] [TAB]:  at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:113)
[21:41:12 INFO] [TAB]:  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[21:41:12 INFO] [TAB]:  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[21:41:12 INFO] [TAB]:  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:41:12 INFO] [TAB]:  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:41:12 INFO] [TAB]:  at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Tanguygab** [comment]
Velocity support won't come back. More details here: https://github.com/NEZNAMY/TAB/pull/632 and here https://gist.github.com/NEZNAMY/21c1aabe57a0a462ee175386c510fdf8

**Comment by DrWurzeli** [comment]
you were told this on discord as well in your ticket.
