### ISSUE TITLE
Exception error in console when server stop or start

### ISSUE THREAD

**Issue by Vehzx** [NEZNAMY/TAB#648]
### Server version

1.19 git-Paper-50

### TAB version

3.1.2

### Stack trace

`[03:24:40 INFO]: [TAB] Disabling TAB v3.1.2
[03:24:40 WARN]: Exception in thread "OkHttp Dispatcher" java.lang.IllegalStateException: zip file closed
[03:24:40 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[03:24:40 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[03:24:40 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[03:24:40 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[03:24:40 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
[03:24:40 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[03:24:40 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[03:24:40 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[03:24:40 INFO]: [TAB] Disabled in 1ms
[03:24:40 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[03:24:40 WARN]:        at CraftingStore-2.8.1-RELEASE.jar//net.craftingstore.libraries.socket.engineio.client.transports.WebSocket$1.onFailure(WebSocket.java:104)
[03:24:40 WARN]:        at CraftingStore-2.8.1-RELEASE.jar//net.craftingstore.libraries.okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
[03:24:40 WARN]:        at CraftingStore-2.8.1-RELEASE.jar//net.craftingstore.libraries.okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:211)
[03:24:40 WARN]:        at CraftingStore-2.8.1-RELEASE.jar//net.craftingstore.libraries.okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
[03:24:40 WARN]:        at CraftingStore-2.8.1-RELEASE.jar//net.craftingstore.libraries.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
[03:24:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[03:24:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[03:24:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

### Steps to reproduce (if known)

Not too sure, it just seems to appear when turning server on or off, I don't think it's affecting gameplay in any way it's just an error thrown into console, if this is fixable and you could point me in the right direction of how to fix it that would be great as it's a little annoying seeing this error everytime I start or stop the server.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
`[03:24:40 WARN]: at CraftingStore-2.8.1-RELEASE.jar//net.craftingstore.libraries.socket.engineio.client.transports.WebSocket$1.onFailure(WebSocket.java:104)`
Wrong plugin.
