### ISSUE TITLE
Magma DO NOT work

### ISSUE THREAD

**Issue by sall0-0p** [NEZNAMY/TAB#653]
### Server version

Magma 1.18.2

### TAB version

3.1.2

### Stack trace

[22:11:54] [Server thread/INFO] [/]: [TAB] Server version: 1.18.2 (v1_18_R2)
[22:11:54] [Server thread/INFO] [/]: [TAB] Your server version is marked as compatible, but a compatibility issue was found. Please report the error below (include your server version & fork too)
[22:11:54] [Server thread/ERROR] [me.ne.ta.pl.bu.Main/]: [TAB] 
java.lang.ClassNotFoundException: No class found with possible names [net.minecraft.EnumChatFormat, EnumChatFormat]
        at me.neznamy.tab.platforms.bukkit.nms.NMSStorage.getNMSClass(NMSStorage.java:456) ~[?:?] {}
        at me.neznamy.tab.platforms.bukkit.nms.NMSStorage.<init>(NMSStorage.java:38) ~[?:?] {}
        at me.neznamy.tab.platforms.bukkit.Main.isVersionSupported(Main.java:78) ~[?:?] {}
        at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:32) ~[?:?] {}
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.1.54-universal.jar%2365!/:?] {re:classloading}
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[forge-1.18.2-40.1.54-universal.jar%2365!/:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge-1.18.2-40.1.54-universal.jar%2365!/:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[forge-1.18.2-40.1.54-universal.jar%2365!/:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[forge-1.18.2-40.1.54-universal.jar%2365!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:448) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:357) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:244) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:757) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:253) ~[server-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
[22:11:54] [Server thread/INFO] [me.ne.ta.pl.bu.Main/]: [TAB] Disabling TAB v3.1.2

### Steps to reproduce (if known)

Just launch server

### Additional info

Using Magma Hybrid Core. When starting server (1.18.2) it just enables and disables plugin.
I tried some past versions that support 1.18.2, they have same problem

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
I am not able to start the server, I get a different error about a missing library each time I start the server.
![image](https://user-images.githubusercontent.com/6338394/179848477-ee87da62-fac3-4e8a-bda5-5e65cc847901.png)

**Comment by NEZNAMY** [comment]
Magma 1.18.2 uses mojang mappings for classes. TAB only supports bukkit mappings. If popular server software (spigot / paper) also moves to mojang mappings, I will add support for it. I will not make such a step only for magma.
