### ISSUE TITLE
Paper 1.19.1 Enable Error

### ISSUE THREAD

**Issue by norhu1130** [NEZNAMY/TAB#663]
### Server version

Paper 1.19.1

### TAB version

3.1.2

### Stack trace

[10:54:03 INFO]: [TAB] Your server version is marked as compatible, but a compatibility issue was found. Please report the error below (include your server version & fork too)
[10:54:03 ERROR]: [TAB]
java.lang.NoSuchMethodException: net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(net.minecraft.network.chat.IChatBaseComponent,int)
        at java.lang.Class.getConstructor0(Class.java:3585) ~[?:?]
        at java.lang.Class.getConstructor(Class.java:2271) ~[?:?]
        at me.neznamy.tab.platforms.bukkit.nms.NMSStorage.initializeChatPacket(NMSStorage.java:257) ~[TAB v3.1.2.jar:?]
        at me.neznamy.tab.platforms.bukkit.nms.NMSStorage.<init>(NMSStorage.java:216) ~[TAB v3.1.2.jar:?]
        at me.neznamy.tab.platforms.bukkit.Main.isVersionSupported(Main.java:78) ~[TAB v3.1.2.jar:?]
        at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:32) ~[TAB v3.1.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.1.jar:git-Paper-85]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-85]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by MrGraycat** [comment]
1.19.1 changed a lot of chat packets

This means TAB has to be updated in order for it to work with 1.19.1 so please allow NEZNAMY to update it (which takes time).

**Comment by soshimee** [comment]
It's not NEZMANY's fault, but Minecraft's fault.

**Comment by NEZNAMY** [comment]
"I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform"
Hmmmmm...

**Comment by norhu1130** [comment]
> "I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform" Hmmmmm...

OOPS Sorry
