### ISSUE TITLE
Error when enabling scoreboard teams

### ISSUE THREAD

**Issue by ccyounga** [NEZNAMY/TAB#664]
### Server version

Paper 1.18.2

### TAB version

3.1.2

### Describe the bug

I turn on the scoreboard teams function to sort players in tabs, but the plugin immediately throws an error and turns off.

### Expected behavior

Working plugin, correct sorting of players in tab.

### Steps to reproduce

scoreboard-teams:
  enabled: true

/tab reload

### Additional info

I tried to rollback the tab plugin version, the error remains. My guess is that my custom faction plugin, which used to have some connection to vanilla teams, has crashed since it stopped removing factions, behaving strangely.

Here is the error: https://www.toptal.com/developers/hastebin/ozacigapib.md

[09:19:05 INFO]: [TAB] [TAB v3.1.2] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[09:19:05 INFO]: [TAB] java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 8
[09:19:05 INFO]: [TAB]  at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[09:19:05 INFO]: [TAB]  at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[09:19:05 INFO]: [TAB]  at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[09:19:05 INFO]: [TAB]  at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[09:19:05 INFO]: [TAB]  at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[09:19:05 INFO]: [TAB]  at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
[09:19:05 INFO]: [TAB]  at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
[09:19:05 INFO]: [TAB]  at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4589)
[09:19:05 INFO]: [TAB]  at java.base/java.lang.String.substring(String.java:2703)
[09:19:05 INFO]: [TAB]  at tab-v3_1_2.jar//me.neznamy.tab.shared.features.sorting.types.Placeholder.getPlaceholder(Placeholder.java:42)
[09:19:05 INFO]: [TAB]  at tab-v3_1_2.jar//me.neznamy.tab.shared.features.sorting.types.Placeholder.<init>(Placeholder.java:27)
[09:19:05 INFO]: [TAB]  at tab-v3_1_2.jar//me.neznamy.tab.shared.features.sorting.Sorting.compile(Sorting.java:99)
[09:19:05 INFO]: [TAB]  at tab-v3_1_2.jar//me.neznamy.tab.shared.features.sorting.Sorting.<init>(Sorting.java:57)
[09:19:05 INFO]: [TAB]  at tab-v3_1_2.jar//me.neznamy.tab.shared.features.nametags.NameTag.<init>(NameTag.java:23)
[09:19:05 INFO]: [TAB]  at tab-v3_1_2.jar//me.neznamy.tab.shared.features.nametags.unlimited.NameTagX.<init>(NameTagX.java:37)
[09:19:05 INFO]: [TAB]  at tab-v3_1_2.jar//me.neznamy.tab.platforms.bukkit.features.unlimitedtags.BukkitNameTagX.<init>(BukkitNameTagX.java:30)
[09:19:05 INFO]: [TAB]  at tab-v3_1_2.jar//me.neznamy.tab.platforms.bukkit.BukkitPlatform.loadFeatures(BukkitPlatform.java:92)
[09:19:05 INFO]: [TAB]  at tab-v3_1_2.jar//me.neznamy.tab.shared.TAB.load(TAB.java:158)
[09:19:05 INFO]: [TAB]  at tab-v3_1_2.jar//me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:22)
[09:19:05 INFO]: [TAB]  at tab-v3_1_2.jar//me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:54)
[09:19:05 INFO]: [TAB]  at tab-v3_1_2.jar//me.neznamy.tab.platforms.bukkit.Main$TABCommand.onCommand(Main.java:113)
[09:19:05 INFO]: [TAB]  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:19:05 INFO]: [TAB]  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[09:19:05 INFO]: [TAB]  at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[09:19:05 INFO]: [TAB]  at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2307)
[09:19:05 INFO]: [TAB]  at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2118)
[09:19:05 INFO]: [TAB]  at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[09:19:05 INFO]: [TAB]  at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[09:19:05 INFO]: [TAB]  at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[09:19:05 INFO]: [TAB]  at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[09:19:05 INFO]: [TAB]  at net.minecraft.server.TickTask.run(TickTask.java:18)
[09:19:05 INFO]: [TAB]  at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[09:19:05 INFO]: [TAB]  at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[09:19:05 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1400)
[09:19:05 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[09:19:05 INFO]: [TAB]  at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[09:19:05 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1377)
[09:19:05 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[09:19:05 INFO]: [TAB]  at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[09:19:05 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1348)
[09:19:05 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1230)
[09:19:05 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[09:19:05 INFO]: [TAB]  at java.base/java.lang.Thread.run(Thread.java:833)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by MrGraycat** [comment]
why don't you guys give developers TIME to update properly instead. either wait or help updating it...

**Comment by NEZNAMY** [comment]
Where's your config? This is caused by some sort of misconfiguration.

**Comment by ccyounga** [comment]
https://www.toptal.com/developers/hastebin/maganujifa.yaml

**Comment by NEZNAMY** [comment]
`    - "PLACEHOLDER:%player%"` is invalid. Sorting by predefined placeholder values requires the values. Read sorting page for more info.

**Comment by ccyounga** [comment]
Removed the line with - "PLACEHOLDER:%player%", now the plugin works correctly.
I don’t know if I added it myself some time ago, or one of my those admins tried to do something, but before the plugin worked fine. Thanks for the quick help!
