### ISSUE TITLE
Could not pass event NickChangeEvent to TAB v3.1.4

### ISSUE THREAD

**Issue by Ativ3k** [NEZNAMY/TAB#684]
### Server version

Spigot Paper 1.19.2

### TAB version

3.1.4

### Stack trace

When i change someone nick by console i get error:
`
 [Thu 12:29:25 INFO  Essentials] CONSOLE issued server command: /nick Ativ3k Ativ3k
- [Thu 12:29:25 ERROR Minecraft] Could not pass event NickChangeEvent to TAB v3.1.4
java.lang.NullPointerException: Cannot invoke "net.ess3.api.IUser.getUUID()" because the return value of "net.ess3.api.events.NickChangeEvent.getAffected()" is null
    at TAB.v3.1.4.jar//me.neznamy.tab.platforms.bukkit.BukkitPlaceholderRegistry$1.onNickChange(BukkitPlaceholderRegistry.java:97)
    at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
    at EssentialsX-2.19.6.jar//com.earth2me.essentials.commands.Commandnick.setNickname(Commandnick.java:112)
    at EssentialsX-2.19.6.jar//com.earth2me.essentials.commands.Commandnick.updatePlayer(Commandnick.java:60)
    at EssentialsX-2.19.6.jar//com.earth2me.essentials.commands.EssentialsLoopCommand.lambda$loopOfflinePlayers$0(EssentialsLoopCommand.java:22)
    at EssentialsX-2.19.6.jar//com.earth2me.essentials.commands.EssentialsLoopCommand.loopOfflinePlayersConsumer(EssentialsLoopCommand.java:62)
    at EssentialsX-2.19.6.jar//com.earth2me.essentials.commands.EssentialsLoopCommand.loopOfflinePlayers(EssentialsLoopCommand.java:22)
    at EssentialsX-2.19.6.jar//com.earth2me.essentials.commands.Commandnick.run(Commandnick.java:41)
    at EssentialsX-2.19.6.jar//com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180)
    at EssentialsX-2.19.6.jar//com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:812)
    at EssentialsX-2.19.6.jar//com.earth2me.essentials.Essentials.onCommand(Essentials.java:717)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer
  [Thu 12:29:25 INFO ] Zmieniono pseudonim gracza.
    
    

### Steps to reproduce (if known)

Change player nickname by console.

### Additional info

I use %essentialsnick% placeholder.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Are you nicking an offline player?

**Comment by Ativ3k** [comment]
> 

Player is online.

**Comment by NEZNAMY** [comment]
Then why is player null?

**Comment by NEZNAMY** [comment]
Stack trace shows the code ran through methods called `loopOfflinePlayers`.

**Comment by Ativ3k** [comment]
![image](https://user-images.githubusercontent.com/63321725/185375732-cbd23db9-754e-4706-a143-b2c0b968dee7.png)
Maybe console is detected like offlineplayer?

**Comment by NEZNAMY** [comment]
Are you nicking the console?

**Comment by Ativ3k** [comment]
i change my nick from console
when i change nick from server everything is ok

it's seems like is problem when "command sender" is console, not a player.

**Comment by NEZNAMY** [comment]
https://github.com/EssentialsX/Essentials/blob/1e0d7fb0a3545d15c3b0cc1d180b47551f98cb22/Essentials/src/main/java/net/ess3/api/events/NickChangeEvent.java well apparently it's an essentials bug.
