### ISSUE TITLE
unlimited-nametag-mode automatically turns on

### ISSUE THREAD

**Issue by heytek** [NEZNAMY/TAB#693]
### Server version

Purpur 1.16.5

### TAB version

3.1.4

### Stack trace

[11:36:27 INFO]: [TAB] §c[TAB v3.1.4] Feature BukkitNameTagX failed to process player XYZ
[11:36:27 INFO]: [TAB] §cjava.lang.NullPointerException: Cannot invoke "me.neznamy.tab.platforms.bukkit.features.unlimitedtags.BukkitArmorStandManager.spawn(me.neznamy.tab.api.TabPlayer)" because the return value of "me.neznamy.tab.platforms.bukkit.features.unlimitedtags.BukkitNameTagX.getArmorStandManager(me.neznamy.tab.api.TabPlayer)" is null
[11:36:27 INFO]: [TAB] §c       at me.neznamy.tab.platforms.bukkit.features.unlimitedtags.BukkitNameTagX.spawnArmorStands(BukkitNameTagX.java:84)
[11:36:27 INFO]: [TAB] §c       at me.neznamy.tab.platforms.bukkit.features.unlimitedtags.BukkitNameTagX.onJoin(BukkitNameTagX.java:70)
[11:36:27 INFO]: [TAB] §c       at me.neznamy.tab.shared.FeatureManagerImpl.onJoin(FeatureManagerImpl.java:125)
[11:36:27 INFO]: [TAB] §c       at me.neznamy.tab.platforms.bukkit.BukkitEventListener.lambda$onJoin$1(BukkitEventListener.java:51)
[11:36:27 INFO]: [TAB] §c       at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:112)
[11:36:27 INFO]: [TAB] §c       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[11:36:27 INFO]: [TAB] §c       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[11:36:27 INFO]: [TAB] §c       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[11:36:27 INFO]: [TAB] §c       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[11:36:27 INFO]: [TAB] §c       at java.base/java.lang.Thread.run(Thread.java:831)

### Steps to reproduce (if known)

I turn off the mode unlimited-nametag-mode in config.yml, when the players are on the server it will turn back on automatically, although it doesn't want to

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show plugin list.

**Comment by heytek** [comment]
![image](https://user-images.githubusercontent.com/79208581/186410677-ee961e03-6b72-4369-94f2-2ce0ff5e47ce.png)

**Comment by NEZNAMY** [comment]
eGlow is doing it. Remove it to confirm. Then, ask the author how to disable it.

**Comment by Tanguygab** [comment]
disable this https://github.com/MrGraycat/eGlow/blob/master/src/main/resources/Config.yml#L48

**Comment by heytek** [comment]
I do, but tab sets unlimited-nametag-mode to true after a while

**Comment by NEZNAMY** [comment]
Remove eGlow entirely and try again.

**Comment by NEZNAMY** [comment]
Then ask on eGlow support for help. This is now eGlow support.
