### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Jqnnies** [NEZNAMY/TAB#710]
### Server version

Purpur 1.19.2

### TAB version

3.1.4

### Describe the bug

[15:03:29 INFO]: [TAB] Unknown server version: 1.19.2-R0.1-SNAPSHOT! Plugin may not work correctly.
[15:03:29 INFO]: [TAB] [TAB v3.1.4] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[15:03:29 INFO]: [TAB] java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
[15:03:29 INFO]: [TAB]  at TAB.v3.1.4.jar//me.neznamy.tab.shared.features.layout.LayoutManager.loadLayouts(LayoutManager.java:57)
[15:03:29 INFO]: [TAB]  at TAB.v3.1.4.jar//me.neznamy.tab.shared.features.layout.LayoutManager.<init>(LayoutManager.java:32)
[15:03:29 INFO]: [TAB]  at TAB.v3.1.4.jar//me.neznamy.tab.shared.TAB.loadUniversalFeatures(TAB.java:238)
[15:03:29 INFO]: [TAB]  at TAB.v3.1.4.jar//me.neznamy.tab.platforms.bukkit.BukkitPlatform.loadFeatures(BukkitPlatform.java:97)
[15:03:29 INFO]: [TAB]  at TAB.v3.1.4.jar//me.neznamy.tab.shared.TAB.load(TAB.java:158)
[15:03:29 INFO]: [TAB]  at TAB.v3.1.4.jar//me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:43)
[15:03:29 INFO]: [TAB]  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:03:29 INFO]: [TAB]  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:03:29 INFO]: [TAB]  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548)
[15:03:29 INFO]: [TAB]  at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596)
[15:03:29 INFO]: [TAB]  at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510)
[15:03:29 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[15:03:29 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427)
[15:03:29 INFO]: [TAB]  at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:343)
[15:03:29 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1142)
[15:03:29 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[15:03:29 INFO]: [TAB]  at java.base/java.lang.Thread.run(Thread.java:833)

### Expected behavior

Should load

### Steps to reproduce

1. Use conditions in layouts
2. Restart server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Misconfiguration in layout.yml. Something is supposed to be a string but you made it an array.

**Comment by Jqnnies** [comment]
Would it be this?

`[TAB] Error message from yaml parser: while scanning for the next token
[15:16:41 INFO]: found character '%' that cannot start any token. (Do not use % for indentation)
[15:16:41 INFO]:  in 'reader', line 18, column 16:
[15:16:41 INFO]:         condition: %townyadvanced_town%=%townyadvan ... 
[15:16:41 INFO]:                    ^
[15:16:41 INFO]: [TAB] Suggestions to fix yaml syntax:
[15:16:41 INFO]: [TAB] - Wrap value in line 18 into quotes.
[15:16:41 INFO]: [TAB] Did not enable due to a broken configuration file.`

Been trying to get a placeholder to display with conditions, but it isn't working at all.

**Comment by NEZNAMY** [comment]
Read second to last line of the console paste you sent. This is not support, this is an issue tracker. Errors you are sending are caused by misconfiguration / yaml syntax errors.

**Comment by Jqnnies** [comment]
I did do that though.

**Comment by NEZNAMY** [comment]
This is not support, this is an issue tracker. If you have no bug to report, this will be closed.

**Comment by Jqnnies** [comment]
Then where do I file for support?

**Comment by NEZNAMY** [comment]
High-priority fast assistance with the plugin is provided on discord https://discord.gg/EaSvdk6 for buyers.
