### ISSUE TITLE
TAB isn't loading on Paper 1.19.2, received error to contact you.

### ISSUE THREAD

**Issue by KvasirQc** [NEZNAMY/TAB#718]
### Server version

Paper 1.19.2 build 160

### TAB version

3.1.2

### Stack trace

 [TAB] Enabling TAB v3.1.2
[02:22:02 INFO]: [TAB] Server version: 1.19.2 (v1_19_R1)
[02:22:02 INFO]: [TAB] Your server version is marked as compatible, but a compatibility issue was found. Please report the error below (include your server version & fork too)
[02:22:02 ERROR]: [TAB] 
java.lang.NoSuchMethodException: net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(net.minecraft.network.chat.IChatBaseComponent,int)
	at java.lang.Class.getConstructor0(Class.java:3585) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:2271) ~[?:?]
	at me.neznamy.tab.platforms.bukkit.nms.NMSStorage.initializeChatPacket(NMSStorage.java:257) ~[TAB.v3.1.2.jar:?]
	at me.neznamy.tab.platforms.bukkit.nms.NMSStorage.<init>(NMSStorage.java:216) ~[TAB.v3.1.2.jar:?]
	at me.neznamy.tab.platforms.bukkit.Main.isVersionSupported(Main.java:78) ~[TAB.v3.1.2.jar:?]
	at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:32) ~[TAB.v3.1.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-160]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-160]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-160]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-160]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-160]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-160]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-160]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:22:02 INFO]: [TAB] Disabling TAB v3.1.2

### Steps to reproduce (if known)

I'm trying to boot paper with TAB in 3.1.2 and receive this error to contact you guys about the error. 

I can't help much, the plugin isnt loading.

Thanks for your support and great plugin!

### Checklist

- [ ] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
update

**Comment by KvasirQc** [comment]
sorry -_- i just saw
