### ISSUE TITLE
TAB-Brigde

### ISSUE THREAD

**Issue by YodaZen** [NEZNAMY/TAB#731]
### Server version

Proxy

### TAB version

3.1.5

### Stack trace

17:00:54 [WARNING] Error loading plugin TAB-Bridge
java.lang.NoClassDefFoundError: org/bukkit/plugin/messaging/PluginMessageListener
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
    at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:340)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.messaging.PluginMessageListener
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    ... 13 more

### Steps to reproduce (if known)

The error happend on the proxy server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/196757861-1ba76ed8-edc8-4eb0-aa55-e68ad6ee404f.png)
someone didn't read the red text.
