### ISSUE TITLE
Bossbar announcement-bar is not hidden in disable-in-servers

### ISSUE THREAD

**Issue by nhanledev** [NEZNAMY/TAB#748]
### Server version

Paper 1.19.2, Waterfall 1.19.2

### TAB version

3.1.5

### Describe the bug

Bossbar `disable-in-servers` property does not block announcement-bar when it runs with `/btab announce bossbar` on Bungeecord / Waterfall.

I think the `announcement-bar` should respect the config of `disable-in-servers`.

The `display-condition` property does not help to filter which servers can display the announcement because it does not support `OR` operator. I tried with `||` and it just throws error

```
[23:36:03 INFO] [TAB]: [TAB v3.1.5] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[23:36:03 INFO] [TAB]: java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
[23:36:03 INFO] [TAB]:  at me.neznamy.tab.shared.features.bossbar.BossBarManagerImpl.loadFromConfig(BossBarManagerImpl.java:71)
[23:36:03 INFO] [TAB]:  at me.neznamy.tab.shared.features.bossbar.BossBarManagerImpl.<init>(BossBarManagerImpl.java:52)
[23:36:03 INFO] [TAB]:  at me.neznamy.tab.shared.proxy.ProxyPlatform.loadFeatures(ProxyPlatform.java:117)
[23:36:03 INFO] [TAB]:  at me.neznamy.tab.platforms.bungeecord.BungeePlatform.loadFeatures(BungeePlatform.java:29)
[23:36:03 INFO] [TAB]:  at me.neznamy.tab.shared.TAB.load(TAB.java:157)
[23:36:03 INFO] [TAB]:  at me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:22)
[23:36:03 INFO] [TAB]:  at me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:55)
[23:36:03 INFO] [TAB]:  at me.neznamy.tab.platforms.bungeecord.Main$BTABCommand.execute(Main.java:86)
[23:36:03 INFO] [TAB]:  at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:214)
[23:36:03 INFO] [TAB]:  at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:165)
[23:36:03 INFO] [TAB]:  at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30)
[23:36:03 INFO] [TAB]:  at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87)
[23:36:03 INFO] [TAB]:  at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168)
[23:36:03 INFO] [TAB]:  at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141)
[23:36:03 INFO] [TAB]:  at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:59)
[23:36:03 INFO] [TAB]:  at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[23:36:03 INFO] [TAB]: Failed to enable due to an internal plugin error. Check console for more info.
```

### Expected behavior

`announcement-bar` bossbar should not display on bossbar disabled servers.

### Steps to reproduce

1. Block an server in `disable-in-servers` of bossbar
2. Create an annoucement bossbar
3. Run `btab announce bossbar <name>`
4. See that the bossbar still display on blacklisted servers.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
you broke the config syntax, send your config.yml here

**Comment by NEZNAMY** [comment]
For OR condition types see wiki.

**Comment by nhanledev** [comment]
Thank you, I am able to setup display-condition using the condition config. But is the bossbar disable-in-servers setting bug out, or it is just how it work?
