### ISSUE TITLE
TAB breaks trying to convert to v3 (bossbar.yml) doesn't exist

### ISSUE THREAD

**Issue by ConaII** [NEZNAMY/TAB#762]
### Server version

Pufferfish-22 1.17.1

### TAB version

3.2.0

### Stack trace

```
12.12.2022 - 14:55:22 - [TAB v3.2.0] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
12.12.2022 - 14:55:22 - java.lang.IllegalStateException: Failed to convert configuration to v3: File bossbar.yml does not exist
12.12.2022 - 14:55:22 - 	at TAB-v3.2.0.jar//me.neznamy.tab.shared.config.Converter.convertToV3(Converter.java:73)
12.12.2022 - 14:55:22 - 	at TAB-v3.2.0.jar//me.neznamy.tab.shared.config.Configs.<init>(Configs.java:63)
12.12.2022 - 14:55:22 - 	at TAB-v3.2.0.jar//me.neznamy.tab.shared.TAB.load(TAB.java:154)
12.12.2022 - 14:55:22 - 	at TAB-v3.2.0.jar//me.neznamy.tab.shared.command.DisabledCommand.execute(DisabledCommand.java:29)
12.12.2022 - 14:55:22 - 	at TAB-v3.2.0.jar//me.neznamy.tab.platforms.bukkit.Main$TABCommand.onCommand(Main.java:115)
12.12.2022 - 14:55:22 - 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
12.12.2022 - 14:55:22 - 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
12.12.2022 - 14:55:22 - 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
12.12.2022 - 14:55:22 - 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2263)
12.12.2022 - 14:55:22 - 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2074)
12.12.2022 - 14:55:22 - 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2055)
12.12.2022 - 14:55:22 - 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
12.12.2022 - 14:55:22 - 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
12.12.2022 - 14:55:22 - 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
12.12.2022 - 14:55:22 - 	at net.minecraft.server.TickTask.run(TickTask.java:18)
12.12.2022 - 14:55:22 - 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
12.12.2022 - 14:55:22 - 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
12.12.2022 - 14:55:22 - 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1428)
12.12.2022 - 14:55:22 - 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
12.12.2022 - 14:55:22 - 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
12.12.2022 - 14:55:22 - 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1406)
12.12.2022 - 14:55:22 - 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1399)
12.12.2022 - 14:55:22 - 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
12.12.2022 - 14:55:22 - 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1377)
12.12.2022 - 14:55:22 - 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1288)
12.12.2022 - 14:55:22 - 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
12.12.2022 - 14:55:22 - 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce (if known)

Step 1: Configure the plugin
Step 2: Reload the plugin with /tab reload
Step 3: Every now and then the plugin breaks and 'groups.yml' & 'users.yml' are cleaned.

### Additional info

This also happens in 3.1.5
I don't know why it tries to convert to v3 if it's already v3

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
"Every now and then" I need something that actually triggers the issue. Your config should be in old_configs subfolder.

**Comment by ConaII** [comment]
I don't know, i was configuring things and reloading.
Sometimes it just breaks, then i have to move from old_configs to configs
Then when i reload it works again without having to do anything

**Comment by NEZNAMY** [comment]
I will need working steps to reproduce it. It sounds like something made the config file inaccessible or moved it, are you using some server panel that could cause it?

**Comment by ConaII** [comment]
I'm using WinSCP to edit the files.
I just managed to replicate the issue again with these steps:
 * Using WinSCP
 * Loading the file with Notepad++
 * Breaking the config file with any error and reloading
 * Changing the config.yml from UTF-8 without BOM to UTF-8 and reloading
 
https://pastebin.com/V8APDyYn

(Config used) https://pastebin.com/GjsyQDq2

**Comment by ConaII** [comment]
I tried targetting the bug but it's really strange to replicate and i couldn't find a exact reason.

**Comment by ConaII** [comment]
Now it's happening all the time in the new config that i extracted directly from the plugin (without bungee stuff)

**Comment by NEZNAMY** [comment]
Fresh config installation, breaking config, fixing it and reloading TAB gave me the following result:
```
20:51:56 [INFO] Using standard Java JCE cipher.
20:51:56 [INFO] Using standard Java compressor.
20:51:56 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:e717676:1672
20:51:56 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())

20:51:56 [INFO] Loaded plugin TAB version 3.1.6 by NEZNAMY
20:51:56 [INFO] Loaded plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:e717676:1672 by SpigotMC
20:51:57 [INFO] [TAB] §aEnabled in 149ms
20:51:57 [INFO] Enabled plugin TAB version 3.1.6 by NEZNAMY
20:51:57 [INFO] Enabled plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:e717676:1672 by SpigotMC
20:51:57 [INFO] Listening on /0.0.0.0:25577
20:52:06 [INFO] [TAB] §aDisabled in 1ms
20:52:06 [INFO] [TAB] §cFile plugins\TAB\config.yml has broken syntax.
20:52:06 [INFO] [TAB] §6Error message from yaml parser: mapping values are not allowed here
 in 'reader', line 3, column 10:
      enabled: true
             ^

20:52:06 [INFO] [TAB] §c[TAB v3.2.0] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
20:52:06 [INFO] [TAB] §cjava.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
20:52:06 [INFO] [TAB] §c	at me.neznamy.yamlassist.types.BadIndentation.checkForIndent(BadIndentation.java:30)
20:52:06 [INFO] [TAB] §c	at me.neznamy.yamlassist.types.BadIndentation.getSuggestions(BadIndentation.java:17)
20:52:06 [INFO] [TAB] §c	at me.neznamy.yamlassist.YamlAssist.getSuggestions(YamlAssist.java:63)
20:52:06 [INFO] [TAB] §c	at me.neznamy.tab.api.config.YamlConfigurationFile.<init>(YamlConfigurationFile.java:66)
20:52:06 [INFO] [TAB] §c	at me.neznamy.tab.shared.config.Configs.<init>(Configs.java:25)
20:52:06 [INFO] [TAB] §c	at me.neznamy.tab.shared.TAB.load(TAB.java:154)
20:52:06 [INFO] [TAB] §c	at me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:22)
20:52:06 [INFO] [TAB] §c	at me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:55)
20:52:06 [INFO] [TAB] §c	at me.neznamy.tab.platforms.bungeecord.Main$BTABCommand.execute(Main.java:86)
20:52:06 [INFO] [TAB] §c	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:207)
20:52:06 [INFO] [TAB] §c	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:157)
20:52:06 [INFO] [TAB] §c	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:74)
20:52:06 [INFO] [TAB] §c	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
20:52:06 [INFO] [TAB] §cFailed to enable due to an internal plugin error. Check console for more info.
20:52:14 [INFO] [TAB] §aEnabled in 26ms
20:52:14 [INFO] §f§3[TAB] Successfully reloaded
```

**Comment by ConaII** [comment]
Yeah exactly that

**Comment by NEZNAMY** [comment]
What do you mean exactly that? Where do you see bossbar error message in the log I sent?

**Comment by ConaII** [comment]
Oh, my bad, i didn't remember the error.
Well i don't know what could be happening but it doesn't really affect me anymore since i finished setting up

**Comment by NEZNAMY** [comment]
It would be great if you could help finding the cause, though it's respectable if you don't want to invest your time in this. Let me know what is your decision and if you are not interested in investigating this, please close the issue.

**Comment by ConaII** [comment]
The only thing i can provide is that, comparing this config to my new one:
 * `can-see-friendly-invisibles: false` exists in scoreboard-teams
 * `register-tab-expansion: true` I have it on false (idk what it even does)

**Comment by NEZNAMY** [comment]
Removing config options to let plugin readd them doesn't reproduce it for me either.

**Comment by bumpyJake** [comment]
I've just experienced this same issue. Fresh installation of latest TAB version on a fresh server. Upon modifying the config and reloading a couple of times, I get that same issue in console

**Comment by NEZNAMY** [comment]
I'll need exact steps to reproduce.

**Comment by NEZNAMY** [comment]
@LcyDev , @bumpyJake or anyone having this issue, can you open a ticket on discord? I want to make progress on this.

**Comment by bumpyJake** [comment]
Weirdly enough I haven't had the issue since
Every server I've installed it on has had no issues (I've installed it on at least 5 others)
I think it may be due to my server hosts crappy file management (its been happening quite a bit to other plugins where they save incorrectly)

**Comment by NEZNAMY** [comment]
That can totally be the case, considering how rare it is. Someone once had this issue kinda consistently and when I added more debugging stuff, it turned out the config file was empty at the time of reading, false triggering this. So even without this issue, the plugin would not work correctly anyway. I can revert the config detection logic to avoid this specific issue, but that's about it.
