### ISSUE TITLE
Error when trying to add custom placeholders

### ISSUE THREAD

**Issue by izzzzthewiz** [NEZNAMY/TAB#767]
### Server version

Spigot 1.19.1

### TAB version

3.2.1

### Stack trace

[Server thread/ERROR]: Error occurred while enabling UncutPR v1.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalStateException: API instance is null. This likely means you shaded TAB's API into your project instead of only using it, which is not allowed.
        at me.neznamy.tab.api.TabAPI.getInstance(TabAPI.java:39) ~[?:?]
        at me.izzdevs.uncutpr.TAB.TabPlaceholders.register(TabPlaceholders.java:10) ~[?:?]
        at me.izzdevs.uncutpr.UncutPR.onEnable(UncutPR.java:25) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3608-Spigot-6198b5a-b5aa0be]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3608-Spigot-6198b5a-b5aa0be]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.reload(CraftServer.java:924) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3608-Spigot-6198b5a-b5aa0be]
        at org.bukkit.Bukkit.reload(Bukkit.java:802) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:833) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3608-Spigot-6198b5a-b5aa0be]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:818) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3608-Spigot-6198b5a-b5aa0be]
        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:419) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3608-Spigot-6198b5a-b5aa0be]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:395) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3608-Spigot-6198b5a-b5aa0be]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3608-Spigot-6198b5a-b5aa0be]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1013) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3608-Spigot-6198b5a-b5aa0be]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3608-Spigot-6198b5a-b5aa0be]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### Steps to reproduce (if known)

Added this class into my plugin

    package me.izzdevs.uncutpr.TAB;

    import me.neznamy.tab.api.TabAPI;
    import org.bukkit.entity.Player;

    public class TabPlaceholders {
    
        public static void register() {
            TabAPI.getInstance().getPlaceholderManager().registerPlayerPlaceholder("%uncut-rank%", 100, player -> {
                if (((Player) player).getDisplayName().equalsIgnoreCase("&7")) {
                    return "&7Player";
                }
                else {
                    return ((Player) player).getDisplayName().replaceAll("&8 | ", "");
                }
            });
        }
    
    }

### Additional info

I get the printed error stack. Not sure what shading is or how to fix it, a little help would be nice. Adding to the developer API wiki on how to prevent this would be useful too :)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/208309957-d3a8e5ab-77db-401e-b93b-8518ac0a9461.png)
It's there?

Also this is not something specific to TAB, you should never make your jar contain classes of plugins you hook into.

**Comment by izzzzthewiz** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/6338394/208309957-d3a8e5ab-77db-401e-b93b-8518ac0a9461.png)
> 
> It's there?
> 
> 
> 
> Also this is not something specific to TAB, you should never make your jar contain classes of plugins you hook into.

how would i hook into this and create custom placeholders then? i understand that its my fault, i'm just looking for the proper way to do it and maybe some added documentation on how to do it properly

**Comment by Tanguygab** [comment]
it's literally in the screenshot NEZNAMY said and on the documentation

**Comment by izzzzthewiz** [comment]
> it's literally in the screenshot NEZNAMY said and on the documentation 

ok then what did i do wrong? i know that i "shaded" it but what does this mean and what can i do to make this work properly?

**Comment by NEZNAMY** [comment]
Open your jar with winrar for example and delete TAB's classes.
