### ISSUE TITLE
Getting kicked from the server when using the plugin

### ISSUE THREAD

**Issue by skTanklol** [NEZNAMY/TAB#769]
### Server version

Paper 1.19.2

### TAB version

3.2.0

### Stack trace

[09:47:11 INFO]: [TAB] Disabled in 4ms
[09:47:11 INFO]: [TAB] [TAB v3.2.0] Feature HeaderFooter failed to process player PienAppel
[09:47:11 INFO]: [TAB] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@52b89b36[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@6e8cda25[Wrapped task = me.neznamy.tab.shared.CpuManager$$Lambda$7279/0x000000080228d460@420a2297]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7c2e480b[Terminated, pool size = 8, active threads = 0, queued tasks = 0, completed tasks = 42]
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:632)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.CpuManager.startRepeatingMeasuredTask(CpuManager.java:362)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.addUsedPlaceholder(PlaceholderManagerImpl.java:256)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.api.TabFeature.lambda$addUsedPlaceholders$0(TabFeature.java:299)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.api.TabFeature.addUsedPlaceholders(TabFeature.java:299)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.DynamicText.analyze(DynamicText.java:118)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.DynamicText.<init>(DynamicText.java:82)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.ITabPlayer.setProperty(ITabPlayer.java:127)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.ITabPlayer.setProperty(ITabPlayer.java:140)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.features.HeaderFooter.refresh(HeaderFooter.java:84)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.features.HeaderFooter.onJoin(HeaderFooter.java:49)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.FeatureManagerImpl.onJoin(FeatureManagerImpl.java:125)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.platforms.bukkit.BukkitEventListener.lambda$onJoin$1(BukkitEventListener.java:52)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:112)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[09:47:11 INFO]: [TAB] 	at java.base/java.lang.Thread.run(Thread.java:833)
[09:47:11 INFO]: [TAB] [TAB v3.2.0] Feature PlayerList failed to process player PienAppel
[09:47:11 INFO]: [TAB] java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.shared.features.PlaceholderManagerImpl.detectPlaceholders(String)" because the return value of "me.neznamy.tab.shared.TAB.getPlaceholderManager()" is null
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.DynamicText.analyze(DynamicText.java:95)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.DynamicText.<init>(DynamicText.java:82)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.ITabPlayer.setProperty(ITabPlayer.java:127)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.ITabPlayer.loadPropertyFromConfig(ITabPlayer.java:375)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.ITabPlayer.loadPropertyFromConfig(ITabPlayer.java:362)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.features.PlayerList.updateProperties(PlayerList.java:78)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.features.PlayerList.onJoin(PlayerList.java:198)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.FeatureManagerImpl.onJoin(FeatureManagerImpl.java:125)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.platforms.bukkit.BukkitEventListener.lambda$onJoin$1(BukkitEventListener.java:52)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:112)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[09:47:11 INFO]: [TAB] 	at java.base/java.lang.Thread.run(Thread.java:833)
[09:47:11 INFO]: [TAB] [TAB v3.2.0] Feature YellowNumber failed to process player PienAppel
[09:47:11 INFO]: [TAB] java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.Property.updateAndGet()" because the return value of "me.neznamy.tab.api.TabPlayer.getProperty(String)" is null
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.features.YellowNumber.getValue(YellowNumber.java:54)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.features.YellowNumber.onJoin(YellowNumber.java:101)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.FeatureManagerImpl.onJoin(FeatureManagerImpl.java:125)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.platforms.bukkit.BukkitEventListener.lambda$onJoin$1(BukkitEventListener.java:52)
[09:47:11 INFO]: [TAB] 	at TAB.v3.2.0.jar//me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:112)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[09:47:11 INFO]: [TAB] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[09:47:11 INFO]: [TAB] 	at java.base/java.lang.Thread.run(Thread.java:833)
[09:47:11 INFO]: [TAB] Enabled in 14ms
[09:47:11 INFO]: [TAB] [TAB] Successfully reloaded

The error above gets sent to console after a player joins the server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
>  I am running latest version of the plugin
try with 3.2.1

**Comment by skTanklol** [comment]
I tried using 3.2.1 the same error is happening

**Comment by NEZNAMY** [comment]
Send the kick message.

**Comment by skTanklol** [comment]
That is all that is sent when the player joins, the player joins then immediately gets disconnected

**Comment by NEZNAMY** [comment]
Send disconnect message from client.

**Comment by NEZNAMY** [comment]
Considering this issue inactive, error was fixed, considering this solved.
