### ISSUE TITLE
Placeholders not loading, players getting kicked, ...

### ISSUE THREAD

**Issue by MinecollYT** [NEZNAMY/TAB#771]
### Server version

FlameCord 1.2.1 (Also happens with normal Bungee) + Paper 1.18.2

### TAB version

3.1.2

### Stack trace

On join:
```
[21:09:06 INFO] [TAB]: java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.packet.PlayerListItem$Item.setGamemode(int)'
[21:09:06 INFO] [TAB]:  at me.neznamy.tab.platforms.bungeecord.BungeePacketBuilder.build(BungeePacketBuilder.java:58)
[21:09:06 INFO] [TAB]:  at me.neznamy.tab.api.protocol.PacketBuilder.lambda$new$2(PacketBuilder.java:31)
[21:09:06 INFO] [TAB]:  at me.neznamy.tab.api.protocol.PacketBuilder.build(PacketBuilder.java:54)
[21:09:06 INFO] [TAB]:  at me.neznamy.tab.shared.ITabPlayer.sendCustomPacket(ITabPlayer.java:330)
[21:09:06 INFO] [TAB]:  at me.neznamy.tab.shared.ITabPlayer.sendCustomPacket(ITabPlayer.java:338)
[21:09:06 INFO] [TAB]:  at me.neznamy.tab.shared.features.PlayerList.updatePlayer(PlayerList.java:99)
[21:09:06 INFO] [TAB]:  at me.neznamy.tab.shared.features.PlayerList.refresh(PlayerList.java:194)
[21:09:06 INFO] [TAB]:  at me.neznamy.tab.shared.features.PlayerList.lambda$onJoin$0(PlayerList.java:206)
[21:09:06 INFO] [TAB]:  at me.neznamy.tab.shared.features.PlayerList.onJoin(PlayerList.java:215)
[21:09:06 INFO] [TAB]:  at me.neznamy.tab.shared.FeatureManagerImpl.onJoin(FeatureManagerImpl.java:130)
[21:09:06 INFO] [TAB]:  at me.neznamy.tab.platforms.bungeecord.BungeeEventListener.lambda$onSwitch$1(BungeeEventListener.java:43)
[21:09:06 INFO] [TAB]:  at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:113)
[21:09:06 INFO] [TAB]:  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[21:09:06 INFO] [TAB]:  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[21:09:06 INFO] [TAB]:  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:09:06 INFO] [TAB]:  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:09:06 INFO] [TAB]:  at java.base/java.lang.Thread.run(Thread.java:833)
```

Kick message for clients below 1.19 / for everyone when running `/btab reload`:
`NoSuchMethodError : 'void net.md_5.bungee.protocol.packet.PlayerListItem$Item.setGamemode(int)' @ me.neznamy.tab.platforms.bungeecord.BungeePacketBuilder:58`

### Steps to reproduce (if known)

Step 1: Install Flamecord
Step 2: Install TAB
Step 3: Install TAB-Bridge

### Additional info

I recently upgraded my viaversion, flamecord, tab and tab-bridge to allow 1.19 clients to join. ViaVersion is installed on the Backend-Servers, not on Bungeecord.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Why are you reporting missing 1.19.3 support which was added weeks ago?

**Comment by MinecollYT** [comment]
I'm reporting this error that comes up, I'm using the latest version of everything, but it seems like there is something missing?
I know that 1.19 support was added, that's why I upgraded in the first place

**Comment by NEZNAMY** [comment]
You didn't upgrade, 3.1.2 is very old, latest is 3.2.1.

**Comment by MinecollYT** [comment]
Oh sorry, my mistake. I meant 3.2.1 not 3.1.2 - typpo

**Comment by NEZNAMY** [comment]
Send full console log since server startup until the error.

**Comment by MinecollYT** [comment]
That's very weird. I just restarted again for getting a clean log and... it works?
I'm very sorry for the inconvenience caused, but I'm very thankful for your fast response.
