### ISSUE TITLE
NMSStorage

### ISSUE THREAD

**Issue by catches** [NEZNAMY/TAB#803]
### Server version

Pufferfish+ 1.19.3

### TAB version

3.2.3

### Stack trace

[13:36:07 ERROR]: Error occurred while disabling TAB-Additions v1.6.7 (Is it up to date?)
java.lang.NoClassDefFoundError: me/neznamy/tab/platforms/bukkit/nms/NMSStorage
        at io.github.tanguygab.tabadditions.spigot.SpigotPlatform.removeFromChatComplete(SpigotPlatform.java:170) ~[TAB-Additions-1.6.7.jar:?]
        at io.github.tanguygab.tabadditions.shared.features.chat.ChatManager.unload(ChatManager.java:246) ~[TAB-Additions-1.6.7.jar:?]
        at io.github.tanguygab.tabadditions.shared.TABAdditions.lambda$disable$1(TABAdditions.java:144) ~[TAB-Additions-1.6.7.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at io.github.tanguygab.tabadditions.shared.TABAdditions.disable(TABAdditions.java:142) ~[TAB-Additions-1.6.7.jar:?]
        at io.github.tanguygab.tabadditions.spigot.TABAdditionsSpigot.onDisable(TABAdditionsSpigot.java:33) ~[TAB-Additions-1.6.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[pufferfishplus-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:402) ~[pufferfishplus-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:581) ~[pufferfishplus-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:558) ~[pufferfishplus-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.disablePlugins() ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java) ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java) ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.19.3.jar:git-PufferfishPlus-40]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.neznamy.tab.platforms.bukkit.nms.NMSStorage
        ... 16 more

### Steps to reproduce (if known)

Restart/stop server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
This is not a TAB-Additions issue tracker.
