### ISSUE TITLE
Players are invincible with worldguard not sure if it is due to the plugin or worldguard

### ISSUE THREAD

**Issue by Wamens** [NEZNAMY/TAB#843]
### Server version

Purpur 1.19.3

### TAB version

3.3.1

### Describe the bug

Players are invincible in the wild and this error pops out every time: 

[12:11:32 ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.8-beta-01+cbb2ba7
java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.TabPlayer.getProperty(String)" because "p" is null
        at me.neznamy.tab.shared.features.nametags.NameTag.updateTeamData(NameTag.java:257) ~[TAB v3.3.1.jar:?]
        at me.neznamy.tab.shared.features.nametags.NameTag.updateTeamData(NameTag.java:250) ~[TAB v3.3.1.jar:?]
        at me.neznamy.tab.shared.features.nametags.CollisionManager.setCollisionRule(CollisionManager.java:64) ~[TAB v3.3.1.jar:?]
        at me.neznamy.tab.shared.features.nametags.NameTag.setCollisionRule(NameTag.java:239) ~[TAB v3.3.1.jar:?]
        at io.github.invvk.wgef.abstraction.flags.handler.collision.TABCollisionHandler.remove(TABCollisionHandler.java:25) ~[WGEF-REBORN (5).jar:?]
        at io.github.invvk.wgef.abstraction.flags.handler.player.CollisionFlagHandler.onAbsentValue(CollisionFlagHandler.java:58) ~[WGEF-REBORN (5).jar:?]
        at io.github.invvk.wgef.abstraction.flags.handler.player.CollisionFlagHandler.onAbsentValue(CollisionFlagHandler.java:19) ~[WGEF-REBORN (5).jar:?]
        at io.github.invvk.wgef.abstraction.flags.handler.AbstractFlagHandler.onCrossBoundary(AbstractFlagHandler.java:41) ~[WGEF-REBORN (5).jar:?]
        at com.sk89q.worldguard.bukkit.session.TimedHandlerFactory$TimedHandler.onCrossBoundary(TimedHandlerFactory.java:107) ~[worldguard-bukkit-7.0.8-beta-01-dist (3).jar:?]
        at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:220) ~[worldguard-bukkit-7.0.8-beta-01-dist (3).jar:?]
        at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:180) ~[worldguard-bukkit-7.0.8-beta-01-dist (3).jar:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerTeleport(WorldGuardPlayerListener.java:400) ~[worldguard-bukkit-7.0.8-beta-01-dist (3).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor36.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1927]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1328) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1222) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at com.earth2me.essentials.AsyncTeleport.lambda$nowAsync$3(AsyncTeleport.java:196) ~[EssentialsX-2.19.7 (3).jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.lambda$getChunkAtAsync$15(CraftWorld.java:2420) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1927]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected behavior

Shouldn't be doing that

### Steps to reproduce

Set up a region
Die a couple times and go outside the region

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Try removing the plugin for extra flags to find out.

**Comment by NEZNAMY** [comment]
The plugin is passing null player as argument. I have added null checks to make the error message more obvious, but it won't solve the issue. Since the repository is archived, the issue will probably not be fixed. There is nothing we can do about it.
