### ISSUE TITLE
TAB failed to install. "TAB.v3.3.1.jar appears to be a Bukkit or BungeeCord plugin"

### ISSUE THREAD

**Issue by Penguin-Terminal** [NEZNAMY/TAB#853]
### Server version

Velocity 3.2.0-SNAPSHOT

### TAB version

3.3.1

### Describe the bug

When TAB is put in the plugins folder on the server, an error is received upon booting.

`[16:06:22 ERROR]: Unable to load plugin plugins/TAB.v3.3.1.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file TAB.v3.3.1.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:154) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:64) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:345) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]`

### Expected behavior

The plugin should boot, as it is compatible with velocity.

### Steps to reproduce

Step 1: Install plugin on velocity server.
Step 2: Start velocity server.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/227739316-1ffd4189-4df3-4d77-b4e8-b9129edb3458.png)
Are you sure?
![image](https://user-images.githubusercontent.com/6338394/227739326-e81b1ea4-4900-41eb-b5c9-7ed011be500f.png)
