### ISSUE TITLE
RedisBungee error

### ISSUE THREAD

**Issue by nhanledev** [NEZNAMY/TAB#861]
### Server version

Paper 1.17.1

### TAB version

3.3.2

### Describe the bug

Throws error in `error.log` and cause many issues on RedisBungee-enabled servers.

```
02.04.2023 - 10:22:56 - [TAB v3.3.2] An error was thrown when executing task
02.04.2023 - 10:22:56 - java.lang.NullPointerException: Cannot invoke "String.trim()" because "in" is null
02.04.2023 - 10:22:56 - 	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
02.04.2023 - 10:22:56 - 	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
02.04.2023 - 10:22:56 - 	at java.base/java.lang.Double.parseDouble(Double.java:651)
02.04.2023 - 10:22:56 - 	at me.neznamy.tab.shared.ErrorManager.parseInteger(ErrorManager.java:198)
02.04.2023 - 10:22:56 - 	at me.neznamy.tab.shared.features.redis.RedisPlayer.getBelowName(RedisPlayer.java:122)
02.04.2023 - 10:22:56 - 	at me.neznamy.tab.shared.features.redis.RedisSupport.join(RedisSupport.java:282)
02.04.2023 - 10:22:56 - 	at me.neznamy.tab.shared.features.redis.RedisSupport.lambda$processMessage$0(RedisSupport.java:189)
02.04.2023 - 10:22:56 - 	at me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$11(CpuManager.java:212)
02.04.2023 - 10:22:56 - 	at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:84)
02.04.2023 - 10:22:56 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
02.04.2023 - 10:22:56 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
02.04.2023 - 10:22:56 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
02.04.2023 - 10:22:56 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
02.04.2023 - 10:22:56 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
02.04.2023 - 10:22:56 - 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected behavior

Works as 3.3.1

### Steps to reproduce

1. Install waterfall with RedisBungee 0.10.2
2. Run server and see the error

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by nhanledev** [comment]
I confirm that this is fixed in https://github.com/NEZNAMY/TAB/commit/c211724d132d2d166ad52627222f94582d4b3617
