### ISSUE TITLE
Scoreboard returning null

### ISSUE THREAD

**Issue by MachineKillin** [NEZNAMY/TAB#880]
### Server version

Spigot 1.8

### TAB version

3.3.2

### Stack trace

```
[Plugin] Task #173 for Plugin v2.0 generated an exception
java.lang.NullPointerException: null
        at -----.scoreboard.Scoreboards$1.run(Scoreboards.java:65) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

### Steps to reproduce (if known)

```
TabPlayer player = TabAPI.getInstance().getPlayer(player.getUniqueId());
Scoreboard p = scoreboardmanager.getActiveScoreboard(player); (this is line 65 thats causing the error)
```

### Additional info

in my plugin im doing foreach player by getting all online players and setting scoreboards based on their state on the server. i get the TabPlayer like `TabAPI.getInstance().getPlayer(player.getUniqueId())` which isnt null. but when trying to get the active scoreboard which is set like:
```@EventHandler
    public void initializeBoard(PlayerJoinEvent e) {
        List<String> lines = new ArrayList<>();
        TabPlayer player = TabAPI.getInstance().getPlayer(e.getPlayer().getUniqueId());
        Scoreboard scoreboard = scoreboardmanager.createScoreboard(e.getPlayer().getName(), "Server", lines);
        scoreboardmanager.showScoreboard(player, scoreboard);
    }
```
i also tried to fix this by doing:
```
Scoreboard p = scoreboardmanager.getActiveScoreboard(player);
if (p == null) {
        p = scoreboardmanager.createScoreboard(player.getName(), "Server", lines);
}
```
but it was stopping on the line where i try to define the scoreboard. 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by MachineKillin** [comment]
scoreboardmanager was null lmao
