### ISSUE TITLE
Velocity proxy support

### ISSUE THREAD

**Issue by anonynorbi** [NEZNAMY/TAB#881]
### Server version

Velocity 3.2.0-SNAPSHOT

### TAB version

3.3.2

### Describe the bug

After putting the TAB plugin inside the plugins folder and starting the proxy, it gives me these errors in the console:

`[09:39:49 ERROR]: Unable to load plugin plugins/TAB.v3.3.2.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file TAB.v3.3.2.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:154) ~[velocity-3.2.0-SNAPSHOT-252.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:64) ~[velocity-3.2.0-SNAPSHOT-252.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[velocity-3.2.0-SNAPSHOT-252.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:345) ~[velocity-3.2.0-SNAPSHOT-252.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[velocity-3.2.0-SNAPSHOT-252.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[velocity-3.2.0-SNAPSHOT-252.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]`

### Expected behavior

The plugin should normally work because Velocity proxy says that it supports Bungeecord plugins. 

### Steps to reproduce

Step 1: Put TAB.jar plugin inside plugins folder of Velocity proxy
Step 2: Start the proxy

### Additional info

It would be so nice to see this plugin work with Velocity. I would even pay to see it work. Velocity is a new proxy system, but has Bungeecord support and more. TAB plugin is one of the best plugins I've ever tried out.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by DrWurzeli** [comment]
> because Velocity proxy says that it supports Bungeecord plugins.
Velocity and Bungeecord are fundamentally different things. Plugins do not just work on Velocity.
https://github.com/NEZNAMY/TAB/wiki/Compatibility
Velocity is not going to be supported https://gist.github.com/NEZNAMY/21c1aabe57a0a462ee175386c510fdf8
