### ISSUE TITLE
Tablist does not resolve %player% anymore after /tab reloaded and more than one player.

### ISSUE THREAD

**Issue by dandud100** [NEZNAMY/TAB#889]
### Server version

paper-1.19.3

### TAB version

3.3.2

### Describe the bug

After i reload the tab plugin with more than one player online it does not resolve the player variable anymore.

![image](https://user-images.githubusercontent.com/43549788/236630770-4538f4dd-d7f7-44fa-abd1-6881ba0bf4d7.png)
![image](https://user-images.githubusercontent.com/43549788/236630841-1beb7215-8cb4-481a-89d5-a9c968c40bc2.png)
![image](https://user-images.githubusercontent.com/43549788/236631824-cc512cd6-b9bf-48be-8553-1e309ff4a2c5.png)

Only a server restart brings this back working.
![image](https://user-images.githubusercontent.com/43549788/236631146-735fa6b6-7588-4ed6-be8d-40c663153cf6.png)
![image](https://user-images.githubusercontent.com/43549788/236631212-bef6ea0d-e171-4ebb-a220-f6116e1c8416.png)

### Expected behavior

Showing the playername like before /tab reload

### Steps to reproduce

As described.

### Additional info

![image](https://user-images.githubusercontent.com/43549788/236632415-f9689924-bd67-4328-af90-40f52d647379.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
did you get an errors file in your TAB folder?

**Comment by dandud100** [comment]
> did you get an errors file in your TAB folder?

```06.05.2023 - 14:23:26 - [TAB v3.3.2] An error was thrown when executing task
06.05.2023 - 14:23:26 - java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.shared.features.PlaceholderManagerImpl.getPlaceholder(String)" because the return value of "me.neznamy.tab.shared.TAB.getPlaceholderManager()" is null
06.05.2023 - 14:23:26 - 	at TAB.v3.3.2.jar//me.neznamy.tab.shared.placeholders.TabPlaceholder.setPlaceholders(TabPlaceholder.java:136)
06.05.2023 - 14:23:26 - 	at TAB.v3.3.2.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.updateValue(PlayerPlaceholderImpl.java:85)
06.05.2023 - 14:23:26 - 	at TAB.v3.3.2.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.lambda$updateValue$0(PlayerPlaceholderImpl.java:91)
06.05.2023 - 14:23:26 - 	at TAB.v3.3.2.jar//me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:84)
06.05.2023 - 14:23:26 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
06.05.2023 - 14:23:26 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
06.05.2023 - 14:23:26 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
06.05.2023 - 14:23:26 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
06.05.2023 - 14:23:26 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
06.05.2023 - 14:23:26 - 	at java.base/java.lang.Thread.run(Thread.java:833)
06.05.2023 - 14:24:46 - [TAB v3.3.2] An error was thrown when executing task
06.05.2023 - 14:24:46 - java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.shared.features.PlaceholderManagerImpl.getTabExpansion()" because the return value of "me.neznamy.tab.shared.TAB.getPlaceholderManager()" is null
06.05.2023 - 14:24:46 - 	at TAB.v3.3.2.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.updateValue(PlayerPlaceholderImpl.java:88)
06.05.2023 - 14:24:46 - 	at TAB.v3.3.2.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.lambda$updateValue$0(PlayerPlaceholderImpl.java:91)
06.05.2023 - 14:24:46 - 	at TAB.v3.3.2.jar//me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:84)
06.05.2023 - 14:24:46 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
06.05.2023 - 14:24:46 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
06.05.2023 - 14:24:46 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
06.05.2023 - 14:24:46 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
06.05.2023 - 14:24:46 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
06.05.2023 - 14:24:46 - 	at java.base/java.lang.Thread.run(Thread.java:833)
06.05.2023 - 14:25:36 - [TAB v3.3.2] An error was thrown when executing task
06.05.2023 - 14:25:36 - java.lang.NullPointerException: null
06.05.2023 - 14:25:36 - [TAB v3.3.2] An error was thrown when executing task
06.05.2023 - 14:25:36 - java.lang.NullPointerException: null
06.05.2023 - 14:27:23 - [TAB v3.3.2] An error was thrown when executing task
06.05.2023 - 14:27:23 - java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.shared.features.PlaceholderManagerImpl.getTabExpansion()" because the return value of "me.neznamy.tab.shared.TAB.getPlaceholderManager()" is null
06.05.2023 - 14:27:23 - 	at TAB.v3.3.2.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.updateValue(PlayerPlaceholderImpl.java:88)
06.05.2023 - 14:27:23 - 	at TAB.v3.3.2.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.lambda$updateValue$0(PlayerPlaceholderImpl.java:91)
06.05.2023 - 14:27:23 - 	at TAB.v3.3.2.jar//me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:84)
06.05.2023 - 14:27:23 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
06.05.2023 - 14:27:23 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
06.05.2023 - 14:27:23 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
06.05.2023 - 14:27:23 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
06.05.2023 - 14:27:23 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
06.05.2023 - 14:27:23 - 	at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by NEZNAMY** [comment]
Also was one of those errors thrown at the time you reloaded the plugin and it broke?

**Comment by dandud100** [comment]
> Send your configuration files.

```
# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  header:
    - "<#FFFFFF>&m                                                </#FFFF00>"
    - "&3&lgg.net"
    - ""
    - "&7&l>> Hallo&3 &l%player%&7&l! &7&l<<"
    - ""
    - "&7Gerade online: &f%online%"
#    - "&6Online staff: &e%staffonline%"
    - ""
  footer:
#    - "%animation:time%"
#    - "&2Ping: %ping%"
#    - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
    - ""
    - "&7Alles wichtige findest du unter: %animation:help%"
    - "<#FFFFFF>&m                                                </#FFFF00>"
  per-world:
    world1:
      header:
        - "an example of world with custom"
      footer:
        - "header/footer and prefix/suffix"
    world2;world3:
      header:
        - "This is a shared header for"
        - "world2 and world3"
  per-server:
    server1:
      header:
        - "an example of server with custom header"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Tablist-name-formatting
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist
  sorting-types:
    - "PLACEHOLDER_HIGH_TO_LOW:%luckperms_highest_group_weight%"
    - "PLACEHOLDER_A_TO_Z:%player%"
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode
  unlimited-nametag-mode:
    enabled: false
    disable-on-boats: true
    disable-in-worlds:
      - disabledworld
    disable-in-servers:
      - disabledserver
    dynamic-lines:
      - abovename
      - nametag #the original one, combination of tagprefix + customtagname + tagsuffix
      - belowname
      - another
    static-lines:
      myCustomLine: 0.66

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Yellow-number
yellow-number-in-tablist:
  enabled: true
  value: "%ping%"
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Belowname
belowname-objective:
  enabled: false
  number: "%health%"
  text: "&cHealth"
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Spectator-fix
prevent-spectator-effect:
  enabled: false

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Bossbar
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  bars:
    ServerInfo:
      style: "PROGRESS" # for 1.9+: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
      color: "%animation:barcolors%" # for 1.9+: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
      progress: "100" # in %
      text: "&fWebsite: &bwww.domain.com"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  scoreboards:
    scoreboard1:
      title: "gg.net"
      display-condition: "permission:tab.scoreboard.1"
      lines:
        - " "
        - "&bWelt&7: &f%myworlds_world_alias%"
        - " "
        - "&eMcMMO Powerlevel&7: &f%mcmmo_power_level%"
        - "&eSpielzeit&7: &f%playtime_time_hours% Std."
        - "&eGeld&7: &f$%vault_eco_balance%"
        - " "
        - "&f&bRang&7: &f%luckperms_current_group_on_track_spieler%"
        - "&f&bVotes bis Rangupgrade&7: &f%votingplugin_alltimetotal% / 3"
        - "&f&bPing&7: &f%ping%&7ms"
    scoreboard2:
      title: "gg.net"
      display-condition: "permission:tab.scoreboard.2"
      lines:
        - " "
        - "&bWelt&7: &f%myworlds_world_alias%"
        - " "
        - "&eMcMMO Powerlevel&7: &f%mcmmo_power_level%"
        - "&eSpielzeit&7: &f%playtime_time_hours% Std."
        - "&eGeld&7: &f$%vault_eco_balance%"
        - " "
        - "&f&bRang&7: &f%luckperms_current_group_on_track_spieler%"
        - "&f&bVotes bis Rangupgrade&7: &f%votingplugin_alltimetotal% / 15"
        - "&f&bPing&7: &f%ping%&7ms"
    admin:
      # Only players with tab.scoreboard.admin can see this scoreboard, others will see scoreboard1
      display-condition: "permission:tab.scoreboard.admin"
      title: "Admin scoreboard"
      lines:
        - "%animation:MyAnimation1%"
        - "&6Online:"
        - "* &eOnline&7: &f%online%"
        - "* &eCurrent World&7: &f%worldonline%"
        - "* &eStaff&7: &f%staffonline%"
        - " "
        - "&6Server Info:"
        - "* &bTPS&7: %tps%"
        - "* &bUptime&7: &f%server_uptime%"
        - "* &bMemory&7: &f%memory-used%&7/&4%memory-max%"
        - "%animation:MyAnimation1%"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Ping-Spoof
ping-spoof:
  enabled: false
  value: 0

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Pet-name-fix
fix-pet-names:
  enabled: false

placeholders:
  date-format: "dd.MM.yyyy"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0
  register-tab-expansion: false

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements
placeholder-output-replacements:
  "%essentials_vanished%":
    "yes": "&7| Vanished"
    "no": ""
  # bukkit-only placeholders used in default groups.yml, doing this as a fix
  "%afk%":
    true: " &o[AFK]&r"
    false: ""
    "%afk%": "" # if attempting to use bukkit-only placeholder on bungeecord
  "%essentials_nickname%":
    "%essentials_nickname%": "%player%" # placeholder did not parse correctly, show real name instead

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders
conditions:
  nick: # use it with %condition:nick%
    conditions:
      - "%player%=%essentials_nickname%"
    yes: "%player%"
    no: "~%essentials_nickname%"

placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
    "%server_unique_joins%": 5000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_factionsuuid_relation_color%": 1000

# assigning groups by permission nodes instead of taking them from permission plugin
assign-groups-by-permissions: false

# if the option above is true, all groups are taken based on permissions and the one higher in this list is used as primary
# Warning! This is not sorting list and has nothing to do with sorting players in tablist!
primary-group-finding-list:
  - Owner
  - Admin
  - Mod
  - Helper
  - default

debug: false

# https://github.com/NEZNAMY/TAB/wiki/MySQL
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password

########################################################################
# BUKKIT ONLY - THE FOLLOWING SECTION IS ONLY FOR BACKEND INSTALLATION #
########################################################################

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Per-world-playerlist
per-world-playerlist:
  enabled: false
  # players with tab.staff will always see all players
  allow-bypass-permission: false
  # players in these worlds will always see all players
  ignore-effect-in-worlds:
    - ignoredworld
    - build
  shared-playerlist-world-groups:
    lobby:
      - lobby1
      - lobby2
    minigames:
      - paintball
      - bedwars

#####################################################################
# PROXY ONLY - THE FOLLOWING SECTION IS ONLY FOR PROXY INSTALLATION #
#####################################################################

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Global-playerlist
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
  fill-profile-key: false
  spy-servers:
    - spyserver1
    - spyserver2
  server-groups:
    lobbies:
      - lobby1
      - lobby2
    group2:
      - server1
      - server2

# Take permissions and groups from backend server instead of proxy
use-bukkit-permissions-manager: false

# Sometimes server might be using offline uuids in tablist instead of online, such as disabling waterfall's tablist rewrite option
# If you experience tablist formatting not working and global playerlist duplicating players, toggle this option (set it to opposite value)
# Only affects proxies with online mode enabled
use-online-uuid-in-tablist: true
```

**Comment by dandud100** [comment]
> Also was one of those errors thrown at the time you reloaded the plugin and it broke?

Yeah, those errors appear if a second player is online and i use /tab reload two times. I added an additional screenshot on top where i monitor the variable.

**Comment by NEZNAMY** [comment]
Try latest build from actions.

**Comment by dandud100** [comment]
> Try latest build from actions. 
Just installed, works. So far the issue is not there.

> What does `/tab parse me ` suggest? All placeholders or nothing?
I don't know exactly what you mean with this.

**Comment by NEZNAMY** [comment]
On modern versions when you type a command, you get suggestions. Parse command is supposed to suggest you all valid placeholders there. Does it?

**Comment by dandud100** [comment]
> On modern versions when you type a command, you get suggestions. Parse command is supposed to suggest you all valid placeholders there. Does it?

Yes! It does show a lot of placeholders.

**Comment by NEZNAMY** [comment]
But when the %player% placeholder is broken.

**Comment by dandud100** [comment]
> But when the %player% placeholder is broken.

After a second player joins and i do /tab reload twice.

**Comment by NEZNAMY** [comment]
And how do suggestions look?

**Comment by NEZNAMY** [comment]
Type `/tab group _DEFAULT_ customtabname` if you still get the issue after that (and after reloading).

**Comment by NEZNAMY** [comment]
> > But when the %player% placeholder is broken.
> 
> After a second player joins and i do /tab reload twice. If i am alone on the server it does not break. ![image](https://user-images.githubusercontent.com/43549788/236632415-f9689924-bd67-4328-af90-40f52d647379.png)

Is this with 4.0.0 snapshot?

**Comment by dandud100** [comment]
> And how do suggestions look?

![image](https://user-images.githubusercontent.com/43549788/236633332-a5f0cd6f-71e0-4c07-99f1-e2b84522dda8.png)


> Type `/tab group _DEFAULT_ customtabname` if you still get the issue after that (and after reloading).

![image](https://user-images.githubusercontent.com/43549788/236633377-27e6c4bb-cc13-4d9e-ba24-18ab7c0a6dcf.png)


> Is this with 4.0.0 snapshot?

No, as i said 4.0.0 no issues. This is old version, i reverted now to give you more screenshots of your instructions.

**Comment by NEZNAMY** [comment]
As long as it's fixed now I don't feel like investigating this any further then.

**Comment by dandud100** [comment]
> As long as it's fixed now I don't feel like investigating this any further then.

Yeah, i am happy with 4.0.0! Thanks. :)

**Comment by dandud100** [comment]
> As long as it's fixed now I don't feel like investigating this any further then.

I have another question, on the latest release version the plugin does not load anymore when using "ä,ü,ö" in the scoreboard. Is this possible on 4.0.0?

**Comment by NEZNAMY** [comment]
I didn't change anything regarding config loading. You probably don't have UTF-8 encoding.

**Comment by dandud100** [comment]
> I didn't change anything regarding config loading. You probably don't have UTF-8 encoding.

okay, tried it out and on 4.0.0 the plugin does not crash if i use ä,ö,ü.
