### ISSUE TITLE
After using the /tab reload command, it gives an error in the error.log file.

### ISSUE THREAD

**Issue by TeQTabanca** [NEZNAMY/TAB#891]
### Server version

1.12.2-Spigot

### TAB version

3.2.2 and 4.0.0-SNAPSHOT

### Error.log (3.2.2)

```
09.05.2023 - 11:49:13 - [TAB v3.3.2] Tried to modify non-existing team 7TeqTabancaA for player Test
09.05.2023 - 11:49:13 - [TAB v3.3.2] Tried to modify non-existing team 6TestA for player TeqTabanca
09.05.2023 - 11:49:13 - [TAB v3.3.2] An error was thrown when executing task
09.05.2023 - 11:49:13 - java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.shared.features.PlaceholderManagerImpl.getPlaceholder(String)" because the return value of "me.neznamy.tab.shared.TAB.getPlaceholderManager()" is null
09.05.2023 - 11:49:13 - 	at me.neznamy.tab.shared.placeholders.TabPlaceholder.setPlaceholders(TabPlaceholder.java:136)
09.05.2023 - 11:49:13 - 	at me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.updateValue(PlayerPlaceholderImpl.java:85)
09.05.2023 - 11:49:13 - 	at me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.lambda$updateValue$0(PlayerPlaceholderImpl.java:91)
09.05.2023 - 11:49:13 - 	at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:84)
09.05.2023 - 11:49:13 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
09.05.2023 - 11:49:13 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
09.05.2023 - 11:49:13 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
09.05.2023 - 11:49:13 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
09.05.2023 - 11:49:13 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
09.05.2023 - 11:49:13 - 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Error.log (4.0.0-SNAPSHOT)

```
09.05.2023 - 21:37:32 - [TAB v4.0.0-SNAPSHOT] An error occurred when reading packets
09.05.2023 - 21:37:32 - java.lang.NullPointerException: expectedTeam is marked non-null but is null
09.05.2023 - 21:37:32 - 	at me.neznamy.tab.shared.features.injection.PipelineInjector.logTeamOverride(PipelineInjector.java:61)
09.05.2023 - 21:37:32 - 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector.modifyPlayers(BukkitPipelineInjector.java:140)
09.05.2023 - 21:37:32 - 	at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:120)
09.05.2023 - 21:37:32 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
09.05.2023 - 21:37:32 - 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
09.05.2023 - 21:37:32 - 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
09.05.2023 - 21:37:32 - 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
09.05.2023 - 21:37:32 - 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
09.05.2023 - 21:37:32 - 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
09.05.2023 - 21:37:32 - 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
09.05.2023 - 21:37:32 - 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
09.05.2023 - 21:37:32 - 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:200)
09.05.2023 - 21:37:32 - 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:354)
09.05.2023 - 21:37:32 - 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
09.05.2023 - 21:37:32 - 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
09.05.2023 - 21:37:32 - 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
09.05.2023 - 21:37:32 - 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
09.05.2023 - 21:37:32 - 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce (if known)

**Step 1: /tab reload**

### Additional info

**- In version 4.0.0-SNAPSHOT, the eGlow and TAB-Additions plugin will not work properly.**

eGlow Error:

```
[21:37:14 WARN]: [eGlow] Task #33 for eGlow v3.2.3 generated an exception
java.lang.NoSuchMethodError: 'me.neznamy.tab.api.config.ConfigurationFile me.neznamy.tab.api.TabAPI.getConfig()'
        at me.MrGraycat.eGlow.Addon.TAB.TABAddon.loadTABSettings(TABAddon.java:60) ~[?:?]
        at me.MrGraycat.eGlow.Addon.TAB.TABAddon.<init>(TABAddon.java:33) ~[?:?]
        at me.MrGraycat.eGlow.EGlow$1.run(EGlow.java:121) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

TAB-Additions Error:

```
[21:37:12 INFO]: [TAB-Additions] Enabling TAB-Additions v1.7.1
[21:37:12 ERROR]: Error occurred while enabling TAB-Additions v1.7.1 (Is it up to date?)
java.lang.NoClassDefFoundError: me/neznamy/tab/api/config/ConfigurationFile
        at io.github.tanguygab.tabadditions.spigot.TABAdditionsSpigot.onEnable(TABAdditionsSpigot.java:18) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: me.neznamy.tab.api.config.ConfigurationFile
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more
```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
for eGlow and TAB-Additions, that's expected. 4.0.0 did lots of changes requiring other plugins to update. I've updated TAB-Additions but haven't released it yet since 4.0.0 isn't out yet, and eGlow's dev will probably update as well once the update comes out

**Comment by TeQTabanca** [comment]
> for eGlow and TAB-Additions, that's expected. 4.0.0 did lots of changes requiring other plugins to update. I've updated TAB-Additions but haven't released it yet since 4.0.0 isn't out yet, and eGlow's dev will probably update as well once the update comes out

**I forwarded the error to the author of the eGlow plugin, he said he'd take a look.**

**Comment by TeQTabanca** [comment]
> Try latest build for the TAB error.

**I tried, it gave such an error in the error.log file now.**

```
09.05.2023 - 22:21:38 - [TAB v4.0.0-SNAPSHOT] Tried to modify non-existing team 7TeqTabancaA for player Test
09.05.2023 - 22:21:38 - [TAB v4.0.0-SNAPSHOT] Tried to modify non-existing team 6TestA for player TeqTabanca
```

**Comment by NEZNAMY** [comment]
Can you set debug: true in config and send full server log when it happens again?

**Comment by NEZNAMY** [comment]
So it's always on reload? Can you send all of your TAB configuration files?

**Comment by TeQTabanca** [comment]
> So it's always on reload? Can you send all of your TAB configuration files?

**So every time it reloads it shows the same error. The TAB plugin's settings are at default.**

**Comment by TeQTabanca** [comment]
**I found the problem. When I set the nametag-in-range property in the TAB-Additions plugin to a number higher than 1, it gives this error.**

**Comment by NEZNAMY** [comment]
Well then it's not a bug in TAB itself.

**Comment by TeQTabanca** [comment]
> Well then it's not a bug in TAB itself.

**Yes it looks like that.**

**Comment by NEZNAMY** [comment]
Any more issues with TAB itself?

**Comment by TeQTabanca** [comment]
> Any more issues with TAB itself?

Currently there is no problem with the TAB plugin.

**Comment by TeQTabanca** [comment]
**Every time the players log into the server, it gives this message in the anti-override.log file. It persists even though I turned off the anti-override feature.**

```
10.05.2023 - 15:17:43 - [TAB v4.0.0-SNAPSHOT] Something just tried to add player Test into team a0a96264-ac4b-4 (expected team: ￿26TestA)
10.05.2023 - 15:17:58 - [TAB v4.0.0-SNAPSHOT] Something just tried to add player TeqTabanca into team d36b830e-e2de-4 (expected team: ￿20TeqTabancaA)
```

**Comment by Tanguygab** [comment]
That's not an issue with TAB, some plugin is trying to change players' teams

**Comment by TeQTabanca** [comment]
**I tested the enable-collision feature, it doesn't seem to work.**

**Comment by NEZNAMY** [comment]
That means you disabled collision in paper config.
