### ISSUE TITLE
name is marked non-null but is null

### ISSUE THREAD

**Issue by LuchoMorete** [NEZNAMY/TAB#892]
### Server version

Purpur 1.19.4

### TAB version

3.3.2

### Stack trace

<html>
<body>

1 | [20:48:43 INFO]: [TAB] [TAB v3.3.2] Failed to disable
-- | --
2 | [20:48:43 INFO]: [TAB] java.lang.NullPointerException: name is marked non-null but is null
3 | [20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.TabScoreboard.unregisterTeam(TabScoreboard.java:87)
4 | [20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.features.nametags.NameTag.unload(NameTag.java:73)
5 | [20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.features.nametags.unlimited.NameTagX.unload(NameTagX.java:97)
6 | [20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.backend.features.unlimitedtags.BackendNameTagX.unload(BackendNameTagX.java:62)
7 | [20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.FeatureManagerImpl.unload(FeatureManagerImpl.java:55)
8 | [20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.TAB.unload(TAB.java:182)
9 | [20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:21)
10 | [20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:55)
11 | [20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.platforms.bukkit.BukkitTAB$TABCommand.onCommand(BukkitTAB.java:128)
12 | [20:48:43 INFO]: [TAB]  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
13 | [20:48:43 INFO]: [TAB]  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
14 | [20:48:43 INFO]: [TAB]  at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:920)
15 | [20:48:43 INFO]: [TAB]  at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:883)
16 | [20:48:43 INFO]: [TAB]  at net.minecraft.server.dedicated.DedicatedServer.bh(DedicatedServer.java:541)
17 | [20:48:43 INFO]: [TAB]  at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:488)
18 | [20:48:43 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
19 | [20:48:43 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1195)
20 | [20:48:43 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
21 | [20:48:43 INFO]: [TAB]  at java.base/java.lang.Thread.run(Thread.java:833)
22 | [20:48:43 WARN]: [PlaceholderAPI] Failed to load expansion tab. Identifier is already in use.

</body>
</html>[20:48:43 INFO]: [TAB] [TAB v3.3.2] Failed to disable
[20:48:43 INFO]: [TAB] java.lang.NullPointerException: name is marked non-null but is null
[20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.TabScoreboard.unregisterTeam(TabScoreboard.java:87)
[20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.features.nametags.NameTag.unload(NameTag.java:73)
[20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.features.nametags.unlimited.NameTagX.unload(NameTagX.java:97)
[20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.backend.features.unlimitedtags.BackendNameTagX.unload(BackendNameTagX.java:62)
[20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.FeatureManagerImpl.unload(FeatureManagerImpl.java:55)
[20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.TAB.unload(TAB.java:[1](https://mclo.gs/b3HoPqr#L1)8[2](https://mclo.gs/b3HoPqr#L2))
[20:48:4[3](https://mclo.gs/b3HoPqr#L3) INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:21)
[20:[4](https://mclo.gs/b3HoPqr#L4)8:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:[5](https://mclo.gs/b3HoPqr#L5)5)
[20:48:43 INFO]: [TAB]  at TAB v3.3.2.jar//me.neznamy.tab.platforms.bukkit.BukkitTAB$TABCommand.onCommand(BukkitTAB.java:128)
[20:48:43 INFO]: [TAB]  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:48:43 INFO]: [TAB]  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:1[6](https://mclo.gs/b3HoPqr#L6)[8](https://mclo.gs/b3HoPqr#L8))
[20:48:43 INFO]: [TAB]  at org.bukkit.craftbukkit.v1_1[9](https://mclo.gs/b3HoPqr#L9)_R3.CraftServer.dispatchCommand(CraftServer.java:920)
[20:48:43 INFO]: [TAB]  at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:883)
[20:48:43 INFO]: [TAB]  at net.minecraft.server.dedicated.DedicatedServer.bh(DedicatedServer.java:541)
[20:48:43 INFO]: [TAB]  at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:488)
[20:48:43 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[20:48:43 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:[11](https://mclo.gs/b3HoPqr#L11)95)
[[20](https://mclo.gs/b3HoPqr#L20):48:43 INFO]: [TAB]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[20:48:43 INFO]: [TAB]  at java.base/java.lang.Thread.run(Thread.java:833)
[20:48:43 WARN]: [PlaceholderAPI] Failed to load expansion tab. Identifier is already in use.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/f18e731e-388d-45a7-907b-bf7ce317192e)
Is that on every reload?

**Comment by NEZNAMY** [comment]
@LuchoMorete can you try latest build from actions?

**Comment by NEZNAMY** [comment]
I made various changes and this issue should no longer be present in the next version, considering this resolved with the issue creator being inactive as well.
