### ISSUE TITLE
Disconnect error

### ISSUE THREAD

**Issue by Xitryne** [NEZNAMY/TAB#922]
### Server version

Waterfall 1.19 Build 535

### TAB version

3.3.2

### Stack trace

```
The user Xiitrine has successfully logged in.
The user Xiitrine logged in automatically for having a premium account.
12:05:10
[/151.80.79.173:47910]: <-> InitialHandler has pinged
12:05:16
[Xiitrine|/82.66.218.97:51308]: <-> ServerConnector [Skyblock] has connected
[/82.66.218.97:51308|Xiitrine]: <-> DownstreamBridge <-> [Hub] has disconnected
ERROR12:05:16
[/82.66.218.97:51308|Xiitrine]: -> UpstreamBridge - encountered exception
Console12:05:16
io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.PlayerPublicKey.getExpiry()" because "item.publicKey" is null
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:145) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.PlayerPublicKey.getExpiry()" because "item.publicKey" is null
at net.md_5.bungee.protocol.packet.PlayerListItemUpdate.write(PlayerListItemUpdate.java:91) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:24) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
... 16 more
INFO12:05:16
[Xiitrine]: disconnected with: EncoderException : java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.PlayerPublicKey.getExpiry()" because "item.publicKey" is null @ io.netty.handler.codec.MessageToByteEncoder:125
```

### Additional info

If I remove your plugin I have no more problems, it happens randomly when a player joins and a person is connected.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [x] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Xitryne** [comment]
```
13.06.2023 - 10:13:31 - [TAB v3.3.2] Failed to load data of *Tino3t from MySQL
13.06.2023 - 10:13:31 - com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 30,315,949 milliseconds ago. The last packet sent successfully to the server was 30,315,949 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
13.06.2023 - 10:13:31 - 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)
13.06.2023 - 10:13:31 - 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
13.06.2023 - 10:13:31 - 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
13.06.2023 - 10:13:31 - 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
13.06.2023 - 10:13:31 - 	at me.neznamy.tab.shared.config.MySQL.getCRS(MySQL.java:60)
13.06.2023 - 10:13:31 - 	at me.neznamy.tab.shared.config.mysql.MySQLUserConfiguration.lambda$load$7(MySQLUserConfiguration.java:121)
13.06.2023 - 10:13:31 - 	at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:84)
13.06.2023 - 10:13:31 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
13.06.2023 - 10:13:31 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
13.06.2023 - 10:13:31 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
13.06.2023 - 10:13:31 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
13.06.2023 - 10:13:31 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
13.06.2023 - 10:13:31 - 	at java.base/java.lang.Thread.run(Thread.java:833)
```
This error in error.log, this error does not occur at the same time as the one reported above

**Comment by NEZNAMY** [comment]
Did you enable global playerlist or layout?

**Comment by NEZNAMY** [comment]
Also try latest build from github actions.

**Comment by Xitryne** [comment]
The global list is activated, I have the bridge on all my other servers, I have the free version too ^^

**Comment by Xitryne** [comment]
The 3.3.2 on github is the same as the one on the other sites?

**Comment by Xitryne** [comment]
My server accepts cracks too

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/suites/13434435626/artifacts/736458774 this is latest build from actions

**Comment by Xitryne** [comment]
I'll have to download the latest version of the bridge too, I suppose ?

**Comment by NEZNAMY** [comment]
Yes, 3.0.0 bridge.

**Comment by Xitryne** [comment]
I will try this, thanks for the fast support

**Comment by NEZNAMY** [comment]
This is not support, support is paid.

**Comment by NEZNAMY** [comment]
I checked the code again and this issue should definitely be fixed already.

**Comment by Xitryne** [comment]
So for the last build on github or even on the one I had it should have been solved?

**Comment by NEZNAMY** [comment]
Only the last build from actions, marked as 4.0.0-SNAPSHOT.

**Comment by Xitryne** [comment]
[config.txt](https://github.com/NEZNAMY/TAB/files/11744785/config.txt)

**Comment by NEZNAMY** [comment]
I meant your config from 3.3.2. I guess you don't have it anymore. Let me know if updating fixed it.

**Comment by Xitryne** [comment]
Oh ok sorry, so far I haven't had any problems, but it happens randomly

**Comment by NEZNAMY** [comment]
If you don't get the issue within 24 hours, I'll consider it fixed.
