### ISSUE TITLE
Error on /sb

### ISSUE THREAD

**Issue by aml2023529** [NEZNAMY/TAB#927]
### Server version

1.19.4

### TAB version

4.0.1

### Stack trace

[08:29:01 INFO]: Ami_donkey issued server command: /csb
[08:29:01 ERROR]: Could not pass event PlayerCommandPreprocessEvent to TAB v4.0.1
java.lang.IllegalArgumentException: 1 > 0
        at java.util.Arrays.copyOfRange(Arrays.java:3782) ~[?:?]
        at java.util.Arrays.copyOfRange(Arrays.java:3742) ~[?:?]
        at me.neznamy.tab.shared.command.scoreboard.ScoreboardCommand.execute(ScoreboardCommand.java:42) ~[TAB v4.0.1.jar:?]
        at me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:56) ~[TAB v4.0.1.jar:?]
        at me.neznamy.tab.shared.features.scoreboard.ScoreboardManagerImpl.onCommand(ScoreboardManagerImpl.java:152) ~[TAB v4.0.1.jar:?]
        at me.neznamy.tab.shared.FeatureManager.onCommand(FeatureManager.java:184) ~[TAB v4.0.1.jar:?]
        at me.neznamy.tab.shared.platform.EventListener.command(EventListener.java:107) ~[TAB v4.0.1.jar:?]
        at me.neznamy.tab.platforms.bukkit.BukkitEventListener.onCommand(BukkitEventListener.java:36) ~[TAB v4.0.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor888.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2273) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2257) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
* 
![image](https://github.com/NEZNAMY/TAB/assets/6338394/c02b51a5-2c0e-4ccc-941e-f876100cc284)
* Confusing title
* No steps to reproduce

**Comment by aml2023529** [comment]
I'm sorry, my foreign language is not very good and I rely on translation

**Comment by Tanguygab** [comment]
try updating to 4.0.1 @aml2023529

**Comment by NEZNAMY** [comment]
That won't do, I fixed it later, see milestone.

**Comment by Tanguygab** [comment]
ah alright

**Comment by postyizhan** [comment]
I'm also getting the same error
