### ISSUE TITLE
Error scoreboard /sb

### ISSUE THREAD

**Issue by euj3ne** [NEZNAMY/TAB#932]
### Server version

Velocity 3.2.0

### TAB version

4.0.1

### Stack trace

[08:38:38] [Velocity Async Event Executor - #1/INFO] [com.velocitypowered.proxy.protocol.packet.chat.CommandHandler]: Exception occurred while running command for euj3ne
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command btab scoreboard for [connected player] euj3ne (/104.28.198.247:59516)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command btab scoreboard for [connected player] euj3ne (/104.28.198.247:59516)
	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:239) ~[velocity.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:264) ~[velocity.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
Caused by: java.lang.IllegalArgumentException: 1 > 0
	at java.util.Arrays.copyOfRange(Arrays.java:3782) ~[?:?]
	at java.util.Arrays.copyOfRange(Arrays.java:3742) ~[?:?]
	at me.neznamy.tab.shared.command.scoreboard.ScoreboardCommand.execute(ScoreboardCommand.java:42) ~[?:?]
	at me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:56) ~[?:?]
	at me.neznamy.tab.platforms.velocity.VelocityTabCommand.execute(VelocityTabCommand.java:30) ~[?:?]
	at me.neznamy.tab.platforms.velocity.VelocityTabCommand.execute(VelocityTabCommand.java:15) ~[?:?]
	at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:226) ~[velocity.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:264) ~[velocity.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
	
Everything works, except for the scoreboard and the command to turn on the scoreboard.
I myself contributed the velocity-plugin.json file - by the way, when you do this, once you support velocity.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
#927 
?

![image](https://github.com/NEZNAMY/TAB/assets/6338394/a3f99e93-4a1c-4579-9a56-a652e551e4aa)
??

![image](https://github.com/NEZNAMY/TAB/assets/6338394/dcf533d4-eb86-4d63-bf33-959429959710)
![image](https://github.com/NEZNAMY/TAB/assets/6338394/25e63a22-bd6b-47ed-b6af-d3559a11bb8a)
???

**Comment by euj3ne** [comment]
By the way, I read the checkboxes) I put it just for fun
Have a nice day author!

**Comment by euj3ne** [comment]
![Screenshot_1](https://github.com/NEZNAMY/TAB/assets/109100606/b7389def-c3d0-45a1-bfd2-951dac889efa)
![Screenshot_2](https://github.com/NEZNAMY/TAB/assets/109100606/19ac47fa-0f60-4962-b2e0-ccd7bc752d98)

**Comment by NEZNAMY** [comment]
Not ready for production. You **will** have issues and I am **not**  interested in losing my sanity trying to resolve them.

**Comment by euj3ne** [comment]
On plugin version 3.3.2, the scoreboard works, but on 4.0.1 it does not work

**Comment by NEZNAMY** [comment]
Velocity is not supported. This conversation is over.

**Comment by euj3ne** [comment]
:(

**Comment by euj3ne** [comment]
You put in another topic Resolution: Fixed
Did you fix it?

**Comment by NEZNAMY** [comment]
In the commit linked to it.

**Comment by euj3ne** [comment]
So what if I bet on a bungeecord or a spigot, will it give an error? Possible fix?

**Comment by NEZNAMY** [comment]
4.0.1 has the error. Future versions will not have it anymore.

**Comment by euj3ne** [comment]
okay, I get it. Thanks a lot!
