### ISSUE TITLE
/sb not recognized and log error, but the command still work for toggling.

### ISSUE THREAD

**Issue by dandud100** [NEZNAMY/TAB#951]
### Server version

This server is running Paper version git-Paper-46 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### TAB version

4.0.1

### Describe the bug

Type /sb with the tab.scoreboard.toggle permission, the scoreboard gets toggled, but the autocomplete to show this command does not work and also there is an error message in console.

### Expected behavior

Command is recognized by tab complete and no error in logs.

### Steps to reproduce

/sb

### Additional info

```[19:11:40] [Server thread/INFO]: Pokemoon issued server command: /sb
[19:11:40] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to TAB v4.0.1
java.lang.IllegalArgumentException: 1 > 0
	at java.util.Arrays.copyOfRange(Arrays.java:3782) ~[?:?]
	at java.util.Arrays.copyOfRange(Arrays.java:3742) ~[?:?]
	at me.neznamy.tab.shared.command.scoreboard.ScoreboardCommand.execute(ScoreboardCommand.java:42) ~[TAB.v4.0.1.jar:?]
	at me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:56) ~[TAB.v4.0.1.jar:?]
	at me.neznamy.tab.shared.features.scoreboard.ScoreboardManagerImpl.onCommand(ScoreboardManagerImpl.java:152) ~[TAB.v4.0.1.jar:?]
	at me.neznamy.tab.shared.FeatureManager.onCommand(FeatureManager.java:184) ~[TAB.v4.0.1.jar:?]
	at me.neznamy.tab.shared.platform.EventListener.command(EventListener.java:107) ~[TAB.v4.0.1.jar:?]
	at me.neznamy.tab.platforms.bukkit.BukkitEventListener.onCommand(BukkitEventListener.java:36) ~[TAB.v4.0.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor626.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-46]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-46]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-46]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2275) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2259) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-46]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-46]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-46]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-46]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-46]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-46]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-46]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-46]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
update
