### ISSUE TITLE
Does TAB fully support Velocity?

### ISSUE THREAD

**Issue by veteranmina** [NEZNAMY/TAB#965]
### Server version

Velocity - 3.2.0 Snapshot 260

### TAB version

4.0.2

### Stack trace

ERROR13:05:36
Unable to load plugin plugins/TAB.v4.0.2.jar
Console13:05:36
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file TAB.v4.0.2.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:154) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:64) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:345) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]

### Steps to reproduce (if known)

Load Velocity 3.2.0 snapshot 260 and TAB 4.0.2, attempt to start server results in TAB being detected as a bungee/bukkit plugin

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by veteranmina** [comment]
Sorry about that....misunderstood that it doesn't load at all and that it was limited. Sad to see that communities are toxic for a great plugin.

**Comment by PetMeetup-Adoption** [comment]
@veteranmina wdym how are they rude/toxic

**Comment by veteranmina** [comment]
> @veteranmina wdym how are they rude/toxic

It's noted here

https://gist.github.com/NEZNAMY/21c1aabe57a0a462ee175386c510fdf8
