### ISSUE TITLE
1.8 Error

### ISSUE THREAD

**Issue by TheWylot** [NEZNAMY/TAB#969]
### Server version

Flamepaper 1.8.9

### TAB version

4.0.3

### Describe the bug

[01:36:22 INFO]: [TAB] [TAB v4.0.3] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[01:36:22 INFO]: [TAB] java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.Integer (java.util.LinkedHashMap and java.lang.Integer are in module java.base of loader 'bootstrap')
[01:36:22 INFO]: [TAB]  at me.neznamy.tab.shared.MisconfigurationHelper.fixRefreshIntervals(MisconfigurationHelper.java:41)
[01:36:22 INFO]: [TAB]  at me.neznamy.tab.shared.features.PlaceholderManagerImpl.<init>(PlaceholderManagerImpl.java:56)
[01:36:22 INFO]: [TAB]  at me.neznamy.tab.shared.TAB.load(TAB.java:149)
[01:36:22 INFO]: [TAB]  at me.neznamy.tab.platforms.bukkit.BukkitTAB.onEnable(BukkitTAB.java:38)
[01:36:22 INFO]: [TAB]  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[01:36:22 INFO]: [TAB]  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[01:36:22 INFO]: [TAB]  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[01:36:22 INFO]: [TAB]  at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[01:36:22 INFO]: [TAB]  at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[01:36:22 INFO]: [TAB]  at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:373)
[01:36:22 INFO]: [TAB]  at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:337)
[01:36:22 INFO]: [TAB]  at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[01:36:22 INFO]: [TAB]  at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:255)
[01:36:22 INFO]: [TAB]  at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
[01:36:22 INFO]: [TAB]  at java.base/java.lang.Thread.run(Thread.java:834)

### Expected behavior

not sure but i got that errors

### Steps to reproduce

just start server with v4.0.3

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Your configuration was supposed to be converted. Save the config, delete it, regenerate and paste configured parts back.

**Comment by TheWylot** [comment]
Alright!

**Comment by NEZNAMY** [comment]
Replaced with a warn.
