### ISSUE TITLE
How do I make TAB on bungee compatible with PremiumVanish on bungee?

### ISSUE THREAD

**Issue by AriaCraft2019** [NEZNAMY/TAB#993]
### Server version

waterfall 536

### TAB version

4.0.3

### Stack trace

[17:34:53 INFO] [TAB]: [TAB v4.0.3] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
[17:34:53 INFO] [TAB]: java.lang.IllegalStateException: PremiumVanish must be enabled to use its API
[17:34:53 INFO] [TAB]:  at de.myzelyam.api.vanish.BungeeVanishAPI.checkPluginEnabled(BungeeVanishAPI.java:110)
[17:34:53 INFO] [TAB]:  at de.myzelyam.api.vanish.BungeeVanishAPI.isInvisible(BungeeVanishAPI.java:44)
[17:34:53 INFO] [TAB]:  at me.neznamy.tab.platforms.bungeecord.BungeeTabPlayer.isVanished(BungeeTabPlayer.java:137)
[17:34:53 INFO] [TAB]:  at me.neznamy.tab.shared.features.redis.message.PlayerJoin.write(PlayerJoin.java:33)
[17:34:53 INFO] [TAB]:  at me.neznamy.tab.shared.features.redis.RedisSupport.sendMessage(RedisSupport.java:202)
[17:34:53 INFO] [TAB]:  at me.neznamy.tab.shared.features.redis.RedisSupport.onJoin(RedisSupport.java:172)
[17:34:53 INFO] [TAB]:  at me.neznamy.tab.shared.features.redis.RedisSupport.load(RedisSupport.java:159)
[17:34:53 INFO] [TAB]:  at me.neznamy.tab.shared.FeatureManager.load(FeatureManager.java:52)
[17:34:53 INFO] [TAB]:  at me.neznamy.tab.shared.TAB.load(TAB.java:155)
[17:34:53 INFO] [TAB]:  at me.neznamy.tab.shared.command.DisabledCommand.execute(DisabledCommand.java:31)
[17:34:53 INFO] [TAB]:  at me.neznamy.tab.platforms.bungeecord.BungeeTabCommand.execute(BungeeTabCommand.java:27)
[17:34:53 INFO] [TAB]:  at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:213)
[17:34:53 INFO] [TAB]:  at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:164)
[17:34:53 INFO] [TAB]:  at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30)
[17:34:53 INFO] [TAB]:  at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87)
[17:34:53 INFO] [TAB]:  at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168)
[17:34:53 INFO] [TAB]:  at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141)
[17:34:53 INFO] [TAB]:  at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:72)
[17:34:53 INFO] [TAB]:  at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[17:34:53 INFO]: Failed to enable due to an internal plugin error. Check console for more info.

### Steps to reproduce (if known)

TAB is installed on the bungee along with PremiumVanish.

### Additional info

I have read the wiki but it didn't solve the problem so I thought I'd ask for help, thanks.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/3a8432d3-cff7-4e82-922c-366f4f5d4f97)
Well known PV Bug.

**Comment by AriaCraft2019** [comment]
So it's unresolvable now is it?

**Comment by NEZNAMY** [comment]
I added a try/catch to avoid this error.
